### ISSUE TITLE
(Feat) add more function on backdrop

### ISSUE THREAD

**Issue by aleasaDev** [roman-rr/cupertino-pane#10]
I emplacements the script on ionic 5 and it is so beautiful.

Requesting features:

Can you please add the ability of backdrop color to be transparent from settings?

Also can you add more function like backdropClose like ability to change the pane to any Breakpoints. 
for example if the pane on top and when i click on backdrop drop, will minimize the pane to bottom or middle based on my choice on settings.

**Comment by roman-rr** [comment]
@aleasaDev 
> I emplacements the script on ionic 5 and it is so beautiful.

Thanks


> Also can you add more function like backdropClose like ability to change the pane to any Breakpoints.
for example if the pane on top and when i click on backdrop drop, will minimize the pane to bottom or middle based on my choice on settings.

Updated package, now you can make this: 
```javascript
let settings = {
  ...
  backdropTransparent: true,
  onBackdropTap: () => {
    this.cupertinoPane.moveToBreak('bottom');
  }
}
```

Or this: 
```javascript
let settings = {
  ...
  backdropTransparent: true,
  onBackdropTap: () => {
    this.cupertinoPane.destroy({animate: true});
  }
}
```

**Comment by aleasaDev** [comment]
Nice work, and thanks so much for fast response. It’s working pretty good on actual devices.
