### ISSUE TITLE
[BUG] The panel does not animate when present(), after the first time it is destroyed.

### ISSUE THREAD

**Issue by ebhsgit** [roman-rr/cupertino-pane#101]
**Describe the bug**

On the latest revision from **master** (7f2cb87c735f6ab684d34752665f2225222eaa5e)
After the first present + destroy. Then 2nd time the panel is presented, it no longer animates (from bottom to top).

The bug is reproducible on Android, and I have reproduced in JSBin.

See example code:
https://jsbin.com/kilecodito/3/edit?html,output

**To Reproduce**
Using the example (https://jsbin.com/kilecodito/3/edit?html,output)
Steps to reproduce the behaviour:
1. Click image to present panel
2. Click 'x' or 'Continue' to close panel
3. Click image to present panel again

**Expected behaviour**
The panel should animate from bottom to top.

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android 10
 - Browser: Chrome
 - Version: Latest stable

**Additional context**

- With ` backdrop: true`, everything still works correctly.
- v1.1.94 released on 14/11/2020 seems to be working ok

**Comment by ebhsgit** [comment]
I think it is to do with `transitionend` not firing in correct order.
Because I am also observing that `onDidPresent()` is not fired at the correct time, after the first time the panel is destroyed.

After the first `destory()`, all subsequent `present()` does not trigger `onDidPresent()` when the panel is presented.
Instead, the `onDidPresent()` is triggered after any action that causes a transition. Eg: `destroy()`, dragging the panel

So I tried to make a quick fix. See my branch below
https://github.com/ebhsgit/cupertino-pane/tree/test-fix

The result is not quite right, because on present() the 2nd time, the panel transitions down first, then is presented properly.

JSBin link for the attempted fix.
https://jsbin.com/qasufeqido/1/edit?html,output

**Comment by roman-rr** [comment]
@ebhsgit Please check latest commit. Should be fixed, with simple clearing destroy function.

**Comment by ebhsgit** [comment]
Thanks.
Latest commit seem to have fixed issue.
