### ISSUE TITLE
[BUG] Can't scroll horizontally on div in panel

### ISSUE THREAD

**Issue by sasafister** [roman-rr/cupertino-pane#102]
**Describe the bug**
When panel is opened, horizontal touch scroll it doesn't work

**To Reproduce**
It works when you try to scroll on web browser, but not on mobile Chrome 87.0.4280.86

**Expected behavior**
It should be scrollable on both devices

**Screenshots**
https://streamable.com/y2juez

**Desktop (please complete the following information):**
MacOS (Big Sur)
Chrome 
Version 87.0.4280.67

**Smartphone (please complete the following information):**
Huwaei Y6
Android 9
Chrome 
87.0.4280.86

**Comment by roman-rr** [comment]
@sasafister Checked iOS, scroll is works. All android issues i will handle with 1-2 weeks.

**Comment by sasafister** [comment]
@roman-rr ok... As this is really needed feature, I will check if I can help somehow.

**Comment by roman-rr** [comment]
@sasafister Fixed in master branch, you can use it. Will be included to next release.

**Comment by sasafister** [comment]
@roman-rr I tried, could get result as I wanted..Ok I will try on the next release. Btw. is there any way to trigger method when users drag pane to the top. Animation in that case is not triggered. I'm trying to find a way to fix that. Nothing happens when you swipe and drag to the top.

**Comment by roman-rr** [comment]
@sasafister 
If user drag to top, `onTransitionEnd` should be triggered. Aren't it ?

**Comment by sasafister** [comment]
@roman-rr horizontal now works ;) Good job!

Nope, onTransitionEnd doesn't trigger if you dragging all through the top. It never occurs because there is no animation triggered. I'm considering that we need onReachTop() so when the pane reach top, you trigger function. That's rough idea. Maybe we should open new Issue?

**Comment by roman-rr** [comment]
1. Can you record a video with tap and hold drag ? 
2. I will check better way to found top callback

**Comment by roman-rr** [comment]
@sasafister I will make `onReach(breakpoint)` callback if many request will appears. 
For this moment, you can check it with 

```javascript
onDragEnd: () => {
  if (drawer.getClosestBreakY() === window.innerHeight - YOUR_TOP_BREAKPOINT_HEIGHT) {
    // Here top reached
  }
}
```

I'm still need a video with horizontal scroll bug

**Comment by sasafister** [comment]
@roman-rr i opened new issue so it's easier to track progress. I will have to see how can I record screen on mobile, so I will post it here afterwards!

**Comment by roman-rr** [comment]
@sasafister reproduced scroll throttling when drag & scroll in one time. Search for fix

**Comment by roman-rr** [comment]
@sasafister Use horizontal scrolls in pair with option `touchAngle: 45`. Fixed stops and bugs when you already move pane. When you do scroll, pane shouldn't moved.

**Comment by sasafister** [comment]
@roman-rr 
> 
> 1. Can you record a video with tap and hold drag ?
> 2. I will check better way to found top callback

Check this lag when drag.

https://streamable.com/wpca3h

**Comment by roman-rr** [comment]
@roman-rr Could you reproduce with clear example, only pane with horizontal scrollable area, without this elements on background ? Throttling still exist ?

**Comment by sasafister** [comment]
It seems that something is breaking with swiperjs. It's workin fine! I will close this issue.
