### ISSUE TITLE
[BUG] currentBreak shows wrong position

### ISSUE THREAD

**Issue by sasafister** [roman-rr/cupertino-pane#103]
**Describe the bug**
When dragged, currentBreak function show 'old' position
Also, when just touched, it triggers onDrag method

**To Reproduce**
1. Initially opened panel
2. Drag up
3. Console log should show 'top'

**Expected behavior**
When dragged up currentBreak should show 'top'

**Screenshots**
https://streamable.com/c58vwo

**Desktop (please complete the following information):
MacOS (Big Sur)
Chrome
Version 87.0.4280.67

**Smartphone (please complete the following information):
Huwaei Y6
Android 9
Chrome
87.0.4280.86

**Additional context**

**Comment by sasafister** [comment]
Fix it with onTransitionEnd, even I think that on tap onDrag function should be triggered.

**Comment by roman-rr** [comment]
@sasafister All right, currentBreak changes after transition.
