### ISSUE TITLE
[BUG] when drag to the top, no event has been triggered

### ISSUE THREAD

**Issue by sasafister** [roman-rr/cupertino-pane#105]
**Describe the bug**
When you open panel and drag it to the top without leaving touch event, no event has been triggered even tough onTransitionEnd is set

**To Reproduce**
1. Create onTransitionEnd or onDragEnd method
2. Open panel
3. Touch and drag to the top without letting touch event go
4. See error (console log in methods)

**Expected behavior**
When reached to the top, both event's onTransitionEnd with this.currentBreak() === 'top' should be triggered

**Screenshots**
https://streamable.com/hn101s

** Desktop (please complete the following information):
MacOS (Big Sur)
Chrome
Version 87.0.4280.67

**Additional context**
```
settings: {
   onTransitionEnd: () => this.swiped(),
   onDidDismiss: () => this.extended = false,
       breaks: {
                middle: { enabled: true, height: 300, bounce: true },
                top: { enabled: true, height: 700 },
            },
       onDragEnd: () => {
            if (this.drawer.getClosestBreakY() === window.innerHeight - 700) {
                console.log('onDragEnd', this.drawer.currentBreak())
            }
        },
        touchAngles: 45
}
```

```
swiped() {
     if(this.drawer.currentBreak() === 'middle') {
         this.extended = false
     } else if (this.drawer.currentBreak() === 'top') {
         this.extended = true
     } else {
        this.drawer.destroy({animate:true})
     }
},
```

**Comment by roman-rr** [comment]
@
