### ISSUE TITLE
[BUG] Can't drag if background (backdrop) is scrollable (Chrome)

### ISSUE THREAD

**Issue by sasafister** [roman-rr/cupertino-pane#108]
**Describe the bug**
When you open Panel, if background is scrollable, you can scroll through background but can't drag panel at all (works on Safari not on Chrome). Sometimes, when you drag you are dragging both Panel and background (try on code example with n in 13)

**Expected behavior**
When panel is opened, backdrop or background should be completely disabled. No touch events or scroll events should be allowed.

**Screenshots**
[Code](https://stackblitz.com/edit/vue-tovtxu?file=src/App.vue)
[Demo](https://vue-tovtxu.stackblitz.io/)

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser Chrome 
 - Version Version 87.0.4280.88 

**Additional context**
If background is scrollable, and you want to drag panel, then it's laggy. To avoid this, we should fix this issue. So logically, when Panel is opened that's only place where user should interact.

**Comment by roman-rr** [comment]
@sasafister Any idea's around ? For example we have cases when users must have abilities to interact with map, or other elements. 
In my project i manually disable scroll events for background elements with opened pane, but touch event's still allow to.

**Comment by sasafister** [comment]
Hmmm...Maybe we should give them prop to enable / disable background scroll / touch completely? So when they will use map, they can enable it, otherwise it's disabled by default? Here, the problem is on Chrome / FF when you have scrollable content behind, you are not even able to drag up panel. It's just stuck.

**Comment by sasafister** [comment]
I think I've solved issue. So what I did is first create div with height to screen size and with overflow:auto than inside I've put scrollable content (background) and then outside of that div I've put Panel, so everything works fine for now.
