### ISSUE TITLE
(Feat) move the pane to bottom when click or drag outside the pane

### ISSUE THREAD

**Issue by aleasaDev** [roman-rr/cupertino-pane#11]
I have extra features if you interested.

For more efficiency, It’s good to minimize the pane to bottom if it’s in middle or top break and click or drag outside the pane (without effecting on dragging the body if possible)

Thanks

**Comment by roman-rr** [comment]
@aleasaDev
Thanks for idea. 

You can realize it with current pane methods and custom event listener for outside area. 

I will include this option out of the box is there are at least few requests will have from users.
