### ISSUE TITLE
[BUG] handleKeyboard is ignored on android

### ISSUE THREAD

**Issue by blahblehblah** [roman-rr/cupertino-pane#110]
tried setting handleKeyboard to false in android, it still keeps pushing the content over when the pane is in the middle's break.

plus a weird behavior is happening, look at this video please, first input does not push content, second one, pushes it a little over

https://streamable.com/as4fog

P.S: this is with handleKeyboard set to false

**Comment by roman-rr** [comment]
@blahblehblah What if you set `handleKeyboard: true` ?

**Comment by roman-rr** [comment]
@blahblehblah behavior is proper on your screen! 
Android push up view if keyboard height more than height from bottom to focused input. Thats why first input doesn't push view up, but second input lower than keyboard height, and view pushed. This is how android handle keyboard for webview.
