### ISSUE TITLE
[BUG] Pane is displayed when hidden after keyboard hide

### ISSUE THREAD

**Issue by sjregan** [roman-rr/cupertino-pane#112]
**Describe the bug**
If the pane has been opened and then hidden with `.hide()`, when the on-screen keyboard is hidden the pane is shown again. 

**To Reproduce**
1. Initialise and open the pane
2. Use `.hide()` to hide the pane
3. Focus on an input field to show on-screen keyboard
4. Tap elsewhere on screen to blur input field to hide on-screen keyboard

**Expected behavior**
I expect the pane to remain hidden after the on-screen keyboard has been hidden.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS

```
Ionic:

   Ionic CLI                     : 6.12.2
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.4
   @angular-devkit/schematics    : 11.0.4
   @angular/cli                  : 11.0.4
   @ionic/angular-toolkit        : 3.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 9.0.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 28 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 1.2.2

System:

   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 12.2 Build version 12B45b
```

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 14.3

**Comment by roman-rr** [comment]
@sjregan Already fixed on master. Will be included to next release.

**Comment by modvd** [comment]
This still happens in v1.2.7 on Android devices

**Comment by roman-rr** [comment]
@modvd i will check

**Comment by roman-rr** [comment]
@modvd please check that it completely fixed on master branch.

**Comment by modvd** [comment]
I have two panels. The first one has a middle and top break and has fitScreenHeight set to true. The second one has no breaks and fitHeight set to true. 

Before the fix, both panes would open when I hide the keyboard (by tapping outside and by clicking hardware back button).

After the fix, the first pane stays hidden. It is completely fixed. The second pane still opens when hiding the keyboard when tapping outside of the keyboard. It stays hidden when i hide the keyboard by tapping the hardware back button.

**Comment by modvd** [comment]
I did a little more tests and this bug still happens with panes with fitHeight set to true. And not when fitScreenHeight is set to true.
Plus, I get this warning "Cupertino Pane: middle breakpoint disabled" when I hide the keyboard.
It only happens when I hide the keyboard when clicking outside of it. Not when I use the hardware back button.

**Comment by roman-rr** [comment]
@modvd big thanks for investigations and help. It believes that's now it is completely done for all type of panes!
