### ISSUE TITLE
[BUG] React - Changing State in Ionic Router Breaks

### ISSUE THREAD

**Issue by leejustin** [roman-rr/cupertino-pane#115]
**Describe the bug**
With ReactJS, using `IonRouter` + `IonPage` + `setState` will cause issues with Cupertino Pane when calling `.hide()`.
```
Uncaught TypeError: Cannot read property 'style' of undefined
```

**To Reproduce**
I am using the boilerplate code to set up `IonReactRouter`. It is rendering the component `FlowContainer`.
```javascript
import React from "react";
import { IonRouterOutlet, IonSplitPane } from "@ionic/react";
import { IonReactRouter } from "@ionic/react-router";
import { Redirect, Route } from "react-router-dom";

/* Core CSS required for Ionic components to work properly */
import "@ionic/react/css/core.css";
import FlowContainer from "./components/FlowContainer";


const App: React.FC = () => {
  return (
        <IonReactRouter>
          <IonSplitPane contentId="main">
            <IonRouterOutlet id="main">
              <Route path="/main" component={FlowContainer} exact={true} />
              <Route exact path="/" render={() => <Redirect to="/main" />} />
            </IonRouterOutlet>
          </IonSplitPane>
        </IonReactRouter>
  );
};
export default App;
```

The `FlowContainer` component is set up to only contain `cupertino pane` code:
```javascript
import React, { useState } from 'react';

import { CupertinoPane, CupertinoSettings } from 'cupertino-pane';
import { IonButton, IonContent, IonPage } from '@ionic/react';

const FlowContainer = () => {

  let drawer = new CupertinoPane('.cupertino-pane', { backdrop: false });

  const [testValue, setTestValue] = useState("None");

  const openDrawer = () => {
    setTestValue("First");
    drawer.present({animate: true});
  }

  const closeDrawer = () => {
    drawer.hide();
  }

  return (
    <IonPage>
      <IonContent>
      <IonButton onClick={openDrawer}>Open First Pane</IonButton>
      <IonButton onClick={closeDrawer}>Close Pane</IonButton>
      <div className="cupertino-pane">
        Content displayed here
      </div>
      </IonContent>
    </IonPage>
  );
};

export default FlowContainer;
```

This will cause an error when I click the button that calls `.hide()`. Dragging the pane or pressing the close button native to the pane will not trigger the error.

The two ways to cause the error not to occur:
* If I remove `setTestValue("First");` and don't modify the component's state, then no error will occur
* If I remove `<IonPage>` from wrapping the component, the error will not occur as well

<img width="326" alt="Screen Shot 2020-12-30 at 10 30 27 PM" src="https://user-images.githubusercontent.com/2660448/103397891-17b04800-4aef-11eb-8dfb-2a7935552332.png">
<img width="326" alt="Screen Shot 2020-12-30 at 10 30 23 PM" src="https://user-images.githubusercontent.com/2660448/103397892-17b04800-4aef-11eb-802d-a889381cc836.png">
<img width="331" alt="Screen Shot 2020-12-30 at 10 30 32 PM" src="https://user-images.githubusercontent.com/2660448/103397885-154dee00-4aef-11eb-80fb-307319d0b209.png">

I'm happy to help test and bounce things around but I've spent a few hours troubleshooting this. The code I provided looks like it's the base-case to reproduce it on my end. I'm using `"@ionic/react-router": "^5.5.2"` and `"cupertino-pane": "^1.2.1"`

**Comment by leejustin** [comment]
Here's a really ugly workaround that I set up for now. Basically simulates clicking on the `buttonClose` element since that one doesn't seem to raise the issue I detailed above:
```javascript
  const closeDrawer = () => {
    const closeButtonElems = document.getElementsByClassName("close-button")
    if (closeButtonElems.length > 0) {
      closeButtonElems[0].click();
    }
  }
```

**Comment by roman-rr** [comment]
Hi @leejustin I will check in few days.

**Comment by roman-rr** [comment]
Hello @leejustin thank you for issue.
First of all, your code re-create CupertinoPane instance few times for one variable. 
You might see warning which notify your in that fact "selector already in use". 
If you check with console you might see that pane re-created few times, from element same. 
This is because of Ionic/React lifecycle hooks. 

I'm a little bit restructured your code and this is fix your issue: 
```javascript
import React, { useState } from 'react';

import { CupertinoPane  } from 'cupertino-pane';
import { IonButton, IonContent, IonPage, useIonViewDidEnter } from '@ionic/react';

let drawer: CupertinoPane;
const FlowContainer = () => {

  const [testValue, setTestValue] = useState("None");

  const openDrawer = () => {
    setTestValue("First");
    drawer.present({animate: true});
  }

  const closeDrawer = () => {
    drawer.hide();
  }

  useIonViewDidEnter(() => {
    drawer = new CupertinoPane('.cupertino-pane', { backdrop: false });
  });

  return (
    <IonPage>
      <IonContent>
      <IonButton onClick={openDrawer}>Open First Pane</IonButton>
      <IonButton onClick={closeDrawer}>Close Pane</IonButton>
      <div className="cupertino-pane">
        Content displayed here
      </div>
      </IonContent>
    </IonPage>
  );
};

export default FlowContainer;
```

I will also review ability to re-create CupertinoPane instance without issues, but anyway you must be sure always in your programs that you doesn't repeat operations even if it's const assignations!

**Comment by leejustin** [comment]
This is awesome. Thank you @roman-rr ! Appreciate the help even though it turns out that this is not an issue with the library.
