### ISSUE TITLE
Body scrolling

### ISSUE THREAD

**Issue by BenitoJedai** [roman-rr/cupertino-pane#117]
Hi how can fix whe drag panel body scrolling and aand panel not woek propely

**Comment by BenitoJedai** [comment]
@roman-rr please help-me

**Comment by BenitoJedai** [comment]
Body no have fixed size

**Comment by roman-rr** [comment]
Please re-create issue properly from template @BenitoJedai, or at least provide full detailed information with examples and sources. Then i will be able to help you.
