### ISSUE TITLE
Body scrollable issue panel showing

### ISSUE THREAD

**Issue by BenitoJedai** [roman-rr/cupertino-pane#118]
[](https://i.imgur.com/up5NZvm.png)  this is the ui but when open the panel here the issue 
![](https://i.imgur.com/QZhhdbb.png) ![](https://i.imgur.com/hA0av1B.png)
How i can fix this the body is a scrollable area

**Comment by BenitoJedai** [comment]
@roman-rr please help me

**Comment by roman-rr** [comment]
@BenitoJedai Could you please provide a sources ? From your screenshots i doesn't understand anything.
