### ISSUE TITLE
[BUG] Panel disappear when rotating the screen in web brower

### ISSUE THREAD

**Issue by baneJack** [roman-rr/cupertino-pane#119]
**Unexpected behaviour:**
1) When I use web browser, depending of panel start position; the panel disappear or there is a shift when i rotate the screen.
 
2) I display panel with elements list **without** hiding the bottom tab bar navigation, so when i scroll down the last element is hidden by the bottom bar. How to handle this case?
How can we reproduce the effect when the scrollbar is in bottom position (as you gallery example in: https://github.com/roman-rr/cupertino-pane)

3) Have you planned an event/callbacks that fire **only** when the scrollbar is in bottom position ?

**Comment by roman-rr** [comment]
Hello @baneJack thank you for issue!

1. Good point to work around. I did schedule this as a feature/enhancement to set proper pane positions on `window.resize` callback.
2. Try to play with `topperOverflowOffset`. Set some numbers, especially tab-bar height value. 
3. You are the first who's ask about this callbacks. I did not plan to include this callback into core, but if requests will appears frequently, i will do. Right now you can simply listen scroll bar element: 
```javascript
document.querySelector('SCROLL-ELEMENT').addEventListener('scroll', (s: any) => {
  console.log(s.target.scrollTop);
});
```

**Comment by baneJack** [comment]
Thank you @roman-rr for your work and quick efficient response.

**Comment by roman-rr** [comment]
@baneJack Orientation changes should be maintained automatically from `1.2.3.` version
