### ISSUE TITLE
Ability to read current state?

### ISSUE THREAD

**Issue by raminnoodle** [roman-rr/cupertino-pane#12]
Is there currently a way for me to retrieve the pane's location state (bottom, middle, top?)

**Comment by roman-rr** [comment]
@raminnoodle 
### currentBreak()
Method return current break position in text format ('top' | 'middle' | 'bottom)
```javascript
if (myPane.currentBreak() === 'top') {
    myPane.moveToBreak('bottom');
}
```

**Comment by raminnoodle** [comment]
Perfect, thank you! Love this component!

**Comment by roman-rr** [comment]
@raminnoodle i add this feature one day ago, please update package.

**Comment by raminnoodle** [comment]
Thank you so much. Absolutely love the pane! Spent weeks trying to get another one working properly this one works exactly as needed out of the box.
