### ISSUE TITLE
[Android] [BUG] Cannot set property 'scrollTop' of null

### ISSUE THREAD

**Issue by blahblehblah** [roman-rr/cupertino-pane#120]
On keyboard hide an error shows

cupertino-pane.esm.bundle.js:887 Uncaught TypeError: Cannot set property 'scrollTop' of null
    at cupertino-pane.esm.bundle.js:887
    at Object.fireWindowEvent (cordova.js:247)
    at Function.Keyboard.fireOnHiding (keyboard.js:32)
    at success (keyboard.js:76)
    at Object.callbackFromNative (cordova.js:295)
    at <anonymous>:1:9

`  if (!this.settings.handleKeyboard
            && this.device.cordova
            && this.device.android) {
            window.addEventListener('keyboardWillHide', () => {
                this.parentEl.scrollTop = 0;
                this.parentEl.parentElement.scrollTop = 0;
         this.parentEl.parentElement.parentElement.scrollTop = 0;
            });
        }`

this parentElement is null  > this.parentEl.parentElement.parentElement.scrollTop = 0;

**Comment by roman-rr** [comment]
Hello @blahblehblah you are disable keyboard handling ?

**Comment by roman-rr** [comment]
@blahblehblah Please check if solved in latest `b1ac0ac`

**Comment by blahblehblah** [comment]
I actually made the same changes you've done locally, it worked well, this happens when setting handleKeyboard to false,
 awesome, thank you
