### ISSUE TITLE
[QUESTION] Disable panning when scrolling horizontally inside pane

### ISSUE THREAD

**Issue by vesper8** [roman-rr/cupertino-pane#121]
I have this working almost perfectly except for one thing. Inside my pane content I have an area that is scrollable horizontally. When I try to interact with this using my finger, it keeps scrolling vertically and horizontally at the same time, often causing the pane to trigger one of the breakpoints. Is there a way to completely disable vertical scrolling/panning while interacting with this one horizontal scrolling div?

**Comment by roman-rr** [comment]
Hello @vesper8 
Have you try to set option `touchAngle: 45` ?

**Comment by vesper8** [comment]
@roman-rr thanks for the tip, that does seem to make it much better

One more thing.. this might not be possible at all but.. right now I have `topperOverflow` set to `true` which is the default. This is fine and is the desired behaviour.. except for my horizontal scrolling div.. which just happens to be visible when the pane is at the bottom breakpoint. Would it be possible to have certain divs scrollable (such as my horizontal scrolling div) even with `topperOverflow` being set to `true`

**Comment by roman-rr** [comment]
@vesper8 this is possible. You can set attr `overflow-y` to certain div, or set css `overflow-y: scroll !important'. If there is some issues, share code with me so i can help you in practice.

**Comment by roman-rr** [comment]
Closed for inactivity until sources or other information
