### ISSUE TITLE
[FEAT] maxHeight settings for use with fitHeight setting

### ISSUE THREAD

**Issue by sjregan** [roman-rr/cupertino-pane#122]
**What are you trying to add to Cupertino-Pane?**

Setting for maximum pane height when `fitHeight` setting is true. eg `maxHeight` - an integer representing maximum height in pixels.

*Describe your feature request **detailed***

If `fitHeight` is true and the pane contains a long list, the height of the displayed pane may end up the height of the window. If `maxHeight` was set, and the calculated pane height is greater than `maxHeight`, set the pane height to `maxHeight`.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[ X] No

**Is this related to an issue?**

[X] Yes (Give a link to the issue)
[ ] No

https://github.com/roman-rr/cupertino-pane/issues/113

**Comment by roman-rr** [comment]
@sjregan Please check in `v.1.2.2` option `fitScreenHeight: true`.

**Comment by sjregan** [comment]
@roman-rr I have seen the option `fitScreenHeight: true` thank you, what I would like to be able to do is set the maximum height of the pane to the height of the screen minus X pixels.

The reason for this is so the page title behind the pane can still be seen to give the pane context.

**Comment by roman-rr** [comment]
@sjregan Please check `1.2.3` 
```js
let settings = {
  fitHeight: true, 
  maxFitHeight: 400
};
```
