### ISSUE TITLE
[FEAT] Method to force recalculation of pane height when fitHeight setting is true

### ISSUE THREAD

**Issue by sjregan** [roman-rr/cupertino-pane#123]
**What are you trying to add to Cupertino-Pane?**

This relates to when `fitHeight` setting is true.

A method such as `recalculateHeight` that can be called on a drawer pane. When the method is called, the height of the pane is recalculated.

*Describe your feature request **detailed***

The contents of the pane may changed depending on user interaction or when API requests are complete. Currently the only way to fix the height of the pane is to destroy it and present it again. This creates a flicker as the backdrop is hidden and shown again.

https://user-images.githubusercontent.com/1580170/104992251-be479300-5a74-11eb-9150-d5b6374c2e63.mov

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[ X] No

**Is this related to an issue?**

[X ] Yes (Give a link to the issue)
[ ] No

https://github.com/roman-rr/cupertino-pane/issues/113

**Comment by roman-rr** [comment]
@sjregan added additional time for timeout in height calculation function. Please check first, if it is solve issue. 
If issue still exist, i will add method to update pane height.

**Comment by sjregan** [comment]
@roman-rr Thank you, this is not an issue with the existing code but a feature request based on a use case where the content of the pane changes. In the example above the content changes when an API request is completed.

In this instance, your pane library doesn't know when the content will be changed so a `recalculateHeight` method is required.

Thanks.

**Comment by roman-rr** [comment]
@sjregan Added async method `calcFitHeight()`. 
```js
this.pane.calcFitHeight();
```
