### ISSUE TITLE
[FEAT] Add indication on whether the pane was dismissed via close button

### ISSUE THREAD

**Issue by sjregan** [roman-rr/cupertino-pane#124]
**What are you trying to add to Cupertino-Pane?**

Add additional detail to the `onDidDismiss()` callback to indicate if the user clicked the close button, or whether the pane was dismissed programmatically.

*Describe your feature request **detailed***

The `onDidDismiss()` signature is `onDidDismiss: (event?: CustomEvent) => void`, however the event argument is always undefined.

This should be changed so there is an indication if the close button was clicked, or the pane was dismissed via the `destroy()` method.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[X ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[ X] No

**Comment by roman-rr** [comment]
Hello @sjregan 
In `v.1.2.2` you will receive `{destroyButton: true}` when destroy pane with destroy button from `onDidDismiss(event)`

**Comment by sjregan** [comment]
@roman-rr Thank you!

**Comment by sjregan** [comment]
@roman-rr Does the PaneSettings interface need to be updated in relation to this update? The callback is currently defined as:

`onDidDismiss: (event?: CustomEvent) => void`

**Comment by roman-rr** [comment]
@sjregan on this moment not required, as passed only one value. Later when few values will be passed, new interface can be created.
