### ISSUE TITLE
[BUG] Resize on Keyboard hide

### ISSUE THREAD

**Issue by jeremycastelli** [roman-rr/cupertino-pane#125]
**Describe the bug**
Hello,
On Android, as you can see in the video, my input updates a list, when I click on an item, it opens a pane, the keyboard disappear but the height seems not to be updated

**Expected behavior**
show the bottom part of the pane

**Screenshots**
https://user-images.githubusercontent.com/380859/105203546-89eed800-5b43-11eb-9da8-611c648d9e5d.mp4

**Smartphone (please complete the following information):**
Android

**Additional context**
I'm using version 1.22

I tried several options 
handleKeyboard: true or false,
fitScreenHeight: true
also
function keyboardClose () {
  pane.moveToBreak('top'); // or moveToHeight(current - keyboardHeight);
}
always same result
I'm using ionic/vue last version

**Comment by roman-rr** [comment]
@jeremycastelli Should be fixed within `1.2.3`, please try.

**Comment by jeremycastelli** [comment]
Hey thank you for the update but unfortunately it doesn't work :/

My guess is that it's a problem of the type: "it happens at the same moment"
something like :
click
pane init: size initialized with keyboard still open
input blur
keyboard hide
resize/orientation changed handler created (but maybe too late)

My workaround for now is adding a slight delay before initializing the pane. it works ok so don't worry if you don't want to investigate more on this.

thks

**Comment by roman-rr** [comment]
@jeremycastelli should be fixed in `v.1.2.4` because pane will pushed only for entries inputs elements. But if still not, please share example with bug in clear environment.
