### ISSUE TITLE
[BUG] Panel position after web browser refreshing

### ISSUE THREAD

**Issue by baneJack** [roman-rr/cupertino-pane#127]
First, thanks for #119 fixing
Unexpected behaviour:
1.	Open web browser (chrome for example)
2.	Panel is in middle position
3.	Minimize browser window
4.	Refresh page
5.	Maximize browser window
=> The panel position seems to be "stucked" (ie not resize)

**Comment by roman-rr** [comment]
@baneJack created some resize manager in `1.2.4`, but you must be sure that your breakpoints height not depend on screen height and static. On step #4 your pane instance created again and breakpoints saved for all next recalculating.
