### ISSUE TITLE
[BUG] calcFitHeight() throws error when called when pane has not been shown

### ISSUE THREAD

**Issue by sjregan** [roman-rr/cupertino-pane#128]
**Describe the bug**
The calcFitHeight() throws an error when called before the pane has been shown.

**To Reproduce**
1. Initialise pane.
2. Call calcFitHeight()
3. Error is shown in logs:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'style' of undefined
TypeError: Cannot read property 'style' of undefined
    at Breakpoints.<anonymous> (cupertino-pane.esm.bundle.js:882)
```

Line #882 is:
`this.instance.wrapperEl.style.visibility = 'hidden';`

**Expected behavior**
The calcFitHeight() function to recalculate the height without throwing an error.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 88.0.4324.96

**Additional context**
https://github.com/roman-rr/cupertino-pane/issues/123

**Comment by roman-rr** [comment]
@sjregan Thank you for your effort!
Fixed in master branch. 
Anyway you must call method after present: 

```js
this.pane = new CupertinoPane('.pane', settings);
this.pane.present({animate: true});
this.pane.calcFitHeight();
```

And better with some timeout
```js
this.pane = new CupertinoPane('.pane', settings);
this.pane.present({animate: true});
setTimeout(() => this.pane.calcFitHeight());
```
