### ISSUE TITLE
CurrentBreak method returns undefined

### ISSUE THREAD

**Issue by khancom1988** [roman-rr/cupertino-pane#129]
Hello,

I am very new to ionic framework but have used your library and this is awesome and helped my project a lot. Now I got stuck at one point where I have the find the currentBreak of the pane but somehow the pane is returning me undefined when I call myPane.currentBreak() method. Here is my implementation

ionViewWillEnter() {
    this.myPane = new CupertinoPane(
      ".cupertino-pane", // Pane container selector
      {
        parentElement: "body", // Parent container
        buttonDestroy: false,
        initialBreak: "bottom",
        breaks: {
          middle: { enabled: true, height: window.screen.height / 2, bounce: true },
          bottom: { enabled: true, height: 100 }
        },
        onDrag: (obj) => {
          console.log(obj.eventPhase)
        },
        onTransitionEnd: (obj) => {
          this.currentBreak = this.myPane.currentBreak()
          console.log(this.currentBreak)
        }
      }
    )
    this.myPane.present({ animate: false })
  }

**Comment by roman-rr** [comment]
@khancom1988 Thank you for issue, i will check.

**Comment by roman-rr** [comment]
Hey @khancom1988 
I checked your example. Value is always returned without issues. 

```javascript
import { Component } from '@angular/core';
import { CupertinoPane } from '../../../../cupertino-pane';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

  public myPane: CupertinoPane;
  public currentBreak: string;
  constructor() {}

  ionViewWillEnter() {
    this.myPane = new CupertinoPane(".cupertino-pane", // Pane container selector
      {
        parentElement: "body", // Parent container
        buttonDestroy: false,
        initialBreak: "bottom",
        breaks: {
        middle: { enabled: true, height: window.screen.height / 2, bounce: true },
        bottom: { enabled: true, height: 100 }
      },
      onDrag: (obj) => {
        console.log(obj.eventPhase)
      },
      onTransitionEnd: (obj) => {
        this.currentBreak = this.myPane.currentBreak();
        console.log(this.currentBreak); // Not undefined 
      }
    });
    this.myPane.present({ animate: false });
  }

}

```
