### ISSUE TITLE
Calculating middleBreakOffset Across Multiple Device sizes

### ISSUE THREAD

**Issue by jwburnside** [roman-rr/cupertino-pane#13]
Hello, thanks for this plugin, it is definitely an improvement over other options out there. 

I'm implementing this into an Ionic 4 project, but I am running into an issue calculating the middleBreakOffset based on the content of the pane. 

I have two boxes of equal height in the pane. I'm attempting to set the middleBreakOffset so that only the first box displays, and then when I pull the drawer the second box will display (and scroll if necessary). 

Here is an image of the desired middleBreak, where only the red box displays, when I explicitly set the middleBreakOffset in the configuration:

![red-displaying-only](https://user-images.githubusercontent.com/854180/75472749-f8daa580-5961-11ea-992c-9f0c556b9351.png)

However, when I attempt to run this example on a larger device, the green box displays slightly, as you can see in this image: 

![some-green-displaying](https://user-images.githubusercontent.com/854180/75472886-3808f680-5962-11ea-8133-6201f83d23f7.png)

So instead of setting the middleBreakOffset based on a determined pixel value, I have attempted a bunch of different calculations based on the content size and screen size to try and get it consistent across devices, but no luck. 

Can you give me an indication on how I can calculate the middleBreakOffset so that it will position the pane exactly the same on different screen sizes? Any help would be greatly appreciated. 

Here's the simple HTML I am testing with:

![markup](https://user-images.githubusercontent.com/854180/75474386-e6ae3680-5964-11ea-8528-25a1e7a50ae2.png)

**Comment by roman-rr** [comment]
@jwburnside Show your JavaScript/Typescript code also please for this page/view

**Comment by jwburnside** [comment]
Might be easier if I just set up a test repo with the behavior I see. Here is link:

https://github.com/jwburnside/cupertino-pane-test

I set it up so that it should load the same example in the post. 
Let me know if you need anything else, thanks!

**Comment by roman-rr** [comment]
@jwburnside 
Please check [Breaking Changes](https://github.com/roman-rr/cupertino-pane#breaking-changes)
Then update package. 

You can now just set offset you need which will strictly follow all devices
```javascript
let settings = {
    ...
    breaks: {
        middle: {
          enabled: true,
          offset: 410 // 410 pixels from screen bottom until pane top vertex
        }
      }
    }
};
```

For top position you can use still strict value, but i recommend to use value depending on device height (which is by default now): 
```javascript
let settings = {
    ...
    breaks: {
        top: { 
          enabled: true, 
          offset: window.screen.height - (135 * 0.35)
        }
      }
    }
};
```

Do not forget to specify `topperOverflowOffset` for scroll (in case you scrollable area not full visible): 
```javascript
let settings = {
    ...
    topperOverflowOffset: 20
};
```

**Comment by jwburnside** [comment]
Works perfectly now, thanks for the fast turnaround!
