### ISSUE TITLE
[FEAT] C++ with QT / QML supports

### ISSUE THREAD

**Issue by hadimousavi79** [roman-rr/cupertino-pane#131]
Hi dear roman-rr 
Can I use this in Qt and Qml in C++ language?
If your answer is positive how i use it in qml?
please help me

**Comment by roman-rr** [comment]
Hello @hadimousavi79 
In roadmap i have C++ and QT supporting. 
I don't sure how to implement it in a best way.
Re-write package fully to C++  or use some bridge like QML. 
I will make a re-search in future. 

I will appreciate your help also if you will make some re-search and will try to do it by yourself first. 
Or at least provide me some examples of good interfaces implementations written on QML + JavaScript.

**Comment by hadimousavi79** [comment]
Thank you @roman-rr

**Comment by roman-rr** [comment]
This repository is only related to js/ts version. I will push here information when any more hight level investigations will be activated such as QT/C++/C/Objective-C.
