### ISSUE TITLE
[BUG] Pane does not appear/disappears instantly when navigating to it

### ISSUE THREAD

**Issue by akharag** [roman-rr/cupertino-pane#132]
**Describe the bug**
When trying to navigate from a page without a cupertino pane to a page with one, the page might flash the cupertino-pane, but then it disappears.

**To Reproduce**

**page1.html**
------
```
<ion-content>
  <ion-button routerLink='/page2'>Login</ion-button>
</ion-content>
```
**page2.html**
------
```
<ion-content>
  <div class="main-pane">
   ...
   </div>
</ion-content>
```

**page2.js**

```
import { OnInit } from "@angular/core";

export class Page2 implements Oninit{
...
ngOnInit() {
    console.log("Loading Main Pane");
    this.mainPane = new CupertinoPane(".main-pane", {
      parentElement: "ion-content ",
      initialBreak: "middle",
      breaks: {
        top: { enabled: true, height: 1000 },
        middle: { enabled: true, height: 300 },
        bottom: {
          enabled: true,
          height: 30
        },
      },
      buttonClose: false,
      inverse: true,
    });

    this.mainPane.present({ animate: false });
    console.log("Main Pane loaded");
  }
...
}
```

CONSOLE: 
```
Loading Main Pane
Main Pane loaded
```

Same issue occurs when using AfterContentInit
**Expected behavior**

The cupertino pane to show as intended when navigated to the new page

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

When the page is refreshed from page2, the cupertino-pane properly shows.

Navigating back a page makes the cuperitno-pane appear. AKA when navigating, I think the cupertino-pane loads on the previous page, even though the initialization is in the first page

**Comment by roman-rr** [comment]
@akharag Thank you for issue. 
It would be nice if you can provide a video with flashing, so i can explore faster.

**Comment by akharag** [comment]
https://user-images.githubusercontent.com/22301549/107920029-ed1e2f80-6f74-11eb-8e7b-fbc86c71e5e9.mov

**Comment by roman-rr** [comment]
@akharag try to remove `parentElement: "ion-content"` from settings. 

```javascript
this.mainPane = new CupertinoPane(".main-pane", {
      parentElement: "ion-content ", // REMOVE THIS LINE
      initialBreak: "middle",
      ...
});
```

You have few ion-content in DOM when you create a page, and pane rendered to wrong element.

**Comment by akharag** [comment]
Yes, that worked.
