### ISSUE TITLE
Pane scrolls parent element on Device

### ISSUE THREAD

**Issue by jongbonga** [roman-rr/cupertino-pane#136]
**Describe the bug**
When opening and closing the drawer, the parent element also scrolls

**To Reproduce**
```
const drawer = new CupertinoPane('.drawer', {
      parentElement: ".test",
      bottomClose: false,
      bottomOffset: 40
    });
drawer.present()
```

**Expected behavior**
Parent element shouldn't be impacted by drawer

**Screenshots**

![drawer](https://user-images.githubusercontent.com/12111716/109522260-c0aafd00-7ab6-11eb-8d7f-bca5b1470257.gif)

**Smartphone:**
 - Device: iPhone 7
 - OS: iOS14.4

**Additional context**
I'm not experiencing the issue when testing on the browser, only when loaded on a device (iOS)

**Comment by roman-rr** [comment]
Thank you for issue @jongbonga !
Seem's that iOS appendix, and i'm always use `overflow-y: false` for parent of my panes. 
But let me check this part. If you would like to help me, please check that not reproduced on chrome and only for iOS/Safari/WebView ?

**Comment by jongbonga** [comment]
it's working fine on Brave/Chrome yes!

**Comment by roman-rr** [comment]
Hi @jongbonga 

### Solution A
The easy solution is to set 
```css
body, html {
  overflow-y: hidden;
}
```
Then wrap your scrollable content to div and make your div scrollable instead of body
```css
.content {
  overflow-y: scroll;
  height: 100vh;
}
```
### Solution B
Try to configure pane settings with this enhancements and set overflow dynamically 
```js
let settings = {
  ... 
  onTransitionEnd: (e) => {
    document.body.style.overflowY = "auto";
    document.querySelector('html').style.overflow = "auto";
  },
  onDidPresent: (e) => {
    let paneEl = document.querySelector('.cupertino-pane-wrapper .pane'); 
    paneEl.addEventListener('touchstart', () => {
      document.body.style.overflowY = "hidden";
      document.querySelector('html').style.overflow = "hidden";
    });
}
```

Hope it helps!
