### ISSUE TITLE
[BUG] Icon close color variable not working

### ISSUE THREAD

**Issue by derek90** [roman-rr/cupertino-pane#139]
**Describe the bug**
Setting the css variable --cupertino-pane-icon-close-color is not enough to change the close icon color

**To Reproduce**
Using **Ionic 5**, set the CSS variable `--cupertino-pane-icon-close-color: red` in the **variables.scss** file. After that, you will see that the color is still the default one.

**Expected behavior**
The color of the Cupertino Pane close icon should be red

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome

**Additional context**
After setting the CSS variable, it will only work if you override the close icon styles like follows:
```
.cupertino-pane-wrapper .destroy-button {
    fill: var(--cupertino-pane-icon-close-color);
}
```

**Comment by roman-rr** [comment]
@derek90 Thank you, already fixed. Will be available in `1.2.6`

**Comment by derek90** [comment]
Thank you very much for your work, it's awesome. Should I close this issue now or should we wait until the new realease is done?

**Comment by roman-rr** [comment]
@derek90 I will re-check after release and close by myself.
