### ISSUE TITLE
Close Pane with hardware backButton IonicReact

### ISSUE THREAD

**Issue by I-am-abdulazeez** [roman-rr/cupertino-pane#143]
Just a question, how do i close the pane with the hardware backButton in Ionic-React. i tried: 

```
        // Trying to get access to the backButton in the Component
    
     useEffect(() => {
        if (Capacitor.isNative) {
          App.addListener("backButton", (ev: any) => {
            ev.detail.register(100, async () => {
               hidePanel();
               // this is a hack that made the page stays by not navigating to the previous route.
               history.push(getPath);
            });
          });
        }
      });
    
    const hidePanel = async () => {
      console.log("Tapped");
      isShowing.current = false;
      await drawerRef.current?.destroy({ animate: true });
    };
```

**Comment by roman-rr** [comment]
Hello @I-am-abdulazeez
Have you try method discussed [here](https://github.com/roman-rr/cupertino-pane/issues/79) ? 
```js
document.addEventListener('backbutton', function(){
  pane.destroy({animate: true});
}, false);
```

**Comment by I-am-abdulazeez** [comment]
> ```js
> document.addEventListener('backbutton', function(){
>   pane.destroy({animate: true});
> }, false);
> ```

Please sir, will this code be in the root component or the Cupertino Component?

**Comment by roman-rr** [comment]
@I-am-abdulazeez 
Try this 
```js
 useEffect(() => {
    if (Capacitor.isNative) {
        // Add listener
        document.addEventListener('backbutton', function(){
            hidePanel();
        }, false);
    }
});
    
const hidePanel = async () => {
  console.log("Tapped");
  isShowing.current = false;
  await drawerRef.current?.destroy({ animate: true });
};
```

**Comment by I-am-abdulazeez** [comment]
It doesn't work sir, maybe because of this

```
if (Capacitor.isNative) {
      App.addListener("backButton", () => {
        if (
          window.location.pathname === "/" ||
          window.location.pathname === "/tab/home"
        ) {
          App.exitApp();
        } else if (
          window.location.pathname === "/tab/search" ||
          window.location.pathname === " /tab/brand" ||
          window.location.pathname === "/tab/chats" ||
          window.location.pathname === "/tab/notifications"
        ) {
          history.push("/tab/home");
        }
      });
    }
```

**Comment by roman-rr** [comment]
@I-am-abdulazeez 
First, add this to check that hardware listener is works: 
```js
if (Capacitor.isNative) {
  document.addEventListener('backbutton', function(){
        alert();
   }, false);
}
```

And then confirm that you able to see alert. 
NOTE: Write event name in lowercase `backbutton`. Not camelCase.

**Comment by roman-rr** [comment]
Closed as not related to Pane.

**Comment by roman-rr** [comment]
@I-am-abdulazeez You must disable hardware button first. 

For example with configuration in your app.module.ts (Angular): 
```
IonicModule.forRoot({
      hardwareBackButton: false
})
```

**Comment by I-am-abdulazeez** [comment]
Then, do i have to add backbutton event on every page?, beacause the above code disabled backbutton across the app, except the ones i added backbutton event.

**Comment by roman-rr** [comment]
@I-am-abdulazeez Then disable backbutton events doesn't help you. 

You would like to disable route-back with backbutton event for a specific single page. You must ask [ionic community](https://forum.ionicframework.com/) how to make it properly. Please send a link with your question here, i'm interesting to know such solution also.

**Comment by roman-rr** [comment]
@I-am-abdulazeez I made it for you https://forum.ionicframework.com/t/prevent-back-route-navigation-for-specific-page/208767

**Comment by roman-rr** [comment]
@roman-rr additionally you must read this page 
https://ionicframework.com/docs/developing/hardware-back-button
