### ISSUE TITLE
[FEAT] .destroy() to return a promise

### ISSUE THREAD

**Issue by rgoldiez** [roman-rr/cupertino-pane#144]
**What are you trying to add to Cupertino-Pane?**
We are using `.destroy({ animated: true })`.  It would be helpful if this returned a promise that resolved once the animation is complete and the pane has been destroyed.

**Is there an alternative at the latest version?**
`setTimeout` but that isn't a great solution.

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[ X ] No

**Comment by roman-rr** [comment]
Hello @rgoldiez thank you for issue!
You can try to use `onTransitionEnd` event, its should fit for your needs.

**Comment by rgoldiez** [comment]
Hi @roman-rr - I'm using `onTransitionEnd` for other functionality.  I could track `destroy` events and then resolve the promise over in `onTransitionEnd` ..... but that seems kind of messy.

**Comment by roman-rr** [comment]
@rgoldiez I will review possibility to covert present and destroy methods into promises functions.

**Comment by roman-rr** [comment]
@rgoldiez You can use `present()` and `destroy()` as promise in `v.1.2.7`
```js
await pane.present({animate: true});
pane.present({animate: true}).then(...)
```
