### ISSUE TITLE
Using Cupertino pane as an in app notification

### ISSUE THREAD

**Issue by jordanrzymski** [roman-rr/cupertino-pane#145]
I was wondering if you have any knowledgable of using this as a dynamic in app notification. Something that can dismiss any notification up at the time and can close after 2 seconds

I am looking for something better than an ion toast not as intrusive as an alert.

I am currently using ionic and capacitor 

thanks in advance

**Comment by roman-rr** [comment]
@jordanrzymski Sure you can create some service which will show notifications on the top based on cupertino-panes. But only i'm missing is why don't ion-toast complete your needs ?

**Comment by jordanrzymski** [comment]
Well it is a football score app and would be nice to show the team badges etc

**Comment by roman-rr** [comment]
@jordanrzymski `ion-toast` is not fully cover your needs ?

**Comment by jordanrzymski** [comment]
Ion-toast only allows text strings - no images or any formatting

**Comment by roman-rr** [comment]
@jordanrzymski All right, i will make some example a bit later with rich notification.

**Comment by roman-rr** [comment]
@jordanrzymski 
Created advanced demo in case https://output.jsbin.com/neqoxef
You can follow this code, or simple for single notifications:
```js
let settings: CupertinoSettings = {
 inverse: true,
      breaks: {
        top: { enabled: true, bounce: true }
      },
      fitHeight:true,
      topperOverflow: false,
      bottomClose: true,
      buttonClose: false,
      showDraggable: false,
      upperThanTop: true,
      cssClass: 'notification'
}

let notification = new CupertinoPane('ion-notification', settings);
     await.notification.present({animate: true});
```
```html
<ion-notification>
        <ion-text>Notification content</ion-text>
</ion-notification>
```
```css

```
