### ISSUE TITLE
Ionic safe area

### ISSUE THREAD

**Issue by jordanrzymski** [roman-rr/cupertino-pane#146]
![image](https://user-images.githubusercontent.com/66678347/117101020-2f356100-ad6d-11eb-96c8-1e9a8ed63fe3.png)
 This might not be a bug I am using a pane in a hybrid app and on iOS it sits under the screen area and under the swipe bar. On android it works fine

How do I get it to respect the safe area?

Ionic capacitor

**Comment by roman-rr** [comment]
Hello @jordanrzymski thank you for issue. 

Get device bottom offset
```js
get deviceOffset() {
    const sab = getComputedStyle(document.documentElement).getPropertyValue("--ion-safe-area-bottom");
    return parseFloat(sab.replace('px', ''));
}
```

When you set config just add to breakpoints
```js
settings = {
  breaks: {
    top: { enabled: true, height: 250 + this.deviceOffset() },
  }
}
