### ISSUE TITLE
[BUG] unexpected behavior of 'isHidden'

### ISSUE THREAD

**Issue by NLueg** [roman-rr/cupertino-pane#148]
**Describe the bug**
I actually don't understand why `isHidden` logs an error and return `null` if the pane if not presented.
I would just expect to return `false` in case the pane is not present.

The `return null` is actually not the problem for me, but the logs really blow up the console sometimes.

**Expected behavior**
`isHidden` should not log warnings if the pane is not present.

**Comment by roman-rr** [comment]
Hey @NLueg good question!
Pane can be in two base statements: **Presented** and **Destroyed**

| base state | hidden | isHidden |
| Destroyed | null | null | 
| Presented | true | true |
| Presented | false | false |

In other words, isHidden only accessible for presented pane. This way we can move pane out of screen, but persist in DOM.

**Comment by NLueg** [comment]
Hey @roman-rr, thank you for your incredibly fast response!
So I could prevent the warning of being presented by using this condition:

`drawer.isPresented() && drawer.isHidden()`

Am I right? Then I totally understand the behavior.

**Comment by roman-rr** [comment]
@NLueg Right. `isPanePresented` looking for element with class `.cupertino-pane-wrapper.rendered` which is available only for rendered (presented pane). `isHidden` check if pane just out of screen.

**Comment by NLueg** [comment]
Perfect, thank you! 
Awesome plugin by the way! 😊
