### ISSUE TITLE
Unable to close pane when hardware back button is pressed.

### ISSUE THREAD

**Issue by abhishekdana1999** [roman-rr/cupertino-pane#150]
I have ionic moodle application have implemented cupertino panel, its working fine in ionic but is not closing the panel when back button is pressed.

**Comment by abhishekdana1999** [comment]
If you have any idea to get active pane from other component please let me know I am stuck

**Comment by roman-rr** [comment]
Hello @abhishekdana1999 thanks for issue. 

This is how you can manage hardware back button
```js
document.addEventListener('backbutton', function(){
  pane.destroy({animate: true});
}, false);
```

> If you have any idea to get active pane from other component please let me know I am stuck

I don't sure what do you mean, it is depend on your code style. But i highly recommend you create pane instance in hight level to easy access from any scope.

**Comment by abhishekdana1999** [comment]
@roman-rr  thank for instant support, i was finally able to close the pane on back button, but is there any way to assign id to pane and then destroy the pane by id from other components

**Comment by roman-rr** [comment]
@abhishekdana1999 I don't know which framework you are using. Keep you pane in shared high level instance and you will able to do it.

**Comment by abhishekdana1999** [comment]
@roman-rr okay great, thank for your support, I am using ionic 2 will moodle app,
