### ISSUE TITLE
Stop pane from closing 

### ISSUE THREAD

**Issue by abhishekdana1999** [roman-rr/cupertino-pane#151]
I have an ionic app, I want the panel to be static like we can drag the pane to full screen but I don't want it to get close or dismiss when we drag it to bottom.

**Comment by roman-rr** [comment]
@abhishekdana1999 
```
bottomClose: false
```

**Comment by abhishekdana1999** [comment]
`settings: CupertinoSettings = {
    backdrop: false,
    buttonClose: false,

    bottomClose: false,
    breaks: {
      middle: { enabled: true, height: 550 },
    },
  };`


this is the setting I am using but still I am able to close it by dragging

**Comment by roman-rr** [comment]
@abhishekdana1999 i guess you bottom breakpoint is out of screen. 
Set like that: 
```
let settings: CupertinoSettings = {
  ...
  breaks: {
    middle: { enabled: true, height: 550 },
    bottom:  {enabled: true, height: 450 }
  }
}
```

And let me know what happen then.

**Comment by abhishekdana1999** [comment]
@roman-rr Thanks a lot I was stuck on this from morning, finally you saved me, the above solution works, can you please let me know can I change the height of the pane depending on the screen size

**Comment by roman-rr** [comment]
@abhishekdana1999 You can disable bottom breakpoint if you would like. 
```js
bottom:  {enabled: false}
```

For screen size use percents, but i guess you need device-safe area: 
```js
get deviceOffset() {
    const sab = getComputedStyle(document.documentElement).getPropertyValue("--ion-safe-area-bottom");
    return parseFloat(sab.replace('px', ''));
}
```
```js
settings = {
  breaks: {
    top: { enabled: true, height: 250 + this.deviceOffset() },
  }
}
```

**Comment by abhishekdana1999** [comment]
The above solutions works but not in my case, but no worries have fixed it by using the height of device.

I am closing this but please don't delete this as there might be chances that people need it.
