### ISSUE TITLE
present pane on button click

### ISSUE THREAD

**Issue by saurabhgharat95** [roman-rr/cupertino-pane#152]
present pane only on button click and not on page load ?? how can i do it in ionic ..it works first time then after navigating to other page and coming back to page ...class cupertino-pane-wrapped is not added

**Comment by roman-rr** [comment]
@saurabhgharat95 

Set function to button. Angular example: 
```html
<ion-button (click)="presentPane();">Present pane</ion-button>
```

```js
presentPane() {
  this.pane.present({animate: true});
}
```

**Comment by saurabhgharat95** [comment]
This works for one page ..but for another page it shows up without adding cupertino-pane-wrapped class to the pane

**Comment by saurabhgharat95** [comment]
So i found the problem ...the problem was using router.navigate to go back a page  , it apparently kills the pane ..so i used location.back() and now it does not kill the pane
