### ISSUE TITLE
Pane Not Going Above Header

### ISSUE THREAD

**Issue by abhishekdana1999** [roman-rr/cupertino-pane#153]
![image](https://user-images.githubusercontent.com/41101599/124065646-d1fc1a00-da54-11eb-9f06-7027e4d497af.png)

**Comment by roman-rr** [comment]
Hello @abhishekdana1999 

There is choose: 
A. Set z-index for pane hight than header. Move pane on same DOM level as header. 
B. Decrease top breakpoint height
