### ISSUE TITLE
[BUG] zStack not reset some times

### ISSUE THREAD

**Issue by davidecampello** [roman-rr/cupertino-pane#157]
**Describe the bug**
zStack sometimes product this effect when I open and close the pane multiple times.
I'm using Ionic 5 with Angular 12.
The problem is that closing the pane, with both close button and background tap does not reset the zStack.

**To Reproduce**
using this configuration:
```javascript
const element = document.querySelector('.cupertino-pane') as HTMLElement;
    this.cupertinoPane = new CupertinoPane(element, {
      parentElement: 'body',
      breaks: {
        top: {enabled: true, height: 1000, bounce: false},
        middle: {enabled: true, height: 300, bounce: true},
        bottom: {enabled: false, height: 100, bounce: true}
      },
       zStack: {
         pushElements: ['.ion-page'],
         minPushHeight: 0
       },
      bottomClose: true,
      // clickBottomOpen: false,
      // lowerThanBottom: false,
      // draggableOver: true,
      // dragByCursor: false,
      backdrop: true,
      // topperOverflowOffset: 110
      // followerElement: 'ion-fab',
      // onDrag: () => console.log('Drag event'),
      // onTransitionEnd: (e) => console.log('Transition end', e),
      onBackdropTap: () => this.cupertinoPane.destroy(),
      buttonDestroy: true
      // freeMode: true,
      // onBackdropTap: () => hideDrawer()
    });
```

**Screenshots**
<img width="392" alt="Schermata 2021-07-20 alle 16 52 52" src="https://user-images.githubusercontent.com/21193922/126346056-5cf04206-c33a-4703-8955-0ddce9da0b42.png">

**Comment by roman-rr** [comment]
Hello @davidecampello 
Z-Stack is disabled on your config. Backdrop doesn't disappear properly ?

**Comment by davidecampello** [comment]
Hi @roman-rr, I copied after I disabled. Now the code is correct.
What happend is sometime the backdrop does not disappear and the page does not come back to the normal dimension.

**Comment by roman-rr** [comment]
@davidecampello Unfortunately, I couldn't unable to reproduce your issue with configuration you are provided. 
I using simple ionic starter with cupertino-pane. 
To find a reason of bug and fix it, i need some example application sources which will be able to reproduce this bug. 

Please prepare any repository with sources and give me a link. Be sure that you can reproduce this bug on this sources.

**Comment by davidecampello** [comment]
I'll prepare an example in the next days.. Thank you!

**Comment by roman-rr** [comment]
@davidecampello closed due inactivity. But if will be urgent, i will re-open.
