### ISSUE TITLE
Two-sided cupertino pane

### ISSUE THREAD

**Issue by zach-goldberg** [roman-rr/cupertino-pane#158]
Hello,

I’m looking to use this library (with the Ionic Framework) to implement the UI shown in the attached image, but I am having trouble doing so. There are two ways I can envision the page structurally:

- There are three layers. The “base layer” contains the map. The middle layer is a Cupertino pane that comes from the top of the screen. This middle layer pane contains the tabs menu as well as a top layer nested Cupertino pane that comes from the bottom and contains the main content. 
- There are two layers. The “base layer” contains both the map and the tabs menu. The top layer is the Cupertino pane that contains the main content.

Again, I’m lost on how to implement this UI. I realize it is not the most straightforward way of using Cupertino panes. If someone could point me in the right direction or tell me if it is possible in the first place using this library I would greatly appreciate it.

Thanks!

![Screen Shot 2019-01-01 at 2 46 31 ](https://user-images.githubusercontent.com/47124484/127146621-67f00dc4-dfcd-4a0e-91d9-deb72b567894.png)

**Comment by roman-rr** [comment]
@zach-goldberg 
Do you using ionic framework ? 

Tabs can be realized with `ion-tabs`. 
Map can be realized inside of `ion-content`.

I need to understand pane behavior with dynamics. 
This is one pane should be include title "Main Page" and the same pane in one time include steps information right ? 
Small rectangle element (draggable) has on bottom and top of pane. Do you need to have ability move pane to the top and bottom screen in one time ? 
Do you need to close pane if drag to bottom direction ?

**Comment by zach-goldberg** [comment]
@roman-rr 
Yes I am using Ionic.

Basically the behavior I'm looking for is as follows. You can't slide the middle pane further down than it is in the above picture (or if you do, it will bounce back up to the position in the image above). You can, however, slide the pane up. If you slide the pane up, first it will cover the tabs menu, and if you keep sliding it up beyond that, part of the main content will get hidden above the viewport.

Ideally, there would be a breakpoint where the pane exactly covers the tabs menu. But if you slide further up than that, the pane goes into "free mode" where you can slide it up to any position you want until the bottom of the pane reaches the top of the screen.

The pane doesn't need to close. It will always be there.

I tried my best to explain that clearly, but if you have any more clarification questions, please ask. Thanks so much for your time.

**Comment by roman-rr** [comment]
@zach-goldberg 
Please check [example ](https://output.jsbin.com/jesoxot)

What else do you need in requirements ?

**Comment by roman-rr** [comment]
Closed due inactivity.
