### ISSUE TITLE
[BUG] Pane opens itself after unlocking mobile device

### ISSUE THREAD

**Issue by tsungweihsu** [roman-rr/cupertino-pane#159]
Hello Roman,

we found an interesting behavior in Android devices, please have a look 🔎

**Describe the bug**
When the pane is hidden by the method `hide()`, it opens itself after the device is being unlocked.

**To Reproduce**
1. Create a pane
2. Hide the pane using `hide()`
3. Lock the device while the app is in foreground
4. Unlock the device
5. The app reappears and the pane jumps up

**Expected behavior**
The pane should stay hidden 🙈

**Screenshots**
<img src="https://user-images.githubusercontent.com/63068563/127357746-0d192e1a-1fe3-4063-8723-737b0f75e320.gif" width="250px"/>

**Smartphone:**
 - Framework: Ionic 5
 - Device: Pixel 4 (emulator), Pixel 4a (real device)
 - Version 30

**Additional context**
This issue is not present in iOS 👌

**Comment by roman-rr** [comment]
@tsungweihsu Please provide a video from `Device: Pixel 4 (emulator)`

**Comment by tsungweihsu** [comment]
@roman-rr The GIF attached to the post above is already the screen from the emulator (Pixel 4), you can see the mouse moving within. But I attach a new video to this one. The app contains nothing but the pane (1.2.7).

https://user-images.githubusercontent.com/63068563/127460688-749fc7bb-6607-4973-a369-eba0e4aa2eb4.mp4

**Comment by roman-rr** [comment]
@tsungweihsu 
What software do you use for emulator ? This is not look like default android studio avd. 
I've tested on device Samsung A51, bug doesn't appears. 

I'm pretty sure that this is somethings with unlock transition. 
After drag to the top gesture, applications viewport do transition or height changes. 
From bottom to the top animation on your videos. 
On Samsung A51 has other unlock animation for apps. Or maybe you change it somewhere ?

**Comment by tsungweihsu** [comment]
@roman-rr 
I am using the default emulator from Android Studio. I've tested further with **Pixel 3a (emulator)** in different scenarios, please find them in the following videos:
1. No unlock passwords, swipe up to unlock.

https://user-images.githubusercontent.com/63068563/127829130-c506fb20-a96c-4e36-bfee-6b4ff7e3943f.mp4

2. Unlock with fingerprint but wake up the phone first

https://user-images.githubusercontent.com/63068563/127829429-614b635f-6dd4-402f-9a65-40e43f4e5965.mp4

3. Unlock with fingerprint directly while the screen is off (**the most common scenario in real life use**)

https://user-images.githubusercontent.com/63068563/127829439-9271ab6a-e813-44b6-bb50-d72588c276e4.mp4

4. Unlock with manually typing password (the pane <ins>**does not**</ins> jump up)

https://user-images.githubusercontent.com/63068563/127831775-88ef831f-8b99-44cb-b52c-8b55b0e510a5.mp4



Additional observed behavior:
* The pane will no longer show up by itself when it is destroyed by `destroy()`.
* The temporary solution is to destroy the pane with animation set `true` to mimic `hide()`, and `present()` it later when in use.

**Comment by roman-rr** [comment]
@tsungweihsu Thank you for such good details provided. Should be fixed on master branch. 
The reason of issue is because android trigger `window.resize` for unlock device events.

**Comment by Tvde1** [comment]
👍🏻 also fixes the pane opening whenever the browser window is resized :) great work
