### ISSUE TITLE
Can you publish some example code for each type of panes?

### ISSUE THREAD

**Issue by GosuMania** [roman-rr/cupertino-pane#161]
There are several examples of using Cupertino Pane, but I don't know how to develop some of them.

For example I would like to play **Bulletin live** or **Apple Clips live**.

How can I do it?

**Comment by roman-rr** [comment]
Hello @GosuMania 
This is JavaScript example for [Bulletin](https://jsbin.com/maqigod) and [Apple Clips](https://jsbin.com/luqaxud)

**Comment by marcelkipp** [comment]
@roman-rr  Unfortunately all links with examples are down at the moment. Can the examples be viewed somewhere else?

**Comment by roman-rr** [comment]
@marcelkipp Just tried and all links working well https://panejs.com/demonstration.html

**Comment by marcelkipp** [comment]
@roman-rr Thanks for the reply! All fine, somehow the page is not reachable from my network. Outside works fine
