### ISSUE TITLE
Unable to stop pane from scrolling to top or bottom 

### ISSUE THREAD

**Issue by abhishekdana1999** [roman-rr/cupertino-pane#162]
Have implemented cupertino pane in my app, let say have some content in Cupertino pane having list when I scroll the list, the pane also starts scrolling, have attached screenshot for some ref and video 

![X - 1](https://user-images.githubusercontent.com/41101599/128969999-f94c2902-70de-4d6b-ba76-145e2c630702.png)

When I try to scroll the list to top the pane starts moving up and when I scroll list to bottom the pane start to move down, I need the pane only to move when the draggable line is used to drag not the all pane.

**Comment by roman-rr** [comment]
Hello @abhishekdana1999 
I guess this behavior you need https://output.jsbin.com/piwecad

**Comment by abhishekdana1999** [comment]
@roman-rr thank the answer is really appreciated thanks for instant support was stuck on this for more than 3 days.
