### ISSUE TITLE
[FEAT] allow destroying the sheet if it's out of the DOM

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#163]
**What are you trying to add to Cupertino-Pane?**
I want to be able to destroy a sheet if it's out of the DOM

*Describe your feature request **detailed***
I have situations where a sheet is not in the DOM because I've moved one of its ancestors out of the DOM (to restore it later). However I may need to `.destroy()` the sheet before I restore the ancestor. In this scenario, [this check](https://github.com/roman-rr/cupertino-pane/blob/7177c646d0c8ac02d4b0c39c2b72495ab6474289/src/cupertino-pane.ts#L744) fails and prevents the sheet from being destroyed. I want to be able to `.destroy()` the sheet successfully even when it's attached to a node that is not currently in the DOM. To put it simply, imagine that the sheet is a child of a node called `.sheet-parent`. Sometimes I remove `.sheet-parent` from the DOM (but it's saved in a variable so I can restore it later), which causes the sheet to also be removed from the DOM. If I call `sheet.destroy()` when `.sheet-parent` is out of the DOM, then the check fails and the sheet is not destroyed. I want to be able to destroy the sheet regardless.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
Hello @CodeWithOz 
Please show how do you copy DOM element before remove it from DOM. If you are just move it to other place, it is one case, but if you make object copy, then you remove DOM element with .remove(), you might lose your angular callbacks and event on copied elements. 

Show me simple example, i will try it.

**Comment by CodeWithOz** [comment]
Hey @roman-rr so what I do is something like this (very simplified):
```js
document.body.insertAdjacentHTML('beforeend', '<div class="sheet-container"><div class="sheet-node">Contents</div></div>');
const sheetContainer = document.querySelector('.sheet-container');
const sheet = new CupertinoPane('.sheet-node', { ... });
sheet.present({ animate: true });

// remove the sheet container 3s later
setTimeout(() => {
  // now remove the sheet container from the DOM
  sheetContainer.parentNode.removeChild(sheetContainer);
}, 3000);

// try to destroy the sheet 5s later
setTimeout(() => {
  // .sheet-node is not in the DOM because its parent has been removed
  sheet.destroy(); // outputs "Cupertino Pane: Present pane before call destroy()"
}, 5000);

// restore .sheet-container to the DOM 7s later because I want to use it for something else
setTimeout(() => {
  document.body.append(sheetContainer);
  // the sheet is still present because .sheet-node is still a child of .sheet-container even though I tried to remove it
}, 7000);
```

Essentially, [this check](https://github.com/roman-rr/cupertino-pane/blob/7177c646d0c8ac02d4b0c39c2b72495ab6474289/src/cupertino-pane.ts#L434-L435) fails because it uses `document.querySelectorAll(...)`. In my example, `.sheet-node` is not in the DOM so `document.querySelectorAll` will not find it.

**Comment by roman-rr** [comment]
Hello @CodeWithOz 
Sorry for delay, should works now!
