### ISSUE TITLE
[BUG] error: 'Support' has already been declared

### ISSUE THREAD

**Issue by baneJack** [roman-rr/cupertino-pane#165]
**Describe the bug**
Hi,
When I open the browser console, I am facing this error:
Uncaught SyntaxError: Identifier 'Support' has already been declared (cupertino-pane.min.js)

**To Reproduce**
Launch your project and open console to see error

**Desktop:**
Browser [chrome]

**Comment by roman-rr** [comment]
@baneJack Thank you for issue! 
Somewhere in your project has additional `Support` module and there is name conflict happen. 

Firstly, to fix issue, i need to know which library exactly in your project has same name `Support`. 
Please share for me exact lib, or all libs that you are using.

**Comment by baneJack** [comment]
Hi Roman,

Thank you for your swift response.
You are right
Thank you!
