### ISSUE TITLE
The old instance of bread remains in memory[BUG] 

### ISSUE THREAD

**Issue by GosuMania** [roman-rr/cupertino-pane#166]
The problem occurs when you try to open the same cupertino-pane with different data.

If I open a cupertino-pane with the data of a product A I close it and reopen it with the data of a product B, if I continue to close it and reopen it I will see the cupertino-pane alternately with the data of product A and B. ..

Example:
If I enter a page with the data of a product A and open the cupertino-pane and then I exit ... afterwards I enter the same page again but with the data of a new product B and open the cupertino-pane, this the first time it opens with the data of product B, but the second time it opens with the data of product A and if I continue to open and close the cupertino-pane I will see once the data of product A and then those of product B ...

If I also exit the page and access it with the data of a new product C then the cycle is repeated by seeing once the cupertino-pane with the data of product C, then B and then A and so on indefinitely ...

This is a video that demonstrates clarification of the bug just described:
https://drive.google.com/file/d/1n7xVXBTffpcv5_MvxZAJBb3R0GVzlo_d/view?usp=sharing

### My Code

TS:
```
  async openPanePreviewProduct() {
    console.log(this.deal.productName);
    this.checkOpenPanePreviewProduct = true;
    let settings: CupertinoSettings = {
      parentElement: 'body',
      fitHeight: true,
      maxFitHeight: this.th.heightPlatform - 70,
      topperOverflow: false,
      bottomClose: true,
      buttonDestroy: false,
      backdrop: true,
      onWillDismiss: () => {
        //this.openPaneProductList();
        this.checkClosePanePreviewProduct = false;
      }
    };
    this.panePreviewProductDetail = new CupertinoPane('.panePreviewProductDetail', settings);
    
    await this.panePreviewProductDetail.present({ animate: true }).then(() => this.checkOpenPanePreviewProduct = false );
  }

  closePanePreviewProduct(b) {
    this.checkClosePanePreviewProduct = true;
    if (b) {
      //this.panePreviewProductDetail.destroy({ animate: true });
      this.addToFavoriteList();
      this.panePreviewProductDetail.destroy({ animate: true });
    } else {
      this.panePreviewProductDetail.destroy({ animate: true });
    }
  }

```

HTML:
```
  <div class="panePreviewProductDetail">
    <ion-grid style="margin-left: 3%; margin-right: 3%;  margin-bottom: 6%;">
      <ion-row>
        <h1 style="text-align: center;">
          Vuoi aggiungere questo prodotto alla tua lista?
        </h1>
      </ion-row>
      <ion-row *ngIf="deal !== null" style="padding-left: 2%; width: 98%;">
        <ion-col size="5" class="immagineProdottoContainer">
          <img class="immagineProdotto" [src]="deal.imageLink2" [style.height]="maxImageHeight" style="padding: 5px;" />
        </ion-col>
        <ion-col size="7" style="margin-top: 3%;">
          <div>
            <ion-label *ngIf="deal.productName.length>90">{{deal.productName | slice:0:90}}...
            </ion-label>
          </div>
          <div>
            <ion-label *ngIf="deal.productName.length<=90">{{deal.productName | slice:0:90}}
            </ion-label>
          </div>
          <div>
            <ion-label color="newgosu">
              <h1><strong>{{deal.finalPrice}} </strong></h1>
            </ion-label>
          </div>
        </ion-col>
      </ion-row>
      <ion-row style="margin-right: 3%; margin-left: 3%;">
        <ion-col>
          <ion-button class="noShadow cancel-button" expand="block" (click)="closePanePreviewProduct(false)"
            [disabled]="checkClosePanePreviewProduct">
            Annulla
          </ion-button>
        </ion-col>
        <ion-col>
          <ion-button class="noShadow" color="newmania" expand="block" (click)="closePanePreviewProduct(true)"
            [disabled]="checkClosePanePreviewProduct">
            Aggiungi
          </ion-button>
        </ion-col>
      </ion-row>
    </ion-grid>
  </div>
```

**Comment by GosuMania** [comment]
Any news??? You can't help me?

**Comment by roman-rr** [comment]
@GosuMania Sorry for delay. In the next few days here will be a solution.

**Comment by GosuMania** [comment]
> ```js
> '#' + productID + 
> ```

i fix with id="{{deal.id}}"

I was already using dealActive, but unfortunately it doesn't work. Even if I replace each time the active offer the previous ones remain in the DOM, in my opinion you need to add a function to clean up the DOM manually when you leave a page

Thanks a lot anyway :)

**Comment by roman-rr** [comment]
@GosuMania Thank you, i will add something like `.destroy({clearDOM: true})` if more requests will appears.
