### ISSUE TITLE
How to get pane height?

### ISSUE THREAD

**Issue by Sovai** [roman-rr/cupertino-pane#167]
I want to get the opened pane height to add bottom padding to the container when the pane opens. I tried this but it seems to get the incorrect height

```
toggleBodyPadding() {
        const container = document.querySelector('.container')
        const height = _.get(document.querySelector('.pane'), 'clientHeight', 0)
        container.style.paddingBottom = height + 'px'
    } 
```

**Comment by roman-rr** [comment]
Hello @Sovai 
Thank you for issue!

Have you already try to set `bottomOffset` ? Probably that what you looking for. 

```js
let settings = {
  ...,
  bottomOffset: 100
}
```

**Comment by Sovai** [comment]
Hi, thanks for your solution. but for `fitHeight: true` how do I set `bottomOffset `since I don't know the calculated height?

**Comment by roman-rr** [comment]
@Sovai
`bottomOffset` will add margin, not padding. 
So, if you need a height, you must get it after render. Try to use `async/await`;

```js
await pane.present({animated: true});

// and then you function for get height
toggleBodyPadding();
```

**Comment by roman-rr** [comment]
@Sovai additionally you can try `pane.getPaneHeight()` method, which is public, but not in docs, because experimental.

**Comment by Sovai** [comment]
> @Sovai `bottomOffset` will add margin, not padding. So, if you need a height, you must get it after render. Try to use `async/await`;
> 
> ```js
> pane.present({animate: true});
> await myPane.calcFitHeight();
> 
> // and then you function for get height
> toggleBodyPadding();
> ```
> 
> Additionally, add timeouts to your `toggleBodyPadding()` to be sure, that height is correct, but need a time to render.
> 
> ```js
> setTimeout(() =>  {
>   toggleBodyPadding();
> }, 300);
> ```
> 
> But i recommend for you to set paddingBottom with css. I don't know the cases where padding bottom should be as big as pane height.


Hi @roman-rr, thanks for support. I now can get the height but I face another issue. when call `pane.present` then call `pane.calcFitHeight()` it cause lag animation like this
![Screen Recording 2021-11-21 at 4 30 37 PM](https://user-images.githubusercontent.com/8064796/142756880-822c8a33-6404-40f1-977f-533e5e8b7590.gif)
 
is there a way I can hide the the pane when calling `pane.present` then show when recalculated?

**Comment by Sovai** [comment]
Hi, I solved the issue by removing the promise function. 

![image](https://user-images.githubusercontent.com/8064796/142769207-a9e3b29e-3470-4897-b1e0-79dc12e83851.png)

**Comment by roman-rr** [comment]
@Sovai Thank you, yes it is good idea. We no need to wait height recalculation to add body padding. 

Only, you might use this syntax with accordance to [AirBNB guidelines](https://github.com/airbnb/javascript): 
```js
async showCupertino() {
  await cupertinoDrawer.present({animate: true});
  if (this.fitHeight) {
    cupertinoDrawer.calcFitHeight();
  }
  this.toggleBodyPadding();
}
```
