### ISSUE TITLE
[BUG] unable to scroll on overflow content

### ISSUE THREAD

**Issue by schervo** [roman-rr/cupertino-pane#168]
**Describe the bug**
If you open the drawer quickly no an iOS device, sometimes the content is not scrollable.

**To Reproduce**
(See the attached video)
1. Go to the [Overflow Top Live example](https://output.jsbin.com/baguroy) using an iOS device.
2. Open the drawer quickly
3. See how sometimes the content is not scrollable

**Expected behavior**
The content should be scrollable.

**Screenshots**
https://user-images.githubusercontent.com/21371840/143275253-b13a305c-f311-4fd4-a724-d2e5cdde69f8.mov

**Desktop (please complete the following information):**
- It works fine on desktop

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.1
 - Browser: Safari, Chrome
 - Version: 15.1, 95

**Additional context**
- It only happens when you scroll up quickly.

**Comment by roman-rr** [comment]
@schervo thanks for your attentiveness. This issue should be already fixed on master branch. And jsbin demo's will be automatically fixed on release 1.2.8 which is very soon (1-2 weeks).
