### ISSUE TITLE
[BUG] inside content not clickable

### ISSUE THREAD

**Issue by BaptisteMonet** [roman-rr/cupertino-pane#169]
**Describe the bug**
Children component are not clickable
[original issue](https://github.com/roman-rr/cupertino-pane/issues/138)

**To Reproduce**
1. Go to [sandbox from other issues](https://codesandbox.io/s/cupertino-example-forked-w5xw5)
2. add onClick to children <div style={{ height: 300 }} onClick={()=>console.log('panel content')}>{"Panel Content"}<'/'div> in app.tsx
4. no effect appears

**Expected behavior**
I want to have button and other stuff inside pane clickable

I'm not sure  if this a bug or a misunderstanding ?

**Comment by roman-rr** [comment]
Hello @BaptisteMonet, thank you for issue.
Set `parentElement` to `parentElement: '.App'` insdead of `body` will do a trick for you. 
I believe that react doesn't propagate events outside of main application container.

**Comment by roman-rr** [comment]
@BaptisteMonet additionally, draggable element sent back.
