### ISSUE TITLE
[BUG] Missed keyboard show events

### ISSUE THREAD

**Issue by bazuka5801** [roman-rr/cupertino-pane#170]
**Describe the bug**

**To Reproduce**
1. In did-present, focus first input
4. See keyboard showing not handled by cupertino-pane and pane behind keyboard

**Expected behavior**
1. React to changes of keyboard state (in attachAllEvents store and use the last keyboard state, and the events themselves should always listen to keyboard events, because we can show the cupertino-pane when the keyboard is open.

Yes I know, you can wait for 200ms and then open the keyboard, but it's a huge blow to the UX, because it takes a very long time to open the keyboard.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15
 - Browser WKWebView
 - Version:  iOS 15

**Comment by roman-rr** [comment]
Hello @bazuka5801 
Currently, events will push pane up only if input is a child of this pane. 
It is not a bug, but created by design.

But we can extend option `handleKeyboard` with few modes: full, child, none.

is that what you need ?

**Comment by bazuka5801** [comment]
@roman-rr  Thanks for the quick reply 🚀 and the great library! 
That's the thing, my input is inside the cupertino-pane
Please take a look at these lines:
https://github.com/roman-rr/cupertino-pane/blob/master/src/cupertino-pane.ts#L352-L357

We wait for 150ms, then subscribe to all events including keyboard events

But input autofocus is called earlier (I call it manually `input.focus()` in the **did-present** event). To open the keyboard faster, I'd like to have the keyboard will showing simultaneously, rather than sequentially as it does now.
Is it possible to do this? Or maybe I'm doing something wrong and it's already implemented?

**Comment by bazuka5801** [comment]
I use it as a crutch to resolve this bug
```js
// Vue 2
async focusFirstInput(e) {
  if (this.$refs.firstInput) {
    let onInputFocus = (e) => {
      this.$refs.cupertino.events.onKeyboardShowCb(e)
      window.removeEventListener("keyboardWillShow", onInputFocus)
    }
    window.addEventListener("keyboardWillShow", onInputFocus)
    this.$refs.firstInput.focusInput()
  }
}
```

**Comment by roman-rr** [comment]
@bazuka5801 ok i got it. 
Please check `onTransitionEnd` instead of `onDidPresent`,  maybe event will handle keyboard with first input focus here. 
If not, i will looking for solution.

**Comment by bazuka5801** [comment]
@roman-rr The same problem, because `onTransitionEnd` is called a little later, but before `attachAllEvents` is reached
https://github.com/roman-rr/cupertino-pane/blob/master/src/transitions.ts#L68-L74

**Comment by bazuka5801** [comment]
https://github.com/roman-rr/cupertino-pane/blob/fe27ab17fc49c5a293ec1aad72b81e22308dbe1d/src/events.ts#L51-L54

I believe that this problem can be fixed by subscribing to the keyboard show event earlier, for example at the beginning of the present call and before await timeout
https://github.com/roman-rr/cupertino-pane/blob/master/src/cupertino-pane.ts#L352

**Comment by roman-rr** [comment]
@bazuka5801 yes, attach events probably must going before. Thank you, i will review this logic in near few days.

**Comment by roman-rr** [comment]
@bazuka5801 Sorry for delay, finally done!  ✅
