### ISSUE TITLE
[BUG] pane can be overscrolled

### ISSUE THREAD

**Issue by tsungweihsu** [roman-rr/cupertino-pane#171]
**Describe the bug**
When `top` is defined, the pane can be overscrolled away from the view port. Please find the video attached. 

**To Reproduce**
1. Create a pane with `top` defined
2. Drag the pane to the top and overscroll it
3. The pane can be scrolled away from the view port

**Expected behavior**
The pane should be fixed when overscrolled.

**Screenshots**

https://user-images.githubusercontent.com/63068563/149132002-23e33034-167d-42c0-ac76-aa7ae8c616ad.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4 Emulator, Pixel 4a
 - Version 1.2.81 & 1.2.8

**Additional context**
This only happens with Android not iOS.

**Comment by roman-rr** [comment]
@tsungweihsu big thanks for report. Probably a case regards to `1.2.8`. i will check it

**Comment by szymek** [comment]
+1

**Comment by bujaczes** [comment]
+1

**Comment by roman-rr** [comment]
@tsungweihsu @bujaczes @szymek please share for exact settings configuration.

**Comment by tsungweihsu** [comment]
```typescript
settings: CupertinoSettings = {
    parentElement: 'body',
    buttonClose: false,
    breaks: {
      top: {enabled: true, height: window.innerHeight },
      middle: {enabled: true, height: window.innerHeight * 0.5},
      bottom: {enabled: true, height: 100}
    }
  };
```
I did a deeper testing to see what really triggers this behavior and found that when `top` is defined to be the **_same height_** as the view port, the pane can be swiped away.

**Comment by roman-rr** [comment]
Just pushed `1.2.82` which should fix the bug!
