### ISSUE TITLE
[BUG] interruption with scroll timeline

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#172]
**Describe the bug**
Using [`ScrollTimeline`](https://github.com/flackr/scroll-timeline/) for animations within the sheet got broken between 1.2.6 and 1.2.7. The animated elements seem to think that the scrollable element is at the end of the scroll area when the sheet is initialized. I was using 1.2.6 and recently upgraded to 1.2.8 and saw this problem, then downgraded to 1.2.7 and still saw the problem. In my example I'm using the scroll timeline to indicate the "active" tab as the user swipes left/right. However the sheet is initialized with the tab on the right i.e. end of the scroll area with the active color instead of the one on the left.

**To Reproduce**
I created a sample reproduction of my cordova app, you can view the code [here](https://github.com/CodeWithOz/cordova-bad-web-workers/tree/feature-scroll-snap) and test it in [this build](https://github.com/CodeWithOz/cordova-bad-web-workers/actions/runs/1800354256)

**Expected behavior**
The "comment" tab should be highlighted with the black background and white text when the sheet is opened.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Tecno Android phone and Samsung Galaxy Ultra Note 20
 - OS: Android 8.1 - Android 12
 - Browser Chrome Webview
 - Version 97

**Additional context**

**Comment by roman-rr** [comment]
Hello @CodeWithOz 
Thank you for issue. I reviewed your code and here some conclusions: 

When you initialize ScrollTimeline with `new ScrollTimeline(...)`, your DOM isn't visible on viewport and active tab is not correctly calculated. You must initialize ScrollTimeline composed and ready DOM. 

Simple solution is to present pane first, and using `async/await` function to be sure that pane presented. And after this ScrollTimeline can be initialized without issues.  

```js
function initPane(...) {
  requestAnimationFrame(async() => { // Here async
    ...
    if (shouldPresent) {
      await myPane.present({ animate: true }); // Here you await for presentation
    }
    
    // And after presentation you could initialize ScrollTimeline and other ScrollTimeline works
   const scrollSnapContainer = document.querySelector(`.content`);
   const sectionScrollTimeline = new ScrollTimeline({
     scrollSource: scrollSnapContainer,
     orientation: 'inline',
     fill: 'both',
   });
   ...
  });
}
```

**Comment by CodeWithOz** [comment]
@roman-rr thanks for that, it worked. :+1: :tada:
