### ISSUE TITLE
[FEAT] add more buttons above the draggable area, similar to the close button

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#173]
**What are you trying to add to Cupertino-Pane?**

*Describe your feature request **detailed***
I want to add more buttons that are positioned in the draggable area just like the close icon, but right now the draggable area overlays them and prevents clicks from registering.

**Is there an alternative at the latest version?**
I could use the `didPresent` callback to manually insert the button outside the `.content`, but I want a cleaner way to do this.

[x] Yes (descripe the alternative)
[ ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by CodeWithOz** [comment]
I've realized I was already doing this using `z-index: 13` because the `.draggable` has `z-index: 12`. Still not ideal because `z-index: 12` may change at any point, which may break what I'm doing. So I'd still prefer if there was a cleaner way to do this as part of the features of the sheet, so I'll leave this open.

**Comment by roman-rr** [comment]
Hello @CodeWithOz Thanks for issue!
Issue is related to #169 which is already fixed on 1.2.8+ and master branch with [commit](https://github.com/roman-rr/cupertino-pane/commit/6196a4e03edf76dd05bfe66eca9e12541510f304)
