### ISSUE TITLE
[BUG] Keyboard willShow handler on Android browser with 1.2.8+

### ISSUE THREAD

**Issue by SolidZORO** [roman-rr/cupertino-pane#175]
**Describe the bug**

### cupertino-pane@1.2.8 (Android has BUG, iOS is OK)
demo: https://j107o.csb.app/
source: https://codesandbox.io/s/cupertino-pane-1-2-8-j107o?file=/index.html
![Screenshot_2022-02-09-00-44-17-234_com android browser](https://user-images.githubusercontent.com/661587/153035419-67ae24ee-63c8-44ae-9330-94f5484b4ded.jpg)

### cupertino-pane@1.2.7 (is OK)
demo: https://tk43o.csb.app/
source: https://codesandbox.io/s/cupertino-pane-1-2-7-tk43o?file=/index.html
![Screenshot_2022-02-09-00-43-15-430_com android browser](https://user-images.githubusercontent.com/661587/153035435-b1ea5227-25a4-4735-90df-6b759158ec72.jpg)

**Smartphone (please complete the following information):**
 - OS: Android 12
 - Browser Chrome

**Additional context**

**Comment by roman-rr** [comment]
@SolidZORO Thank you for issue. 

As already described in [README](https://github.com/roman-rr/cupertino-pane#browserwebview)
Pane do not handle keyboard events for Browser by default. 
In **1.2.7**, by mistake you events was handled by `resize` event. 

Beginning from **1.2.8**, resize and keyboard events was finally separated. 
WIth this action, we can reduce other errors, e.g. android device sometimes trigger resize without keyboard. 

### To help you to solve keyboard issue, i can suggest in two ways:

1. Imitate `resize` function the same using in **1.2.7**
```js
window.addEventListener("resize", function() {
  drawer.updateScreenHeights();
  drawer.setBreakpoints(
    JSON.parse(drawer.breakpoints.lockedBreakpoints)
  );
});
```

2. More proper way (in my opinion) is to manually set functions for input blur/focus events.
```html
<input type="text" onfocus="keyboardOpen()" onblur="keyboardClose()" />
```

```js
function keyboardOpen() {
  drawer.moveToBreak('top');
}

function keyboardClose() {
  drawer.moveToBreak('middle');
}
```

**Comment by SolidZORO** [comment]
@roman-rr  Thank you very much for the code example.! It works fine, but in the real world, there may be such a need that it doesn't work. And this works fine in 1.2.7.

Any suggestions?

cupertino-pane@1.2.82-input-margin-top-500
demo: https://0i3np.csb.app/
source: https://codesandbox.io/s/cupertino-pane-1-2-8-input-margin-top-500-0i3np?file=/index.html



https://user-images.githubusercontent.com/661587/153335966-c976946a-6454-4136-8f84-cf94abf55aa3.mp4

**Comment by roman-rr** [comment]
@SolidZORO Thank you for assistance. Keyboard events was remastered, please check latest commit on master branch with all platforms that you are using, and let me know then, how it works now!

**Comment by SolidZORO** [comment]
@roman-rr It looks like it works fine. but the behavior is a bit different from 1.2.7 😂 , It feels like you can put this update into the next version release.


cupertino-pane@1.2.7-input-margin-top-500--wip
https://idczvl.csb.app/
https://codesandbox.io/s/cupertino-pane-1-2-7-input-margin-top-500--wip-idczvl


cupertino-pane@1.2.7-input-margin-top-500--wip
https://heuhc2.csb.app/
https://codesandbox.io/s/cupertino-pane-1-2-8-input-margin-top-500--wip-heuhc2

**Comment by roman-rr** [comment]
@SolidZORO Pushed additions which should make better events with cordova app.
