### ISSUE TITLE
[BUG] onKeyboardShowCb called multiple times with accessory views

### ISSUE THREAD

**Issue by rgoldiez** [roman-rr/cupertino-pane#176]
**Describe the bug**
On real devices with a virtual keyboard, [this line](https://github.com/roman-rr/cupertino-pane/blob/d752485576a7e2976a5eff40418cddf4fa3c58e5/src/events.ts#L488) throws an uncaught exception if an `input` is focused and then changed with an accessory view.

**To Reproduce**
1. Create a bottom pane with a text input; make sure that input is going to show the accessory view `Keyboard.setAccessoryBarVisible({ isVisible: visible });` if using capacitor with the Keyboard plugin.
2. Launch the bottom pane and focus on the input (make sure the virtual keyboard is visible)
3. Type in the input to cause another `keyboardWillShow` events to fire

**Expected behavior**
This component is using the `keyboardWillShow` event to capture the proper breakpoint before the keyboard is shown and then holding on to that breakpoint in `prevBreakpoint`.  However an error is thrown if this is handler is called a second time because the line referenced above does not find a breakpoint (keyboard is already showing and so the pane has been translated already to a new position).

**Screenshots**
Error: undefined is not an object (evaluating 'Object.entries(this.breakpoints.breaks).find((function(t){return t[1]===e.instance.getPanelTransformY()}))[0]')

**Smartphone:**
 - Device: iPhones, iPads, and Android devices
 - OS: 15.2 / Android 11 but possibly others
 - Browser: Capacitor / Cordova apps

**Additional context**
This stackoverflow issue / "solution" describes how the `keyboardWillShow` can be called multiple times without a `keyboardWillHide`.  One solution could be to track an instance variable so that when the keyboard initially shows the event callback is execute once and not again until the instance variable is cleared by reseting it in the `keyboardWillHide` callback.

**Comment by roman-rr** [comment]
@rgoldiez Thank you for report!
Should be fixed in latest commit, include up/down events with accessory bar.
Please, check it!

**Comment by rgoldiez** [comment]
@roman-rr - your changes look good and the error is gone.  Thank you!
