### ISSUE TITLE
[BUG] Fast swipes still not dismissing the sheet fully sometimes

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#178]
**Describe the bug**
Fast swipe to dismiss from the top breakpoint doesn't always work on some devices, even with `fastSwipeClose: true` and `fastSwipeSensivity: 1`. Even for a large (>50px) and fast vertical swipe, the sheet only moves from top to mid breakpoint.

**To Reproduce**
Unfortunately this problem is only visible on a specific device so far, the Samsung Galaxy Note 20 Ultra, so reproducing it elsewhere has been difficult.

**Expected behavior**
Large fast swipes when at the top breakpoint should dismiss the sheet entirely instead of moving to the mid breakpoint.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Chrome webview
 - Version: 101

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra
 - OS: Android 12
 - Browser: Chrome Webview
 - Version: 101

**Additional context**
I've realized that when the problem occurs the touch positions in `touchmove` don't always get added to the `steps` array (it probably hits one of the `if` statements that `return` early), so by the time `touchend` fires, the calculation of `diff` is `NaN` so the value of `fastSwipeNext` is `false` when it should be `true`.

How about using the touch position of `touchend` as a fallback to calculate the correct `diff` in these situations? I'm referring to something like this (my own code changes for testing):
![cupertino-pane-possible-fix](https://user-images.githubusercontent.com/28525986/159895411-a23e805c-24f5-4733-a423-4c9148588b7d.png)

When I tried this it didn't work very well because it made the swipes over-sensitive and the sheet was dismissed more often than necessary, but I think the principle can lead to the correct solution. What do you think?

**Comment by roman-rr** [comment]
Hello @CodeWithOz thank you for issue!
Do you catch this behavior on the latest version right from master branch ? Or some specific release ?

**Comment by CodeWithOz** [comment]
Yes it happens on the latest version of the master branch too. I thought your recent changes would fix it but the problem is still happening :(

**Comment by roman-rr** [comment]
@CodeWithOz To fix such complicated behavior, we should exactly know how to reproduce.
Please try to find this behavior on any of android emulator. Therefore, everybody can review this, not only specific device holders. 

Right now i guess that android touch events may skip `touchmove` and only execute `touchstart`, `touchend`.  But here we can only guess until reproduction.

**Comment by roman-rr** [comment]
Closed until reproduction.
