### ISSUE TITLE
[FEAT] invoke didDismiss and willDismiss callbacks when destroying a sheet that wasn't presented

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#182]
**What are you trying to add to Cupertino-Pane?**
I want to be able to invoke the `willDismiss` and `didDismiss` callbacks when `destroy()`ing a sheet that was never `present()`ed. 

*Describe your feature request **detailed***
Add an option that can be used to ensure that the callbacks are still invoked, something like `invokeDismissCallbacks: boolean`. And then when `rendered` is checked [here](https://github.com/roman-rr/cupertino-pane/blob/05a3c1ebd0daa7293aa4c7c14b98fa87da432fc4/src/cupertino-pane.ts#L574), invoke the callbacks if `invokeDismissCallbacks` is true, then `return null`.

**Is there an alternative at the latest version?**
I used my own code like this:
```js
    if (sheet.rendered) {
        sheet.destroy(config);
    } else {
        // without the sheet rendered the callbacks are not invoked by using
        // the .destroy() method
        // so we have to invoke them manually
        if (typeof sheet.settings.onWillDismiss === 'function') {
            sheet.settings.onWillDismiss();
        }
        if (typeof sheet.settings.onDidDismiss === 'function') {
            // the default animation duration of the lib is 300ms, so we
            // separate the dismiss callbacks accordingly
            setTimeout(() => {
                sheet.settings.onDidDismiss();
            }, 300);
        }
    }
```

[x] Yes (descripe the alternative)
[ ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
@CodeWithOz Thank you. A little bit tricky to invoke this callbacks without actual destroying. I believe that some logic not clear on your side if you need to execute destroy callbacks/functions for non-presented pane. 

If someone else will also need this feature, i will add callbacks for even not-presented instance.

**Comment by Textras** [comment]
Yes this would be awesome 👍 we could certainly use it 😎

**Comment by CodeWithOz** [comment]
@roman-rr on my end I do some tasks after initializing the pane with `new CupertinoPane(...)`, and those tasks have assumptions for what will happen after the sheet is destroyed. Those assumptions rely on what happens inside the `willDismiss` and `didDismiss` callbacks so that's why I need an option to invoke them even if the pane is never presented.

Also just so you're aware, I always present the panes. This problem came to my attention because of an uncaught error in another part of my code that interrupted the logic that presents the panes. So I saw that when something like that happens I didn't have a way to make sure the `willDismiss` and `didDismiss` callbacks are still executed when the pane is destroyed.

**Comment by roman-rr** [comment]
@CodeWithOz Good case to using `async/await`,  especially on present
```js
await sheet.present({animate: true});
```
Or promise like
```js
sheet.present({animate: true}).then(() => {
  ...
});
```

Than assign your next functions after promise been invoked, and you will no more need to check if `sheet.rendered`. 
Here is logically misspelled in code and no features really required. It will be a hacky to add `didDismiss` callback for non-rendered pane. 
Review your code logic additionally, or let me check this part, i will help you.

**Comment by CodeWithOz** [comment]
@roman-rr thanks for the suggestion :+1: . Unfortunately that won't be a good solution for me because of the type of changes it will require. I already have too much logic that works with the callbacks. I'll continue with my method for now.
