### ISSUE TITLE
[BUG] unable to drag to dismiss when not at top of scrollable list

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#184]
**Describe the bug**
It appears that I cannot drag to dismiss the sheet while the contents are scrolled down. I can only drag to dismiss when I've scrolled to the top of the list. I've specified `.pane`, `.backdrop`, `.draggable` as `dragBy` targets, but this doesn't help.

**To Reproduce**
1. Go to [this build](https://github.com/CodeWithOz/cordova-bad-web-workers/actions/runs/2637876893) and download the APK
2. Install it and click on "Init Pane" and scroll down the list. Then try to dismiss from the top of the pane where `.draggable` is, you will see that the pane cannot be pulled down until you've scrolled back to the top.

**Expected behavior**
I should be able to drag to dismiss the pane if I have scrolled down the list.

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Tecno Android phone and Samsung Galaxy Ultra Note 20
 - OS: Android 8.1 - Android 12
 - Browser: Chrome Webview
 - Version: 102

**Additional context**
N/A

**Comment by roman-rr** [comment]
Hello @CodeWithOz 
It's been a while since I touch this issue, and seems that I just complete it and you must be able to move scrolled pane with draggable element.
