### ISSUE TITLE
[BUG] Any way to fix this keyboard issue? (not in an app)

### ISSUE THREAD

**Issue by omar2205** [roman-rr/cupertino-pane#187]
**Describe the bug**
I have this cupertino-pane that has an input. On phone, when I click the input, the keyboard shows up and misses the pane.

The problem is, I can't even see what I'm typing.

https://i.imgur.com/lfgRSEg.mp4 

**To Reproduce**
1. Have a cupertino-pane with an input
2. Visit on mobile
3. Click the input
4. See the problem

**Comment by roman-rr** [comment]
Hello @omar2205 thank you for issue!
Have you try to set `handleKeyboard: false` ? Does it work for you ?

**Comment by omar2205** [comment]
Yeah, I tried it with no luck. It's not an app, it's a website.

**Comment by roman-rr** [comment]
@omar2205 Please confirm that only on chrome browser, or safari is also affected ?

**Comment by omar2205** [comment]
Yep, the same thing with Firefox. I can't test Safari.

**Comment by omar2205** [comment]
@roman-rr I made this quick demo https://whole-mole-32.deno.dev/

**Comment by flangapp** [comment]
is there a quick solution?

**Comment by flangapp** [comment]
Hack solution:

For .pane class change styles: 

.cupertino-pane-wrapper .pane {
    position: absolute;
    width: 100vw;
}

now it works as expected

**Comment by roman-rr** [comment]
@flangapp thank you. Might fit some cases, but not all. I will check soon keyboard issues.

**Comment by omar2205** [comment]
@roman-rr
I kinda fixed it by having:

```css
  .pane {
    transform-origin: top !important;
  }
```

But there is a problem with the pane's height...

**Comment by justjoshin83** [comment]
Hey guys! Just wanted to see if there's been an official resolution for the keyboard issues.  My issue is that the keyboard actually covers the pane itself, so I can't see the input.  If I need to open a separate issue I will, but I just wanted to check to see if there have been any updates on keyboard-related problems.  Thanks!

**Comment by roman-rr** [comment]
Thank you @justjoshin83 
You show a different issue, compare with others here. Please create new one and I will help you to handle it. 
Quick overview of your bug: Try to focus input after transition end (if you do focus programmatically with `.focus()` );

**Comment by hackal** [comment]
I believe that the issue is related to the `isFormElement` function. I had similar problem (pane flying away when focusing input). Solved it by updating `isFormElement` to return true for content editable too. Fixed my issue

```
isFormElement(el) {
        const formElements = [
            'input',
            'select',
            'option',
            'textarea',
            'button',
            'label',
        ];
        if (
            (el &&
                el.tagName &&
                formElements.includes(el.tagName.toLowerCase())) ||
            el.getAttribute('contenteditable') === 'true'
        ) {
            return true;
        }
        return false;
    }
```

**Comment by roman-rr** [comment]
Everyone's on this topic, please check `v1.3.2` with recent fix and let me know if it's works better.

**Comment by omar2205** [comment]
Tested this https://whole-mole-32.deno.dev on Chrome Android **it looks fixed!**

**Comment by Lychfindel** [comment]
Hi all, I'm having the same issue using v.1.3.2 on safari on iOS.
Moreover I see the same behaviour also on https://whole-mole-32.deno.dev/ (but i don't know if there the package was updated).

**Comment by omar2205** [comment]
https://whole-mole-32.deno.dev uses the latest version so it should be updated. Can you record it?

**Comment by Lychfindel** [comment]
> https://whole-mole-32.deno.dev uses the latest version so it should be updated. Can you record it?

Here the video using Safari on iOS 16.1.1

https://user-images.githubusercontent.com/58313635/216852354-759c2b69-dbf5-408a-a5c6-9a8711ccaa3e.MP4

**Comment by omar2205** [comment]
This is the same behaviour I get, which I consider fixed as it is better than my video above.

**Comment by Lychfindel** [comment]
Sorry, probably I didn't get what was the bug since I cannot see any major difference between the two videos. 
For me the bug is that when the input get the focus everything is pushed by the keyboard (and in the example you cannot see anymore the green background), I think the expected behaviour should be that the keyboard appears but the pane remains at the same height (so you should still see the green background).
If this is different from the bug of this issue I apologise and I will open a new one!

**Comment by omar2205** [comment]
If you check out this video https://i.imgur.com/lfgRSEg.mp4, the whole pane is pushed upwards, making the input hidden. When you close it, you can see the background on the bottom.

You may want to open a new issue if you think this behaviour is wrong.

**Comment by roman-rr** [comment]
Important! All cases related to textarea please describe here #217
But in common should better after latest review.
