### ISSUE TITLE
isHidden spam warnings

### ISSUE THREAD

**Issue by bazuka5801** [roman-rr/cupertino-pane#190]
When I try to check the pane `isHidden()` I get a warn message, why do I need a call `present()` if I want to check that the pane is hidden?

I think this is an error and we need to remove this `if`.

https://github.com/roman-rr/cupertino-pane/blob/2d663bb0cba5d96013661518744160ac029a7b00/src/cupertino-pane.ts#L555-L562

## Screenshots
![image](https://user-images.githubusercontent.com/11452353/182009881-86f41aa3-bf5a-4e5f-b2ce-6d9a3c07e94e.png)

**Comment by bazuka5801** [comment]
Hmm, I got this works, may be `isPanePresented` mean first pane open for initialization for `isHidden` method

```js
if (
  pane.value !== null &&
  pane.value.isPanePresented() &&
  !pane.value.isHidden()
) {
  pane.value.hide();
}
```

**Comment by roman-rr** [comment]
@bazuka5801 absolutely exactly.

`Present pane` is mean to render DOM elements and create a class. 
`Hidden` is mean was hidden with `.hide()` method and just out of the screen. 

Not presented pane couldn't be hidden. 

Alternatively could be used as
```js
if (pane.value.rendered 
    && !pane.value.isHidden()) {
  pane.value.hide();
}
```

**Comment by bazuka5801** [comment]
@roman-rr Thanks for clear solution :)
