### ISSUE TITLE
Calling hide() crash component if present() never been called

### ISSUE THREAD

**Issue by hatsantos** [roman-rr/cupertino-pane#20]
I just found a bug in the latest version of this component.

When trying to call the hide() method, if the present() method was never been called, the component crashes with an error:

```
core.js:6185 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'style' of undefined
TypeError: Cannot read property 'style' of undefined
    at CupertinoPane.hide (cupertino-pane.esm.bundle.js:444)
```

```
hide() 
{
        //The problem seems to be in this line... 
        //this.paneEl is only created in drawElements() 
       //and drawElements() is only called in present()
       //Maybe add:  if (!this.paneEl) return;
        this.paneEl.style.transition = `transform ${this.settings.animationDuration}ms ${this.settings.animationType} 0s`;

        this.paneEl.style.transform = `translateY(${this.screen_height}px)`;
        let initTransitionEv = this.paneEl.addEventListener('transitionend', (t) => 
        {
            this.paneEl.style.transition = `initial`;
            initTransitionEv = undefined;
        });
}
```

**Comment by roman-rr** [comment]
@hatsantos Thank you for inform, some errors handlers will appears in future releases. 
Currently, don't forget to present component before rather manipulatings.

**Comment by hatsantos** [comment]
I was using present({animate:true}) to show the pane only when a details button was clicked.

So I should always call present() and set initialBreak: "bottom", for example, if I do not want to start the the pane open and them use moveToBreak or hide to show/hide the pane?

**Comment by roman-rr** [comment]
@hatsantos logic your described should works. Let me know if not.

**Comment by hatsantos** [comment]
Yes... Already made the changes... It's working! Thank you for your time!
