### ISSUE TITLE
[BUG] Keyboard after hide cause ui not adjust back to previous height

### ISSUE THREAD

**Issue by privaterepo2021** [roman-rr/cupertino-pane#201]
**Describe the bug**
After hiding the keyboard, drawer ui is not adjust back to normal.

**To Reproduce**
1. Tap in input
2. Keyboard is shown
3. Tap on keyboard background to hide keyboard
4. UI is not adjusted back to normal

**Expected behavior**
UI should adjusted back to before keyboard is open

**Videos**
https://user-images.githubusercontent.com/77655845/219937155-6d5e5143-fb52-42c0-9e01-e054312b1720.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung A31
 - OS: Android 12

"cupertino-pane": "1.3.2"

**Comment by roman-rr** [comment]
@privaterepo2021 Definitely strange behavior and weird height pane goes up on keyboard. 
How quickly do you need a solution ? If this is urgent issue, try to reproduce behavior with some code sources that I can digging deeper.

**Comment by privaterepo2021** [comment]
Hi @roman-rr, it only happens if i tap on the background to hide the keyboard, but if I hide the keyboard using back button then it wont have this kind of problem. Is not that urgent for now because I already use a solution to adjust back the height after the pane height is adjusted to wrong height. You can try on it when you free, thanks.

**Comment by privaterepo2021** [comment]
Hi @roman-rr , I will close it first since I'm not able to reproduce the issue in a simple application. Will reopen back once I able to reproduce it thanks.
