### ISSUE TITLE
Cannot hide or destroy animated

### ISSUE THREAD

**Issue by BerkeAras** [roman-rr/cupertino-pane#21]
I cannot hide or destroy it animated.
My code:
```js
function showPane() {
    var myPane = new CupertinoPane('.cupertino-pane', {
        backdrop: true
    });
    myPane.present({
        animate: true
    });
}
function hidePane() {
    var myPane = new CupertinoPane('.cupertino-pane', {
        backdrop: true
    });
    myPane.hide();
}
```

showPanel() works. hidePanel() hides without animation, and I get this error:
`Uncaught TypeError: Cannot read property 'style' of undefined`

**Comment by roman-rr** [comment]
@BerkeAras I still need to handle error handling to prevent such type of issues, but in general the issue in your code structure. 

With this lines you create Pane new class: 
```javascript
var myPane = new CupertinoPane('.cupertino-pane', {
  backdrop: true
});
```

For **showPane()** its works, because you call `myPane.present()` method (which is necessary to render pane). 
For **hidePane()** you once again create new Pane class, but `myPane.present()` is not called. 

This will works without error:
```
function hidePane() {
    var myPane = new CupertinoPane('.cupertino-pane', {
        backdrop: true
    });
    myPane.present();
    myPane.hide();
}
```

But with your code you will not use same Pane, because you re-create Pane class in each function. 

Finally, the correct implementation for you is get pane one-level out of scope: 

```
const myPane = new CupertinoPane('.cupertino-pane', {
        backdrop: true
});

function showPane() {
    myPane.present({
        animate: true
    });
}
function hidePane() {
    myPane.hide();
}
```

**Comment by BerkeAras** [comment]
But then I get this: 
`Uncaught TypeError: myPane.hide is not a function`

**Comment by roman-rr** [comment]
@BerkeAras Explore this simple html example, you can save as html and open in browser.  

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <script>var exports = {"__esModule": true};</script> <!-- Required if exports not defined earlier -->
        <script src="https://unpkg.com/cupertino-pane/dist/cupertino-pane.min.js"></script>
    </head>
    <body>
        <button onclick="showPane();">Show</button>
        <button onclick="hidePane();">Hide</button>
        <div class="cupertino-pane">
            <h1>Header</h1>
            <div class="content">Content</div>
        </div>
        <script>
            var myPane = new CupertinoPane('.cupertino-pane', { /* ... */ });

            function showPane() {
                myPane.present({
                    animate: true
                });
            }

            function hidePane() {
                myPane.hide();
            }
        </script>
    </body>
</html>
```

**Comment by BerkeAras** [comment]
Thank you, it works, but if I use backdrop: true, hidePane doesn’t removes backdrop.

**Comment by roman-rr** [comment]
@BerkeAras You can use 
```javascript
myPane.destroy({
  animate: true
});
``` 
instead of 
```javascript
myPane.hide();
```

On the next release i will also include hidden backdrop for hide method.

**Comment by roman-rr** [comment]
@BerkeAras already pushed new version with fix. 
Please, close issue, if solved.
