### ISSUE TITLE
current break point not updating when moveToBreak() used

### ISSUE THREAD

**Issue by jaimyborgman** [roman-rr/cupertino-pane#22]
Using this awesome plugin in my project works fine but needs some more improvements tho... especially when calling the moveToBreak manually the currentbreak state isn't changing i even don't see it updating inside that method... please add a line which will update the `this.currentBreakpoint` as well

**Comment by roman-rr** [comment]
@jaimyborgman 
Thanks for notification. Fixed. Updated in `1.1.34` version.
