### ISSUE TITLE
[BUG] z-Index issue or request to set it manually.

### ISSUE THREAD

**Issue by woutersteven** [roman-rr/cupertino-pane#222]
**Describe the bug**
Using Ionic 7+ and Angular 16+

<ion-fab> component appears in front of pane. Manually changing the z-index in Chrome Dev Tools hides the Fab button behind the pane, which is the desired beahvior.

I have two panes on 1 page, one for when somebody clicks on an ion-item...(to edit it), this is working well.. and one at the bottom of the page, which acts as a FAB button.. The class for that one is:

```
<div class="cupertino-pane-in-tabs">
</div>
```
How can i manually change the z-index of the wrapper? or is there a property that i missed that will prevent the ion-fab from showing on top of the pane? These are my current settings for the relevant pane.

```
  private cupertinoPaneSettings: CupertinoSettings = {
    modal: false,
    backdrop: true,
    fitHeight: false,
    bottomClose: true,
    breaks: {
      middle: { enabled: true, height: 200, bounce: true },
      bottom: { enabled: true, height: 80 }
    }
  };
```
The pane itself is working, its just not in front of the <ion-fab> component.

**Comment by roman-rr** [comment]
@woutersteven2020 Just quick recommendation before checking the issue description is to check `parentElement` settings. Try set the option `parentElement` to 'body' or `ion-content`. I will check soon description.
