### ISSUE TITLE
how to prevent pane from sliding while swiping in content section

### ISSUE THREAD

**Issue by jaimyborgman** [roman-rr/cupertino-pane#23]
I'm using your plugin inside my vue js ionic app it works nice but I'm curious if there is a way to prevent the drawer from sliding up and down while I'm swiping any ion-item's currently the pane is going up and down if you do not swipe in a straight line (which isn't natural of course) so I was thinking to combine the @ionDrag on the ion-item-sliding element and then trigger something on your cupertino pane that it should ignore any swipe events or at least stop moving

or is there another option which maybe could be helpful in this situation? looking forward to it tho!

**Comment by roman-rr** [comment]
@jaimyborgman Thanks for issue.
Please record a video with bug demonstration.

**Comment by jaimyborgman** [comment]
@roman-rr sure see the video here:
https://streamable.com/6z7ceb

**Comment by roman-rr** [comment]
@jaimyborgman 
Pushed new version **1.1.37** with two new methods: `disableDrag()`, `enableDrag()`

Try to implement like this: 

```html
<ion-item-sliding (touchend)="touchEnd($event)" (ionDrag)="ionDrag($event);">
...
</ion-item-sliding>
```

```javascript
public pane: CupertinoPane;
constructor() { ... }
ionDrag = (e) => this.pane.disableDrag();
touchEnd = (e) => this.pane.enableDrag();
```

**Comment by jaimyborgman** [comment]
thanks for this @roman-rr it is working but not as smooth as i hoped it would be, sometimes it is still a little glitchy but way better then before!

i'm also working with ionic in combination with vue js and as per the new version of ionic there is only an ionDrag event possible currently combined it like this

```const drawer = this.$parent.drawer
if (drawer.disableDragEvents) return
drawer.moveToBreak('top')
drawer.disableDrag()
setTimeout(() => {
    drawer.enableDrag()
}, 500)```

which is doing the job for now so thanks!

**Comment by roman-rr** [comment]
@jaimyborgman glitchy is not satisfaction. Quality first. :) 

I guess this is exactly what you need: 
```html
<ion-item-sliding         
        [disabled]="slideDisabled"
        (touchmove)="touchMove($event)"
        (touchend)="touchEnd($event)" 
        (touchstart)="touchStart($event);">
...
</ion-item-sliding>
```

```javascript
private slideDisabled: boolean = false;
private slideChecked: boolean = false;
private steps: {y: number[], x: number[]} = {y: [], x: []};
constructor() { ... }
touchStart = (e) => {
    this.steps.y.push(e.targetTouches[0].screenY);
    this.steps.x.push(e.targetTouches[0].screenX);
};
  
touchMove = (e) => {
    if (this.slideChecked) return;

    const coords = {
      x: e.targetTouches[0].screenX, 
      y: e.targetTouches[0].screenY
    };
    const delta = {
      x: coords.x - this.steps.x[this.steps.x.length - 1], 
      y: coords.y - this.steps.y[this.steps.y.length - 1]
    };

    if (Math.abs(delta.y) > Math.abs(delta.x)) {
      this.slideDisabled = true;
    } else {
      this.locationsPane.disableDrag();
    }
    this.slideChecked = true;
};

touchEnd = (e) => {
    this.slideDisabled = false;
    this.slideChecked = false;
    this.locationsPane.enableDrag();
    this.steps = {x: [], y: []};
};
```

**Comment by jaimyborgman** [comment]
@roman-rr thanks for the solution

is there also an option possible to only listen to drag events on the draggable item?
would be a nice addition instead of listening on the whole drawer

**Comment by roman-rr** [comment]
@jaimyborgman Currently don't have this option. I will include this option if at least 2 requests will collected here.

**Comment by newfield86** [comment]
> @roman-rr thanks for the solution
> 
> is there also an option possible to only listen to drag events on the draggable item?
> would be a nice addition instead of listening on the whole drawer

That would be indeed a nice addition!

**Comment by roman-rr** [comment]
@newfield86 scheduled for next version :)

**Comment by roman-rr** [comment]
Done with new setting property `dragByCursor`

**Comment by jaimyborgman** [comment]
many thanks @roman-rr and @newfield86

**Comment by roman-rr** [comment]
### Update notes for version > 1.1.6
- Removed `dragByCursor` options from settings
- Added `dragBy` options to settings. 

Now you can bind drag gestures only for cursor by adding to settings: 
```javascript
let settings: CupertinoSettings = {
  ...
  dragBy: ['.pane .draggable']
};
```

**Comment by jaimyborgman** [comment]
hi @roman-rr i've updated to version 1.1.6 and tried to use the dragBy as mentioned but now the full pane is listening on drag events again, while with the previous the pane could be disabled?

**Comment by jaimyborgman** [comment]
hi @roman-rr thanks for the update!
