### ISSUE TITLE
Animate Backdrop Remove

### ISSUE THREAD

**Issue by BerkeAras** [roman-rr/cupertino-pane#28]
How to animate Backdrop Remove using ``myPane.hide();``?

**Comment by roman-rr** [comment]
@BerkeAras Thanks for issue. 

In the last version animation implemented to backdrop. Animation for backdrop will follow pane animation options: `animationType`, `animationDuration`.

Also `backdropTransparent` replaced with `backdropOpacity`, so you can specify final backdrop opacity level.
