### ISSUE TITLE
[Error] Ionic deployment: "Cupertino Pane: wrong selector specified .cupertino-pane" error

### ISSUE THREAD

**Issue by Andranik0** [roman-rr/cupertino-pane#29]
Hi,

I'm currently trying to implement a drawer slide-over pane based on your cupertino-pane repository (which looks very great!).

I'm having some trouble while trying to deploy it on my **Ionic** app. An error is raised after serving the app: "_Cupertino Pane: wrong selector specified .cupertino-pane_".

**HTML file**
```
<ion-content>
  <div class="cupertino-pane">
    <h1>Header</h1>
    <p>Content</p>
  </div>
</ion-content>
```

**CSS file**
```
.cupertino-pane {
    margin: 20px;
    background:#eee;
}
```

**TS file**
```
import { CupertinoPane } from 'cupertino-pane';
[...]
  drawer = new CupertinoPane('.cupertino-pane', {
      onDrag: () => console.log('Drag event')
  });

  constructor() {
    this.drawer.present({ animate: true });
  }
```

![2020-05-11_19h34_22](https://user-images.githubusercontent.com/22680538/81592613-84d76780-93be-11ea-843c-55656daec73b.png)

FYI, it seems to work if I write:
```
  drawer = new CupertinoPane('body', {
      onDrag: () => console.log('Drag event')
  });
```
... but it then does not have the expected behavior: in that case, all the page, including the toolbars, are inside the pane. 

![2020-05-11_19h40_26](https://user-images.githubusercontent.com/22680538/81593130-44c4b480-93bf-11ea-91a1-4bfb1aa25f0c.png)

**Versions**
cupertino-pane@1.1.43
ionic@5.4.16

What could I do to deploy this plugin properly in my Ionic-with-tabs environment?

Thanks a lot in advance for your help! 👍 

Andra

**Comment by roman-rr** [comment]
Hi @Andranik0 
You are using correct selector in this case`.cupertino-pane`, but you do initialization of Pane, before DOM element rendered. 

To fix, just initialize Pane after view init: 

```javascript
...
public drawer: CupertinoPane;
constructor() { ... }

ngOnInit() {
  // Here pane initialization
  this.drawer = new CupertinoPane('body', {
    onDrag: () => console.log('Drag event')
  });
  // And present
  this.drawer.present();
}
```

**Comment by Andranik0** [comment]
Hi @roman-rr,

It works fine! Thanks a lot!

![2020-05-11_20h14_28](https://user-images.githubusercontent.com/22680538/81596238-07165a80-93c4-11ea-98a2-679b544664a4.png)
