### ISSUE TITLE
Wrong childnode selected for Content 

### ISSUE THREAD

**Issue by Tommertom** [roman-rr/cupertino-pane#3]
Hi, 

I was trying your code in a svelte project using the demo code

html:
```
<div class="cupertino-pane">
  <div class="cupertino-header">Header</div>
  <div class="cupertino-content">Content</div>
</div>
```
`  import { CupertinoPane } from "cupertino-pane";`

I had to change the esm bundle line 184 to select childNode 2 instead of 1 for content in order for the code to work.

```
 // Content
 this.contentEl = this.el.childNodes[1];
```

into `this.el.childNodes[2]`

Otherwise it would say it tries to set `transition` on `undefined` in the following line:

` this.contentEl.style.transition = "opacity " + this.settings.animationDuration + "ms " + this.settings.animationType + " 0s";        this.contentEl.style.overflowX = 'hidden';`

Given the html, `this.el.childNodes[1]` is a text element, where is `[2]` is a div it needs to attach to.

Not sure if this is typical svelte thing, but I do guess svelte does not add extra dom elements (its not known for it). So this may be an error in your code?

My code: https://github.com/Tommertom/svelte-ionic-app/blob/master/src/pages/ionic/Pane.svelte
And demo: https://ionicsvelte.firebaseapp.com/pane

**Comment by roman-rr** [comment]
@Tommertom Thanks for your attention! 
I will use your link in readme for temporary demonstration.
[https://ionicsvelte.firebaseapp.com/pane](https://ionicsvelte.firebaseapp.com/pane/)

### Regarding to your issue
I found that **svetle** add additional Element `text` to nodeList after each div 
```html
<ion-content>
...
  <div class="new-content">
    <div class="one"></div>
    <div class="two"></div>
    <div class="three"></div>
  </div>
</ion-content>
```
```javascript
<script>
  import { onMount } from "svelte";

  onMount(() => {
    let childNodes = document.getElementsByClassName('new-content')[0];
    console.log(childNodes.childNodes);
  });
</script>
```
Outputs 
<img width="595" alt="Screen Shot 2019-12-27 at 13 23 44" src="https://user-images.githubusercontent.com/10646478/71504488-306a9a00-28ac-11ea-867e-6432e91d6056.png">

That's reason of incorrect DOM assigment.

### Solution
i did some enhancements to prevent similar cases. 
No required for now to specify entries inside common container: 
```html
<div class="cupertino-pane">
  Any content can placed here
  <div class="body" hide-on-bottom>
  ...
  </div>
</div>
```
*hide-on-bottom attribute will set opacity:0 for element if bottom breakpoint reached*

### In your case you can just update package and it should works without errors!

**Comment by Tommertom** [comment]
Yup. seems to work like a charm. Sorry to see svelte doing the additional element. 

Thx for updating.
