### ISSUE TITLE
New Feature: Make Draggable Shape Over Modal

### ISSUE THREAD

**Issue by BerkeAras** [roman-rr/cupertino-pane#32]
Make the Draggable Shape over the modal. It should be in the configuration (Like draggableOverModal = true). It should look like this:
![image](https://user-images.githubusercontent.com/36629890/82219513-a9cb5d80-991d-11ea-9e6d-667617aa77dd.png)

**Comment by roman-rr** [comment]
Hello @BerkeAras 

Update pane to `1.1.52`, then try new option
```javascript
const this.drawer = new CupertinoPane('.drawer', { 
  draggableOver: true
});
```

Style element if you need
```css
.draggable .move {
  ...
}
```

**Comment by BerkeAras** [comment]
Thanks, that is perfect!
