### ISSUE TITLE
[Feat. Request] Add donate feature

### ISSUE THREAD

**Issue by hatsantos** [roman-rr/cupertino-pane#33]
Hello Roman,

First of all let me thank you for this lib... I'm using it, and it's solving a lot of UI/UX problems that I face in my apps, giving them a more modern and refreshing look.

I noticed the work and effort that you are putting in this project, closing issues and adding new features. I would suggest a donate button on the first page, so I can express my gratitude (and hopefully others) sending you some "bucks"... It will not be much, but it will be well deserved...

**Comment by roman-rr** [comment]
@hatsantos Thanks for request! 

GitHub just approved sponsors program for my profile https://github.com/sponsors/roman-rr

**Comment by hatsantos** [comment]
It think it's done! Let me know if theres any problem.

Thank you again for you work.
