### ISSUE TITLE
New Feature: Make draggable translucent if it is over the pane.

### ISSUE THREAD

**Issue by BerkeAras** [roman-rr/cupertino-pane#34]
New Feature: Make the draggable shape translucent if it is over the pane. You could use this code:
```css
backdrop-filter:blur(6px);
background:rgba(255,255,255,0.5);
```

**Comment by roman-rr** [comment]
@BerkeAras Thanks, it's look nice. 
Are you able to create pull ?

**Comment by BerkeAras** [comment]
Sure I'll create a pull request, and close the issue then.

**Comment by BerkeAras** [comment]
Pull Request created.

**Comment by roman-rr** [comment]
@BerkeAras Created default for draggableOver, without draggableTransition property. 
Other styling you can do with css (if anulgar): 
```css
::ng-deep .move {
  ...
}
```

**Comment by BerkeAras** [comment]
Is it possible to add it to the common configuration?

**Comment by roman-rr** [comment]
@BerkeAras this styles are by default now if `draggableOver : true`
