### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by dragoon000320** [roman-rr/cupertino-pane#38]
**Describe the bug**
When i compile my ionic app with cupertino-pane installed i get following compilation error:

ERROR in node_modules/cupertino-pane/dist/cupertino-pane.d.ts(58,17): error TS1086: An accessor cannot be declared in an ambient context.

**To Reproduce**
bootstrap ionic app, npm install cupertino-pane, run ionic serve.

**Expected behavior**
no compilation error

**Desktop (please complete the following information):**
I don't think it relates to it

**Additional context**
I tried to add "skipLibCheck": true to tsconfig to ignore this error. It looked like it helped, few compilations were ok, but later i got the same error...

**Comment by roman-rr** [comment]
@dragoon000320 Thank you for issue. 

Previous typescript can throw errors with getters. 
So, i just push fix for support previous version
Please update `cupertino-pane` in project until latest `1.1.55
```bash
$ npm install cupertino-pane@latest --save
```

**Comment by dragoon000320** [comment]
@roman-rr thank you for the fix, it compiles now without issues
