### ISSUE TITLE
Feature Requests & Questions

### ISSUE THREAD

**Issue by HansKrywaa** [roman-rr/cupertino-pane#41]
Hey there 😊

**first**: This look very good, but i have a few Points why i can't use this yet. I will point them out here, maybe, if you have time, you can investigate into this?

1. The Usage in the Browser (Safari in my case) doesn't really work well. I expect it to work when i press the mouse and move down (like the new ionic card style ios modal). Currently it works somehow strange that if i go with my mouse over it down, without holding) it scrolls down and then stays there.
2. I opened the drawer from a Modal and was able to close the Modal via swipe gesture while the drawer was opened. Not as i expect this.
3. I really really need to be able to create a Drawer via a Component (and componentProps). Like you can with a Modal in Ionic. In the component i need able to get the Instance of the drawer to dismiss it from there.
4. For this. i want to be able to pass data while dismissing and be able to get this data in the `onDidDismiss` (and other) Functions
5. Question: Is it possible to make the height of the Drawer fit to the content? Should also work when i pass a component.

Let me know what you think about this topics. Maybe some are already possible and i'm using it wrong? Also if you need assist, i will give my best to support you 😊

**Comment by BerkeAras** [comment]
1. I have the problem sometimes too :(
2. did you try backdrop configuration?

**Comment by HansKrywaa** [comment]
1. I have this all the Time
2. Of course, i have set a Backdrop, but this is only over the Modal

**Comment by roman-rr** [comment]
Hello @HansKrywaa 
Sure, let me check. 

1. Desktop gestures a little bit different, but Pane was developed as mobile first. 
This bug already listed as number one in [priority list](https://github.com/roman-rr/cupertino-pane#future-goals) and will be fixed ASAP with next release.

2., 3., 4., 5. Share for me some repository. I modify code and will show you how to get it works with current Pane functions.

**Comment by roman-rr** [comment]
Desktop gestures should be fixed

**Comment by HansKrywaa** [comment]
Okay i just tested around with it and maybe i was too fast with my points.
1: Gets way much better in `v1.1.63` - Sometimes it bugs because my Desktop tries to copy stuff, but this could be an safari topic
2. If i set `parentElement: 'body'`: resolved ✅
3. Of course it is possible to do something like that:
```html
<div class="cupertino-pane">
  <app-test></app-test>
</div>
```
Is this the Way how to use Components?
4. Kinda resolved with 3
5. Can you explain? 😃

I think it would be very very awesome to be able to create this just like in Ionic. Using a Provider (`drawerController`) which can have a Component and ComponentProperties. But this would be a huge major breaking change.

**Comment by roman-rr** [comment]
@HansKrywaa 
1. If desktop bugs critical for your software please describe a bug or record a video. 
3. Create some service that will handle Pane class. This is example of my service with Angular: 
```javascript
```

**Comment by roman-rr** [comment]
@HansKrywaa 
### Desktop mode
If some of desktop bugs is critical for your software, please describe a bug or record a video. 

### Pane as Component/Service
Create some service that will handle Pane class. This is example of my service with Angular: 

```javascript
import { Injectable, ComponentFactoryResolver, ViewContainerRef } from '@angular/core';
import { CupertinoPane, CupertinoSettings } from 'cupertino-pane';
import { Subject } from 'rxjs';

@Injectable()
export class PaneService {
  public app_ref: ViewContainerRef;
  public onEvent: Promise<boolean>;
  private pane: CupertinoPane;
  private dismissed: Promise<boolean>;
  constructor(private factoryResolver: ComponentFactoryResolver) {}
  
  async present(component): Promise<any> {
    // Create dom component
    const factory = this.factoryResolver.resolveComponentFactory(component);
    const cmp:any = this.app_ref.createComponent(factory);
    cmp.location.nativeElement.style.visibility = 'hidden';
    cmp.changeDetectorRef.detectChanges();

    // Offset calculation for X devices
    const deviceOffset = () => {
      const sab = getComputedStyle(
        document.documentElement
      ).getPropertyValue("--ion-safe-area-bottom");
      return parseFloat(sab.replace('px', ''));
    }

    // Auto height component calculation
    const elem = <HTMLDivElement>document.querySelector('.cupertino-pane');
    const computed = getComputedStyle(elem);
    await new Promise(resolve => setTimeout(resolve, 150));
    const height: number = parseFloat(computed.getPropertyValue('height'));
    cmp.location.nativeElement.style.visibility = 'inherit';

    // Dismissed callback as promise
    const dismissedEvent: Subject<boolean> = new Subject<boolean>();

    // Present pane
    const settings: CupertinoSettings = {
      initialBreak: 'top',
      breaks: {
        top: { enabled: true, height + deviceOffset()},
        middle: { enabled: false},
        bottom: { enabled: false},
      },
      backdrop: true,
      onBackdropTap: () => this.pane.destroy({animate: true}),
      onDidDismiss: () => {
        cmp.destroy();
        cmp.location.nativeElement.remove();
        cmp.instance.onEvent?.emit(null);
        dismissedEvent.next(true); 
      }
    };

    // Listen event on pane
    this.onEvent = new Promise((resolve, reject) => {
      cmp.instance.onEvent.subscribe((res) => {
        resolve(res);
      }, (err) => {
        reject(err);
      });
    });

    this.dismissed = new Promise(async (resolve) => {
      dismissedEvent.subscribe(res => resolve(cmp));
    });

    this.pane = new CupertinoPane('.cupertino-pane', settings);
    this.pane.present({animate: true});
  }

  async dismiss(): Promise<any> {
    if (!this.pane) return;
    this.pane.destroy({animate: true});
    await this.dismissed;
    delete this.pane;
  }
}
```

And your component `PaneComponent`
```
@Component({
  selector: 'app-pane',
  template: `
    <div class="cupertino-pane">
      <ion-button expand="block" color="primary" (click)="submit();">
         OK
       </ion-button>
     </div>`
})
export class PaneComponent {
  @Output() onEvent = new EventEmitter<boolean>();
  constructor(private paneService: PaneService) {}
  
  private dismiss = async() => {
    await this.PaneService.dismiss();
  }

  private submit() {
    this.onEvent.emit(true);
  }
}
```

Then i use service to control Pane created from `PaneComponent`
```javascript
import { PaneComponent } from '../pane.component/pane.component';
import { PaneService } from '../services/pane/pane.service';

constructor(private paneService: PaneService) {}

presentPane() {
  await this.paneService.present(PaneComponent);
  const res = await this.paneService.onEvent;
  await  this.paneService.dismiss();
}
```

### Height fit content
Explore auto-height calculation block at the service subscribed above 

### Div visibility
Right after class initialization from element `let pane = new CupertinoPane('.cupertino-pane')`, your element will hidden until .present() function. If you Doesn't init class immediately, you can set hidden visibility or none display for element initialization style property as showed in service above.  

### Ionic framework
Of course, it's nice idea to create entry ionic service/component from Pane, but on this moment my [pull request](https://github.com/ionic-team/ionic/pull/20408) on holding mode. Maybe in future, when this library will looks dope!

**Comment by HansKrywaa** [comment]
@roman-rr 
Big thanks to your Explanation! 😊 I will use this without a Service like this for the Moment and hope that Ionic has this on their Roadmap^^

**Comment by HansKrywaa** [comment]
Some new Feature Request: I think the native Drawer changed the Backdrop Opacity to go smaller while swiping down. This would be good here too.

**Comment by roman-rr** [comment]
@HansKrywaa is that what you need ? 
https://output.jsbin.com/ludoreg

**Comment by HansKrywaa** [comment]
I don't know, because the Content needs to be a List that is larger than the pane itself. So i can scroll it

**Comment by roman-rr** [comment]
> Some new Feature Request: I think the native Drawer changed the Backdrop Opacity to go smaller while swiping down. This would be good here too.

This is how you can implement it with `v.1.1.64`
```javascript
ngOnInit() {
  const topPosition = 600; // Maximum height
  const backdropOpacity = 1; // Maximum value

  const drawer = new CupertinoPane('ion-drawer', { 
    backdrop: true,
    initialBreak: 'top',
    breaks: {
      top: {enabled: true, height: topPosition},
      middle: {enabled: true, height: 300},
      bottom: {enabled: false}
    },
    backdropOpacity,
    onBackdropTap: () => destroyDrawer(),
    onDrag: () => this.changeOpacity(this.getPaneTransformY(), 'unset'),
    onTransitionStart: (e) => this.changeOpacity(e.translateY.new, 'all 300ms ease 0s')
  });
  drawer.present({animate: true}); 
}

changeOpacity(val, transition) {
    const backdrop = document.querySelector('.backdrop');
    const topScreen = topPosition;
    const newScreen = window.screen.height - val;
    const opacity = (backdropOpacity * newScreen) / topScreen;
    if (transition) backdrop.style.transition = transition;
    backdrop.style.backgroundColor = `rgba(0, 0, 0, ${opacity})`;
}

function getPaneTransformY() {
    const translateYRegex = /\.*translateY\((.*)px\)/i;
    const paneEl = document.querySelector('.pane');
    return paneEl ? parseFloat(translateYRegex.exec(paneEl.style.transform)[1]) : 0;
}
```

[Result live](https://output.jsbin.com/riwahab)
