### ISSUE TITLE
Scroll IonContent not possible?

### ISSUE THREAD

**Issue by HansKrywaa** [roman-rr/cupertino-pane#44]
I'm using my Pane with a Header and Content. It's Html is this:

```html
<ion-header>
    <ion-toolbar>
        <ion-title>Langauge</ion-title>
        <ion-buttons slot="end">
            <my-close-button (click)="closePane()"></my-close-button>
        </ion-buttons>
    </ion-toolbar>
</ion-header>

<ion-content>
    <ion-list>
        <ion-radio-group [(ngModel)]="selectedLanguage">
            <ion-item *ngFor="let lang of languages">
                <ion-thumbnail slot="start">
                    <img src="assets/img/flags/{{lang}}.png">
                </ion-thumbnail>
                <ion-label>
                    {{lang}}
                </ion-label>
                <ion-radio slot="end" [value]="lang"></ion-radio>
            </ion-item>
        </ion-radio-group>
    </ion-list>
</ion-content>
```

When i open it i want to be able to scroll the List in the IonContent. But it looks like this:

<img src="https://user-images.githubusercontent.com/20899975/85280636-cc0a4b00-b488-11ea-83d9-0fa93b86fdde.gif" width="300">

Is this a Bug or how to i archive that?

**Comment by roman-rr** [comment]
@HansKrywaa Some devices have bottom offset, and offset might be kinda different. 
In this reason we have option: `topperOverflowOffset`

Try play with some value: 
```javascript
let settings = {
 ...
 topperOverflowOffset: 20
}
```

Or how i solve offsets for all devices in ionic apps: 
```javascript
  // Offset bottom calculation for X devices
    const deviceOffset = () => {
      const sab = getComputedStyle(
        document.documentElement
      ).getPropertyValue("--ion-safe-area-bottom");
      return parseFloat(sab.replace('px', ''));
    }

  let settings = {
    ...
    height: YOUR_VALUE + deviceOffset
  }
``` 

Add some `topperOverflowOffset` if it's still be required.

**Comment by HansKrywaa** [comment]
That's not the Problem here. `--ion-safe-area-bottom` is 0 as i test this in Browser. It's just very buggy while scrolling. I tested this on an Android Device and while scrolling the list the pane scrolls itself too so gets greater or smaller.

**Comment by roman-rr** [comment]
@HansKrywaa how about increase `topperOverflowOffset` ?

**Comment by roman-rr** [comment]
@HansKrywaa Just looked up into code you provided. 
Change `<ion-content>` to `<div class="content" overflow-y>` and it should works well. 
Ion-content has own scroll which give conflicts.

**Comment by HansKrywaa** [comment]
@roman-rr Okay that kinda works it is not buggy anymore. Thanks! 😊

**Some more Points:**
- Now when i try to scroll the List up, it first increase the pane to the next break. Is is possible to scroll the list instead?
- When i now open the Pane to top break, then scroll the list a bit, i'm unable to drag the pane down at the dragging icon. I first have to scroll down...

**Comment by roman-rr** [comment]
@HansKrywaa 

> Now when i try to scroll the List up, it first increase the pane to the next break. Is is possible to scroll the list instead?
Top breakpoint allowed to scroll. You might try to set `initialBreakpoint: 'top'. Is that fit your task ?

> When i now open the Pane to top break, then scroll the list a bit, i'm unable to drag the pane down at the dragging icon. I first have to scroll down...
Thanks, this is bug which will be fixed soon.

**Comment by HansKrywaa** [comment]
Mhh `initialBreakpoint` is not what i want to change here. I want the Pane to start at middle, be able to drag to top, but the list should be scrollable in both positions

**Comment by roman-rr** [comment]
@HansKrywaa 
> When i now open the Pane to top break, then scroll the list a bit, i'm unable to drag the pane down at the dragging icon. I first have to scroll down...

Fixed. 

> Mhh initialBreakpoint is not what i want to change here. I want the Pane to start at middle, be able to drag to top, but the list should be scrollable in both positions

[Live Example](https://output.jsbin.com/piwecad)

As you can see, pane allowed to scrolls in any breakpoint. 
Also, auto-height calculations implemented.

However, we should disable drag gesture by scrollable area, and set drag events to some header elements:
```js
dragBy: ['.draggable', 'ion-drawer h1']
```
If more similar request will appears from different users, i will review again possibility to adjust this behavior with drag by pane also, but this example should fit with your task.

**Comment by HansKrywaa** [comment]
Please checkt his ScreenRecording of your Live Example: https://www.file-upload.net/download-14155468/FullSizeRender.mov.html

I'm not able to scroll the pane in the inital Position. After opening it once: I can.

**Comment by roman-rr** [comment]
@HansKrywaa Which browser/version you are using ? Some steps to reproduce bug ?

**Comment by HansKrywaa** [comment]
Unsing Safari ob my iPhone11Pro with iOS 13.5.1.

This behaviour exists nearly every time when i reload the Page

**Comment by roman-rr** [comment]
@HansKrywaa clear cache and try again https://output.jsbin.com/piwecad

**Comment by HansKrywaa** [comment]
Okay works 👌🏼And this is made via the `dragBy`?

**Comment by roman-rr** [comment]
@HansKrywaa `dragBy` helps also, this option declare which elements will control drag gestures. By default specified to whole pane, in this example only for header and draggable element. 
Please review code provided.
