### ISSUE TITLE
is necessary to use the keyword 'var' to instantiate the pane?

### ISSUE THREAD

**Issue by luislama** [roman-rr/cupertino-pane#45]
Hi!
First of all thank you very much!

I don't know much about js or ts, so I have some doubts...
In README examples you use the keyword '**var**' to instantiate the pane.
Is this necessary?
Any problems if I use '**let**' or '**const**'?

**Comment by roman-rr** [comment]
@luislama variable declaration doesn't change pane functionality. 
But good to know difference between [scope variables](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75)
