### ISSUE TITLE
Dragging Down Triggers Page Refresh

### ISSUE THREAD

**Issue by dionsthilaire** [roman-rr/cupertino-pane#46]
**Describe the bug**
Building an Angular application and testing on an Android phone, dragging down on the pane causes the page to refresh.

**To Reproduce**
1. Go to https://angular-qxxvuj.stackblitz.io/ 
2. Attempt to swipe down pane
4. Observe refresh behavior

**Expected behavior**
Dragging down on the pane should not refresh the page

**Smartphone (please complete the following information):**
 - Device: Pixel 3XL
 - OS: [Android 10 Build/QQ3A.200605.001]
 - Browser [Chrome]
 - Version [83.0.4103.106]

**Additional context**
Angular 9 + Material as provided in this editable stackblitz
https://stackblitz.com/edit/angular-qxxvuj

**Comment by roman-rr** [comment]
@dionsthilaire Thank you for issue. 
Please record a video with bug demonstration.

**Comment by dionsthilaire** [comment]
![DevTools-cupertinodemoz13webcore](https://user-images.githubusercontent.com/67698243/86286718-f8267a00-bbb4-11ea-8950-c0ee6e29801f.gif)

**Comment by roman-rr** [comment]
@dionsthilaire Are you able to reproduce with other android device ? 
Issue with real device or chrome emulation mode on desktop ?
WebView + Chrome both ?

**Comment by dionsthilaire** [comment]
I haven’t tried in an emulator and only have this one device. The recording I sent was of a remote debugging session on that physical device.

**Comment by roman-rr** [comment]
@dionsthilaire 
I'm unable to reproduce [video.zip](https://github.com/roman-rr/cupertino-pane/files/4865821/video.zip)

Device: Pixel 3XL
Chrome: 83.0.4103.44
Android API 30 (> 10)

Moreover, i did try all examples from README.md and all are works. 

I do recommend for you check all examples listed in readme and try buttons, check if some specific pane function give exception in combination of your phone settings/chrome/functions or just drag gesture. Also try different browser and update chrome OS to latest.

**Comment by dionsthilaire** [comment]
Actually, the stack blitz editor frame is preventing the refresh. Please try viewing the page url directly without the editor.

**Comment by roman-rr** [comment]
Seems that somethings with stackblitz. 
Please try: 
1. https://output.jsbin.com/dizerihuwo
2. Try stackblitz without @angular/material/dialog

**Comment by roman-rr** [comment]
@dionsthilaire 
Find solution. Use `ion-content` to prevent this bug. 

The issue is in chrome mobile pull-to-refresh functionality. [Solution](https://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature)  

**Ion-content** should fix drag event with pull-to-refresh.

You can also: 
a) Fix with css
```css
body {
  overscroll-behavior: contain;
  overscroll-behavior-y: none;
}
```
b) Set `touch-action: none` to content except pane, on drag events. 
c) Applying `overflow-y: hidden` to the body element always or while drag events.
d) Disabling the effect locally via chrome://flags/#disable-pull-to-refresh-effect).

**Comment by dionsthilaire** [comment]
Yes, I do agree it works with Ionic and not with Angular. 

Note: There is nothing special about the content, just basic input and enough content to trigger overflow behavior.

Attached is the source for a vanilla Angular CLI application () without Material

1. ng new cupertino-angular-demo-nomaterial
2. cd new cupertino-angular-demo-nomaterial
3. npm install --save cupertino-pane
4. update src/app.component.html 
 <!--`... some really long text-->`

5. update src/app.component.ts
`import { Component } from "@angular/core";
import { CupertinoPane, CupertinoSettings } from "cupertino-pane";
import { PaneBreaks } from "cupertino-pane/dist/models";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "cupertino-angular-demo-nomaterial";
  private bottomDrawer: CupertinoPane;

  ngOnInit() {
    this.bottomDrawer = new CupertinoPane(".cupertino-pane", {});
    this.bottomDrawer.present({ animate: true });
  }
}
`
6. serve (ng serve) or build for deployment (ng build --prod)

To simplify this i've also zipped up the solution (without node modules)
[cupertino-demo-nomaterial.zip](https://github.com/roman-rr/cupertino-pane/files/4866197/cupertino-demo-nomaterial.zip)

1. Unzip this then just run npm install in the extracted folder.

To remove stack-blitz from the equation I created a host for the application in Azure: https://cupertinodemo.z13.web.core.windows.net/ 

Same issue.

![Android-Emulator-pixel-3-xl-pie (1)](https://user-images.githubusercontent.com/67698243/86400511-bbbb5280-bc76-11ea-99d9-21702f9f8353.gif)

**Comment by dionsthilaire** [comment]
> @dionsthilaire
> The issue is in chrome mobile pull-to-refresh functionality. [Solution](https://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature)
> 
> **a)** Fix with css
> 
> ```css
> body {
>   overscroll-behavior-y: none;
> }
> ```
> 
> **b)** Set `touch-action: none` to content except pane, on drag events.
> **c)** Applying `overflow-y: hidden` to the body element always or while drag events.
> **d)** Disabling the effect locally via `chrome://flags/#disable-pull-to-refresh-effect`.
> 
> _Note: for mobile frameworks such as ionic issue fixed out of the box._

yes, actually this is what we used as a work-around to fix the issue. Just thought you would like to know that this bug existed :)
