### ISSUE TITLE
Bug in input focus on mobile

### ISSUE THREAD

**Issue by eduboxgithub** [roman-rr/cupertino-pane#49]
Hello,

when I click the input and then open the keyboard the view is pulled all the way up, then the view does not return to normal on blur. This event makes to lose the submit button on the header.

is possible to see in the following images.

[image 1](https://user-images.githubusercontent.com/13800439/87182549-4ab21580-c2dc-11ea-99fc-8260616afa09.jpg)
[image 2](https://user-images.githubusercontent.com/13800439/87182550-4b4aac00-c2dc-11ea-9cd8-e1a3b32792d5.jpg)
[image 3](https://user-images.githubusercontent.com/13800439/87182551-4b4aac00-c2dc-11ea-9bec-d3364fc90a12.jpg)

What can I do to fix this problem ?

**Comment by BerkeAras** [comment]
If you use capacitor or cordova the plugin ionic keyboard would stop pushing the content up

**Comment by roman-rr** [comment]
@eduboxgithub Please describe platform/browser/device

**Comment by eduboxgithub** [comment]
Hello @BerkeAras and @roman-rr.

I'm using Capacitor (latest version) and I'm testing on a Android device.
Already tested on a OnePlus 5T with Android 10, a Wiko with Android 7 and a Xiaomi A2 with custom ROM (LineageOS).

In all of them when a pane is rendered with an ion-input, when the native keyboard shows up (ion-input focus) the pane scrolling breaks and cant be restored...

This only happens on a device... because of the native keyboard.

If I try to block the content to be pushed up... probably I will be writing things in the input, but not seeing what is being written...

**Comment by BerkeAras** [comment]
@eduboxgithub Is the bug happening when you **dont use** `ion-input`?

**Comment by roman-rr** [comment]
@eduboxgithub please share your code and i will find optimal solution for this case.

**Comment by roman-rr** [comment]
@eduboxgithub Reproduced in my environment, looking for solution.

**Comment by roman-rr** [comment]
@eduboxgithub 
Quick solution
```js
if (this.platform.is('android')) {
  const pane = <HTMLElement>document.querySelector('.pane');
    window.addEventListener('keyboardWillHide', () => 
    window.requestAnimationFrame(() => (pane.style.display = 'none',
    window.requestAnimationFrame(() => pane.style.display = 'block'))));
}
```

**Comment by nbaleli-w** [comment]
I wonder if this can be achieved in a browser as well?
I currently have an input in the drawer and the virtual keyboard is hiding it -/

**Comment by roman-rr** [comment]
@nbaleli-w please describe your issue here https://github.com/roman-rr/cupertino-pane/issues/73
Seems like it's match.

**Comment by Nickholas** [comment]
Borried looking for a solution, i did this and works 100% on any device:

On .html:

<ion-item>
                    <ion-label position="floating">Días disponibles</ion-label>
                    <ion-input formControlName="dias" type="number" class="number-input" readonly='true' (ionFocus)="changeDiasDisponible()"></ion-input>
                </ion-item>

On .ts:
async changeDiasDisponible() {
    const alert = await this.alertController.create({
      header: 'Nº días disponibles',
      inputs: [
        {
          name: 'numdias',
          type: 'number',
          value: this.form.get('dias').value
        }
      ],
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
          cssClass: 'secondary'
        }, {
          text: 'Ok',
          handler: (data: any) => {
            this.form.get('dias').patchValue(data.numdias);
          }
        }
      ]
    });
    await alert.present();
  }

**Comment by alleneben** [comment]
Hello, when I focus in an input on android, style="overflow: hidden" is injected into my pages html tag. This prevents me from scrolling the page. 

How do I fix this.
