### ISSUE TITLE
[FEAT] Add changelog to README

### ISSUE THREAD

**Issue by BerkeAras** [roman-rr/cupertino-pane#50]
**What are you trying to add to Cupertino-Pane?**

Add changelog.md to readme.md

*Describe your feature request **detailed***

Add changelog.md to readme.md because it is not very good visible in the code.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[X] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X] No

**Comment by roman-rr** [comment]
@BerkeAras Thank you!

**Comment by BerkeAras** [comment]
You're welcome!
