### ISSUE TITLE
[BUG] How to Declare Safe Area for Iphone X and Above?

### ISSUE THREAD

**Issue by kartiksolanki** [roman-rr/cupertino-pane#54]
First of all, thank you for wonderful component. I am wondering, how do you declare safe-area-inset-bottom for this component for devices Iphone X and above?

**Comment by roman-rr** [comment]
Hello @kartiksolanki

This is an example function of how i do safe area calculations on ionic project
```js
get deviceOffset() {
    const sat = getComputedStyle(document.documentElement).getPropertyValue("--ion-safe-area-top");
    const sab = getComputedStyle(document.documentElement).getPropertyValue("--ion-safe-area-bottom");
    return parseFloat(sat.replace('px', '')) + parseFloat(sab.replace('px', ''));
}
```

Then I just add returned value to heights for breakpoints. 

```js
let settings = {
  ...
  breaks: {
    middle: {
      enabled: true,
      height: 300 + this.deviceOffset
    }
  }
}
```

**Comment by kartiksolanki** [comment]
Perfect! I have one more question:
I am using this component inside my ionic tab pages and when I keep the drawer open and navigate to other tab, and then when i navigate back to the drawer open tab, the drawer doest close on .destroy() method. I also tried destroying it in ionViewWillLeave() method but the drawer gets destroyed too but then i am not able to click on any fields inside that destroyed drawer tab. Any idea how can I resolve that issue? Thanks.

**Comment by roman-rr** [comment]
@kartiksolanki 
Seems like scope and variables definition issue. Please provide some code snippet or whole repo, i will check.

**Comment by kartiksolanki** [comment]
Nevermind, I was able to fix it but initializing Panes inside ngOnInit() instead of ionViewWillEnter(). Just want to confirm, if this is the right practice to init panes inside ngOnInit()? and if this pane is open while moving to other tab, I am destroying them in ionViewDidLeave() ?

**Comment by roman-rr** [comment]
`ionViewWillEnter` will executed each time you open page. That's why, you re-open page and you re-create pane again. Same with `ionViewDidLeave`, it calls each time you open other page. 

Best practice with angular is to present within `ngOnInit`. And destroy with `ngOnDestroy`. 
This methods are only once called, when page rendered/destroyed, not depend you go to other pages or not.
