### ISSUE TITLE
[BUG] IonMenu is swipable through backdrop

### ISSUE THREAD

**Issue by BerkeAras** [roman-rr/cupertino-pane#55]
**Describe the bug**
IonMenu is swipable through the Cupertino-Pane Backdrop

**To Reproduce**
Just create Ionic App with Menu and open Drawer.

**Expected behavior**
It should not be swipable.

**Comment by roman-rr** [comment]
@BerkeAras Thank you. I tried, but can't reproduce with both opened menu and drawer. 
Please share some code.

**Comment by BerkeAras** [comment]
@roman-rr [https://jsfiddle.net/umy4vn91/](https://jsfiddle.net/umy4vn91/)

**Comment by roman-rr** [comment]
@BerkeAras 

Please try this solution (Disable/Enable gesture)
```html
<ion-menu [swipeGesture]="swipeGesture">
```
 
And controller
```javascript
public swipeGesture:boolean = true;
constructor() {}

ngOnInit() {
    this.drawer = new CupertinoPane('.ion-drawer', {
      ...
      onWillPresent: () => this.swipeGesture = false,
      onDidDismiss: () => this.swipeGesture = true
    });
    this.drawer.present({animate: true});
}
```

**Comment by roman-rr** [comment]
@BerkeAras Already able `touchMoveStopPropagation` settings with the latest commit, and will be able in next release within 1 week. 
Simple set 
```
let settings = {
  ...
  touchMoveStopPropagation: true
}
```
To fix this issue.
