### ISSUE TITLE
[BUG] Horizontal Scroll inside flickers the pane and closes abnormally

### ISSUE THREAD

**Issue by everestkid** [roman-rr/cupertino-pane#57]
I have a horizontal scroll div inside the pane 

```
.horizontal {
overflow-x:auto,
white-space:nowrap
}
```

When I scroll the horizontal content, the pane flickers abnormally and sometimes closes if its at the bottom. 
Is there another way to add horizontal scroll inside the pane??

**Expected behavior**
It should scroll the content horizontally without affecting the pane.

**Comment by roman-rr** [comment]
@everestkid Thank you for issue!

For horizontal scroll cases I recommend to set drag angle equals 45.
`touchAngle: 45`

But if this is not solution for you, you can show me your code example and I will investigate into.

**Comment by everestkid** [comment]
It worked thank you very much.

**Comment by sasafister** [comment]
I tried this but it wont work. It works on web but not when I try on mobile. Any ideas?

[Imgur](https://imgur.com/8FRnXGU)

**Comment by roman-rr** [comment]
@sasafister Please create new issue. Specify mobile device / browser there and provide sources or at least video.
