### ISSUE TITLE
[Feature] Top -> Bottom and Horizontal directions

### ISSUE THREAD

**Issue by vesper8** [roman-rr/cupertino-pane#58]
I'm looking for a drawer that can be activated by swiping left-to-right at any time exactly like it works on the Twitter app. I'm not sure if your package is appropriate for this but it seems to be very well maintained and modern compared to other drawer packages so I would like your feedback on whether I should try to use your package to accomplish this or if it was not meant for this kind of "swipe-activated menu drawer".

I see that all your examples are bottom-to-top so I'm not sure. If it is appropriate then it would be lovely if you could add such an example to your demos.

Thanks for making this!

**Comment by roman-rr** [comment]
@vesper8 Thanks, scheduled!

**Comment by vesper8** [comment]
excellent @roman-rr ! thanks so much!

**Comment by marcofugaro** [comment]
looking at the `top-to-bottom` feature as well 👀

**Comment by roman-rr** [comment]
### Top-to-bottom 
Already available in `1.1.91`

### Horizontal directions 
Considered not make in near future. 
Need more users requests on, to create such a big changes for package.

**Comment by vesper8** [comment]
@roman-rr thanks for this enhancement.. however I never asked for top-to-bottom now that I look back at my request.. you're the one that changed my title.. all I really want is left-to-right / right-to-left.. that's what I need in my app.

Is it really such a big change to add?

Anyway I really hope you add it in the future.

**Comment by roman-rr** [comment]
@vesper8 I don't really see right now how pans can be used in sidemenu way.  
But let's wait For more requests.

**Comment by vesper8** [comment]
@roman-rr Would be nice if you left the feature request open though so others can vote on it : )

**Comment by roman-rr** [comment]
@vesper8 Honestly, i do not want to maintain "one more sidemenu". But if you provide some nice examples of UI/UX where pane can be used as horizontal mode, i will think toward the implementation.
