### ISSUE TITLE
Logo & Name

### ISSUE THREAD

**Issue by roman-rr** [roman-rr/cupertino-pane#59]
Welcome @EduardoLopes, thank you for respond 🎉
Let's discuss logo here. 
Project main functionality is a drawer panel. Currently it's a `bottom -> top` drag panel.
On couple of weeks we will release other directions like `top -> bottom` and `left -> right`. 

Why **cupertino** ? Kind of reference to apple styled UI, which flutter framework called as **cupertino**. 
And main drawer ideas was taken from similar panes in such applications as: Apple Stocks, Apple Music, Apple Maps, Asana, Google Maps.

**Comment by EduardoLopes** [comment]
Hey Roman, this is a cool lib.

I imagine the typography a little bit like this (this is a draft). "Cupertino" smaller than "pane", with "Cupertino" on top of "pane". 

![Artboard 1](https://user-images.githubusercontent.com/1084297/93110651-ffc1cf00-f68b-11ea-9859-9e2ab82213c2.png)

The pane will come from all four directions, right? i guess i have an idea on how to illustrate that in a logo. But i'll need a little bit more time to think about it and post a draft.

It's worth mention here too that i'm kinda busy these days, so it can take some time to respond. :)

**Comment by roman-rr** [comment]
@EduardoLopes i definitely like this font and also how you find a way to save space made it with 2 lines.

Yes, next plans is to make 4 directions.
However, the main directions will be `bottom -> top` and `top -> bottom`.

I don't sure horizontal directions will be widely using.

**Comment by EduardoLopes** [comment]
Hi Roman. Sorry it's taking too long. Anyways, i got some time to make a **draft** for the symbol i imagine for the logo.

![Artboard 1](https://user-images.githubusercontent.com/1084297/94331126-7a4df100-ffa0-11ea-9ded-40ecf788bb36.jpg)

The shapes on the sides represent the panes, top and bottom are bigger because it's much used. There's a lot of room to explore this concept, if you like it, i can try more ideas over the same concept.

**Comment by roman-rr** [comment]
Thank you @EduardoLopes 
We appreciate your efforts, no matter how long is it. 

About shapes - i like this idea. This is my thoughts:
- I think each top/bottom/left/right must be with same size to follow good visual proportions, but then need some way to reduce free space on center. 
- In other side, seems it can be good to increase bottom shape height in 2-3 times. It can reduce center free space and each side will have own size. Most usable side will be longer on shape. 
- Some way to get rid of borders ? Maybe inverse colors ? Not necessary but might be good.

**Comment by roman-rr** [comment]
@EduardoLopes I just look up once again and realize that here is "X" letter shape. Which i really like, maybe shape of logo can be played around "X". (Just another idea).

**Comment by BerkeAras** [comment]
@roman-rr Just a question for the logo: in which city/country do you live (or where did you code cupertino pane)?

**Comment by BerkeAras** [comment]
@roman-rr Not more needed

**Comment by BerkeAras** [comment]
What do you think about this logo?

Apple's headquarter in **Cupertino** is **round** - inspired by it.

**Comment by BerkeAras** [comment]
![logo](https://user-images.githubusercontent.com/36629890/95615212-2515e300-0a68-11eb-920a-7e953bb5e0c3.png)

**Comment by roman-rr** [comment]
@BerkeAras if you are have any suggestions about logo, welcome!

**Comment by BerkeAras** [comment]
in the light text you can see the 4 contributors

**Comment by BerkeAras** [comment]
@roman-rr What do you think about the Logo?

**Comment by roman-rr** [comment]
@BerkeAras Please wait for @EduardoLopes and make some suggestions for him various.

About logo you are provided: 
Text should be on the right from shape. Shape must no be circle (should symbolize panes shapes). Text in circle of contributors must be updated with new contributors (not a good way at all to use it).

**Comment by davayd** [comment]
![untitled](https://user-images.githubusercontent.com/17270614/96271879-18e4d500-0fd6-11eb-890d-6218a71f5918.png)

**Comment by davayd** [comment]
![untitled (1)](https://user-images.githubusercontent.com/17270614/96272012-39149400-0fd6-11eb-8e1e-4c89e4e365c0.png)

**Comment by omar2205** [comment]
![](https://i.imgur.com/aKbubog.png)

**Comment by roman-rr** [comment]
Maybe need a renaming also? To simple "Panes" ?

**Comment by roman-rr** [comment]
Not more actual
