### ISSUE TITLE
UI issues in Pane

### ISSUE THREAD

**Issue by Tommertom** [roman-rr/cupertino-pane#6]
HI

I am facing a number of UI issues in using the pane. 

See video:
https://github.com/Tommertom/svelte-ionic-app/blob/master/doc/TQDW3977.MP4?raw=true

There are at least three things happening:
- the pane content scrolls while dragging up, initially and then not anymore. This happens on iOS, but not chrome browser on Win10
- when changing the menu item (changing the parent content), the pane remains but becomes empty
- not shown in video: `Uncaught (in promise) TypeError: Cannot read property 'style' of undefined` in line `this.contentEl.style.overflowY = 'hidden';` of function move-to-break. This happens after closing the pane which was emptied (see bullet 2). 

Project: https://ionicsvelte.firebaseapp.com
Project Code: https://github.com/Tommertom/svelte-ionic-app
Pane code: https://github.com/Tommertom/svelte-ionic-app/blob/master/src/pages/ionic/Pane.svelte

**Comment by roman-rr** [comment]
@Tommertom 
Big thanks for your efforts!

1) Fixed this and other UI and touch events issues. Update package.
2) Svelte wipe the DOM of child pages, when you go to other page. So `.cupertino-content` element destroyed. But pane not rendered with svelte engine, and persist in DOM.

if you wish to place Cupertino Pane in all pages, you might place it out Svelte engine.
bottom lines of **App.svelte**
```html
...
  <div class="cupertino-pane">
    <div class="cupertino-header">
      <h1>Drag me up Test!</h1>
    </div>
  </div>
```

Another option is place Pane for demonstration only in one page.
Place element inside of `ion-content`:
```html
...
  <div class="cupertino-pane">
    <div class="cupertino-header">
      <h1>Drag me up Test!</h1>
    </div>
  </div>
</ion-content>
```

One more option - render pane content with js:
```javascript
onMount(() => {
    // Create alement
    let newElement = document.createElement('div');
    newElement.innerHTML = `
        <div class="cupertino-pane">
          <div class="cupertino-header">
            <h1>Drag me up!</h1>
          </div>
        </div>`;
    document.getElementsByTagName('ion-app')[0].appendChild(newElement);

    // Init pane
    var myPane = new CupertinoPane(
      ".cupertino-pane", // Pane container selector
      {
        onDrag: () => console.log("Drag event")
      }
    );
    myPane.present();
  });
```

Another option - confirm with Svelte community how to create resist for changes to specific DOM elements. 

### Hope it helps!

**Comment by Tommertom** [comment]
Hi @roman-rr 

THank you very much for the solution and detailed analysis. Will give it a try.

I am not looking to put the pane in App.svelte - although that could just be the solution if needed. I just notice the behaviour which you explained by the way svelte works.

I'd rather put the pane in ion-content per page, so the whole pane gets destroyed, but then a padding occurs on the pane (if I add padding to ion-content). 

WE'll be in touch

**Comment by roman-rr** [comment]
@Tommertom 
Please update npm package to `1.0.71` (did fixed left margin). 

Let's make it better with `scroll-y="false"`: 
```html
<ion-content padding scroll-y="false">
...
```

You can also improve demonstration offsets with `breaks`: 
```javascript
onMount(() => {
    var myPane = new CupertinoPane(
      ".cupertino-pane", // Pane container selector
      {
        onDrag: () => console.log("Drag event"),
        breaks: {
          top: { enabled: true, offset: -10},
          middle: { enabled: true, offset: 180},
          bottom: { enabled: true, offset: 140},
        }
      }
    );
    myPane.present();
  });
```

**Comment by Tommertom** [comment]
Ok. Deployed as such (without the scroll-y) and seems indeed much better.

Slowly we are getting there!

**Comment by Tommertom** [comment]
Personally I rather not have the dependency on scroll-y:false. I put it back as on iPhone 7S, the UI is not ok. The scrolling seems to bubble down from the pane to ion-content. Something you want to consider to resolve?

**Comment by roman-rr** [comment]
@Tommertom 
It is something how ionic gesture recognize any touch events to entry ion-content elements.

This is might be solutions:
1) Disable scroll for ion-content
2) Disable scroll for ion-content only when you drag pane
