### ISSUE TITLE
React-JS, useEffect to render and accessing drawer.present() from outside component

### ISSUE THREAD

**Issue by Gojira-san** [roman-rr/cupertino-pane#62]
Hey Roman, 

First of all, awesome project. Was really hard to find something like this outside react native.

We use react-js and are tryng to incorporate your pane in a fullscreen PWA to create a native experience.

However we ran in some issues with a design similar to apple stocks.

What is your advice on making a reusable component?

**For example:** 

On our page we have a cupertino pane component which initializes on render of the page with useEffect (else it gives the cannot find dom element error).

But we also want to have another pane which expands fullscreen (like apple stocks) when you click on a button on the page. However, we cannot acces the drawer.present() from outside the component (from the page its rendered in).

**So our main questions are:**

- Do we always need a useEffect per cupertino-pane to render (we have multiple)? Because for us it never works due DOM element not being available. 
- How do we trigger the present function from outside the component? 

Thnx!

```
function ParentPage () {

   function PresentDrawer () {
     // How do we call function drawer.present() here and pass as props?
   }

return (
   <>
     <Button onClick={PresentDrawer}

      // This pane auto initializes on render page due to use effect
     <BottomSheet className="pane1">Content</BottomSheet>

      // This pane needs to be triggered only on button click.
     <BottomSheet className="pane2"/>Content</BottomSheet>
   </>
  )
}

function BottomSheet(props) {

    useEffect(() => {
        const drawer = new CupertinoPane('.' + props.className, // Pane container selector
        {
            parentElement: '.App', // Parent container
            breaks: {
                middle: { enabled: true, height: 300, bounce: true },
                bottom: { enabled: true, height: 80 },
            },
            initialBreak: 'middle',
            pushMinHeight: 370,
        }
    );
        setTimeout(() => drawer.present({ animate: true }));
    }, [])

    return (
        <>
            <div className={props.className}>
                {props.children}
            </div>
        </>
    )
}
```

**Comment by roman-rr** [comment]
Hey @Gojira-san thank you for issue!
If i correctly understand you will need somethings like this: 

```html
<parent-element>
  ...
  <bottom-drawer-1></bottom-drawer-1>
  <bottom-drawer-2></bottom-drawer-2>
</parent-element>
```

Then, best way is to initialize and control pane inside `<parent-element></parent-element>`
But yes, we need panes rendered in DOM to initialize panes.

I believe that reactjs has some methods to send callbacks from child elements into parent element ? 
Good to send render callbacks into parent element and then initialize pane on parent.

**Comment by roman-rr** [comment]
@Gojira-san Detail clarifications of how to do it properly 
https://stackoverflow.com/questions/38394015/how-to-pass-data-from-child-component-to-its-parent-in-reactjs

**Comment by brunoAltinet** [comment]
This question is one of the top answers for cupertino pane react, so here's a starting point for someone, I use this one in Ionic and it works fine:
