### ISSUE TITLE
[BUG] Performance drop when drag happens on a overflow area

### ISSUE THREAD

**Issue by hatsantos** [roman-rr/cupertino-pane#63]
**Describe the bug**
When we do a drag/swipe in the header the performance seems really good, but if there's a scrollable section in the content and we try to drag/swipe the panel using that area the performance takes a big hit!

The performance also breaks in desktop (not so noticeable as in a mobile device).

**To Reproduce**
1) Add a header
2) Add content with overflow (that will have an additional scroll)
3) drag pane using the top header (no problem in performance)
4) drag the pane using the content area (slow motion activated =).

**Expected behavior**
The performance should not be affected if we drag/swipe the scrollable/overflow area.

**Screenshots**
I uploaded a video do show the behaviour:

https://streamable.com/z8saji

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85.0.4183.102

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 10
 - Browser Capacitor App (webview version)

**Comment by roman-rr** [comment]
Hello @hatsantos thank you for details. 
Seems that [chromium throttle issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1123304) still relevant for some cases, which should be fixed by chrome devs soon.
I will check for quick patch in our side.

**Comment by roman-rr** [comment]
@hatsantos please try `1.1.83`

**Comment by eduboxgithub** [comment]
@roman-rr thank you, for the quick fix!
I update the dependencies to 1.1.83 and I tested a new build.

I can't see the performance drop anymore. =D
