### ISSUE TITLE
Can you drag the drawer all the way up to occupy the entire screen?

### ISSUE THREAD

**Issue by rickyh2007** [roman-rr/cupertino-pane#66]
Just a question. I tried different settings, but didn't seem to be able to do that.

Also can an absolute position content sit on top of the drawer pane?

**Comment by rickyh2007** [comment]
I figured out by setting the top break height to be the screen height (window.innerHeight).

However, I'm still not able to figure out how to make an absolute div content to show on top of the pane. Tried z-index, didn't seem to work. Is it even possible?

**Comment by roman-rr** [comment]
@rickyh2007 Play with `parentElement` configuration. I guess your absolute content placed on container with lowest z-index than pane parentElement. 
If you can't find solution, provide sources and i will dig deeper.

**Comment by roman-rr** [comment]
@rickyh2007 Closed for inactivity
