### ISSUE TITLE
[BUG] Slow animations on Android

### ISSUE THREAD

**Issue by SumailaBello** [roman-rr/cupertino-pane#67]
Great job on the pane so far but there seems to be an issue on my ionic 4/5 apps where the pane animates rather slowly and skips a lot of frames.

1. Create a starter app on a real Android device
2. Install this package and use as usual.
3. Ensure the app is built into an apk and installed on a real Android device running latest chrome browser and using Chrome webview.
4. Drag the pane to expand or collapse to see the slow animations
**Expected behavior**
It used to animate very smoothly while sliding the pane up and down previously, so this is probably due to a recent update to Chrome.

**Comment by roman-rr** [comment]
Thank you for report @SumailaBello 
What pane version are you using ?

**Comment by SumailaBello** [comment]
> Thank you for report @SumailaBello
> What pane version are you using ?

Ok I just updated to the latest version now and the problem seem to be solved plus it seems to be faster now 😁. Great job 👏🏾
