### ISSUE TITLE
Control Dark Mode after initialization

### ISSUE THREAD

**Issue by ibrahimawadhamid** [roman-rr/cupertino-pane#68]
I'm trying to control the dark mode after initialization.

A public method needs to be implemented like this:

setDarkMode({darkMode: boolean = false})

**Comment by ibrahimawadhamid** [comment]
@roman-rr I see that you already did some work on this! that's great, please let me know when the changes are live.

**Comment by roman-rr** [comment]
@ibrahimawadhamid will be available on next release
