### ISSUE TITLE
[Feature] Changing Breakpoints After Initialization

### ISSUE THREAD

**Issue by akharag** [roman-rr/cupertino-pane#69]
**What are you trying to add to Cupertino-Pane?**
The ability to change breakpoints after the cupertino-pane has been created.
*Describe your feature request **detailed***
Sometimes there are different contexts, where after the cupertino-pane has been created, that a person would want to change the breakpoints without having to close and reinitialize a new cupertino-pane. A possible example is changing the top breakpoint based on an option that the user sets by pushing a button. Creating a method that could update the breakpoints, later on, would be helpful to streamline many apps.
**Is there an alternative at the latest version?**

[ ] Yes (describe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
@akharag Will be available on next release `1.1.9`
