### ISSUE TITLE
[BUG] CDN script lacks the CommonJS converter snippet

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#70]
**Describe the bug**
Loading the script from CDN fails with error: `exports is not defined` because the CommonJS snippet is missing. I'm referring to this snippet which should wrap the code of the lib. Something like:
```
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (global = global || self, factory(global.CupertinoPane = {}));
  }(this, (function (exports) { 'use strict';
  ...
  })));
```

**To Reproduce**
Load the script from the CDN and you'll get `exports is not defined` in the browser console

**Smartphone (please complete the following information):**
 - Device: Tecno Spark
 - OS: Android 8
 - Browser: Chrome Webview
 - Version: 85

**Comment by roman-rr** [comment]
Hey @CodeWithOz 
I will review once again if this part already fixed by latest `rollup`. 

But now, please try to add line before your import
```html
<script>var exports = {"__esModule": true};</script> <!-- Required if exports not defined earlier -->
<script src="https://unpkg.com/cupertino-pane/dist/cupertino-pane.min.js"></script>
```

Let me know if it doesn't works or you have better solution.

**Comment by CodeWithOz** [comment]
@roman-rr thanks I'll try that now and give feedback. I initially tried using the snippet I posted above but it meant that I had to do `new CupertinoPane.CupertinoPane()`.

**Comment by CodeWithOz** [comment]
Yeah your suggestion works, thanks!
