### ISSUE TITLE
[FEAT] get event details inside the callbacks

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#71]
**What are you trying to add to Cupertino-Pane?**
I want to get the details of the associated events in the callbacks.

*Describe your feature request **detailed***
For instance I want to be able to use `event.target` inside `onTransitionEnd` and `onDidDismiss`. Even if it's not `event.target`, at least something like `event.pane` where `pane` is the `CupertinoPane` instance for the pane that received the event.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[x] No - I'm not aware of an alternative. Is there a way to do this currently?

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
@CodeWithOz 
Pane isn't accessible after `onDidDismiss`, it is destroy calllback. 
Added target to `onTransitionEnd`. Note that if transition end after destroy, target also will not be accessible.

**Comment by CodeWithOz** [comment]
Amazing with the quick response! Thanks. :+1:

**Comment by roman-rr** [comment]
BTW: Will be able on next release

**Comment by CodeWithOz** [comment]
Thanks, when can I expect that release?

**Comment by roman-rr** [comment]
> Thanks, when can I expect that release?

After 1-2 weeks. The last feature I gonna to make before release it is top-bottom direction.
