### ISSUE TITLE
Disable Downward Drag When at Bottom Position

### ISSUE THREAD

**Issue by jwburnside** [roman-rr/cupertino-pane#72]
**What are you trying to add to Cupertino-Pane?**
Flag to disable downward drag if at a bottom position.

*Describe your feature request **detailed***
Great plugin!

I went through the documentation pretty thoroughly, and did some rounds of trial and error, but I can't seem to figure out how to prevent the pane from dragging if it is at a bottom position. Currently it allows a downward drag, then bounces back into position. I believe I can listen for the drag event and stop the downward drag manually, but it would be nice if this was a feature.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[x ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x ] No

**Comment by roman-rr** [comment]
Hey @jwburnside ✋
Did you try `lowerThanBottom: false` ?

**Comment by jwburnside** [comment]
@roman-rr I seem to have overlooked that in the docs, but I'm getting some undesired results when I try that flag. It seems to allow me to drag downward, then the pane disappears. It may be something on my end, however, I'll experiment with it, thanks.

**Comment by roman-rr** [comment]
@jwburnside i just found that `lowerThanBottom` currently works for `freeMode` only. 
Please try 
```javascript
{
  freeMode: true,
  lowerThanBottom: false
}
```

Is that expected behavior ? Do you need this feature for `freeMode: false` also ?

**Comment by jwburnside** [comment]
Yes, support for freemode: false would be very helpful. I have a scenario where I need a defined bottom position (around 300px) and a defined top position (full screen), but I don't want the bottom to be draggable downwards.

Appreciate the help again!

**Comment by roman-rr** [comment]
@jwburnside will be works as you need on `1.1.9` release;
If you would like to implement right now, install package from `master` branch version.

**Comment by jwburnside** [comment]
Ok, thanks I'll give it a try and let you know!
