### ISSUE TITLE
Pane Breaks when Upgrading (1.1.64 -> 1.1.9)

### ISSUE THREAD

**Issue by jwburnside** [roman-rr/cupertino-pane#74]
**Describe the bug**
I seem to be experiencing a few issues when upgrading 1.1.64 to 1.1.9. 

The earlier version seems to work as intended when using the example as provided in the docs. 

When I upgrade to 1.1.9, however, and move the pane from break to break, it begins throwing console errors and eventually stops respecting the defined positions. 

The error I'm getting is as follows: 

`TypeError: Cannot read property 'enabled' of undefined
    at CupertinoPane.swipeNextPoint (:8100/default~in-progress-ride-in-progress-ride-module~pages-create-ride-create-ride-map-create-ride-map-module.js:288)
    at CupertinoPane.touchEnd (:8100/default~in-progress-ride-in-progress-ride-module~pages-create-ride-create-ride-map-create-ride-map-module.js:791)
    at HTMLDivElement.CupertinoPane.touchEndCb (:8100/default~in-progress-ride-in-progress-ride-module~pages-create-ride-create-ride-map-create-ride-map-module.js:243)
    at HTMLDivElement.__trace__ (:8100/vendor.js:100759)`

My specs are as follow: 
Ionic Framework : @ionic/angular 5.1.1
Android Pixel 3a, OS v29

**Expected behavior**
The pane should not throw any console errors, and respect the defined positions.

The code I'm using:

```
import { AfterViewInit, Component } from '@angular/core';
import { CupertinoPane } from 'cupertino-pane';

@Component({
  selector: 'app-create-ride-map',
  templateUrl: './create-ride-map.page.html',
  styleUrls: ['./create-ride-map.page.scss']
})
export class CreateRideMapPage implements AfterViewInit {
  ngAfterViewInit(): void {
    const cupertinoPane = new CupertinoPane('.cupertino-pane', {
      breaks: {
        middle: { enabled: true, height: 300 },
        bottom: { enabled: true, height: 80 }
      },
      onDrag: () => console.log('Drag event')
    });
    cupertinoPane.present({ animate: true });
  }
}
```

```
<ion-content>
  <div class="cupertino-pane">
    <div class="content">
      <br />
      test
      <br />
      <br />

      <br />
      test
      <br />
    </div>
  </div>
</ion-content>
```

**Comment by roman-rr** [comment]
@jwburnside Please update to ‘1.1.91’. Issue already fixed

**Comment by jwburnside** [comment]
Ok upgraded to 1.1.91 and seems to be working now!
