### ISSUE TITLE
Unexpected behavior related to how spacing is assigned inside of the pane [BUG]

### ISSUE THREAD

**Issue by akharag** [roman-rr/cupertino-pane#75]
**Describe the bug**

The cupertino-pane has much more room under where the content inside of the pane resides. There is no way to get the content to extend to the bottom of the pane. Tryin to extend the div, etc. beyond 100% height only makes the div, etc. scrollable. Tested with div, ion-slides, and ion-content.

**To Reproduce**
<style>
.cupertino-pane {
  backgrounf-color= yellow;
}
.myDiv {
  height=100%;
  background-color= blue;
}
</style>
<div class="cupertino-pane">
   <div class="myDiv"></div>
</div>

**Expected behavior**

The div, etc. should cover all the yellow space when height=100%. Refer to the screenshots below. 

**Screenshots**

ion-slides
![Screen Shot 2020-10-14 at 8 24 36 PM](https://user-images.githubusercontent.com/22301549/96026553-51ae6e00-0e5f-11eb-9bbd-2a66e13b16ee.png)

div (can reduce the height to less than 100% to make the area not scrollable, also occurs on inverse=false, but content starts at top instead of in middle)
![Screen Shot 2020-10-14 at 8 26 53 PM](https://user-images.githubusercontent.com/22301549/96026560-5410c800-0e5f-11eb-88c6-2704ff3d36c1.png)

ion-content (always makes a scrollable area even without specifying height)
![Screen Shot 2020-10-14 at 9 01 16 PM](https://user-images.githubusercontent.com/22301549/96027383-79520600-0e60-11eb-9b06-768a3aa3d25b.png)

**Desktop (please complete the following information):**
 - OS: ionic serve
 - Browser: chrome
 - Version 86.0.4240.75

**Additional context**
Adding flex to a child div will allow the screen to take up the whole pane if the height is over 100%, but will make it scrollable.

**Comment by roman-rr** [comment]
@akharag Should be fixed in `1.1.92` and padding removed, please check.
