### ISSUE TITLE
[BUG] ion-range not working inside pane

### ISSUE THREAD

**Issue by davayd** [roman-rr/cupertino-pane#77]
**Describe the bug**
<ion-range> not working inside pane

**To Reproduce**
1. Go to https://stackblitz.com/edit/ionic-angular-v5-cvaevs?file=src/app/app.component.html
2. Click on button "open pane"
3. Try to change (click on circle then try move it on right/left direction) range inside pane

**Expected behavior**
Range inside a pane can interact with touch events.

**Desktop (please complete the following information):**
 - OS: [emulator 10.0 (Q) - API 29]
 - Browser [Cordova WebView]

**Comment by roman-rr** [comment]
Thank you for issue @davayd 
Bug reported [here](https://github.com/ionic-team/ionic-framework/issues/22335)

**Comment by roman-rr** [comment]
Closed, as it not `Cupertino Pane` bug and reproducible without Pane. 
https://output.jsbin.com/xufazic

@davayd Please write in issue to ping ionic-framework developers [here](https://github.com/ionic-team/ionic-framework/issues/22335)
