### ISSUE TITLE
[FEAT] dismiss based on hard back button

### ISSUE THREAD

**Issue by sohep** [roman-rr/cupertino-pane#79]
**What are you trying to add to Cupertino-Pane?**
I would like to be able to dismiss the pane based on hard back button.

*Describe your feature request **detailed***

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
Hello @sohep thank you for issue!
Have you try simply handle it on your side ? 
```javascript
document.addEventListener('backbutton', function(){
  pane.destroy({animate: true});
}, false);
```

**Comment by sohep** [comment]
@roman-rr thanks for your respone.
it works well, thanks.
i think it will be usefull to have a boolean option for it in the pane settings such "backbuttonClose"
 :)

**Comment by roman-rr** [comment]
I will add this feature if there are some more requests will appears from users. For now please handle on your side.
