### ISSUE TITLE
[BUG] Keyboard resize behavior

### ISSUE THREAD

**Issue by EinfachHans** [roman-rr/cupertino-pane#80]
I have a Pane with a Textarea in it. In it smallest breakpoint it is smaller than the keyboard height. Focusing this cause a Keyboard resize (of course lol).
The resize behavior is not working.

- Android: View is getting resized somehow, but kinda breaks. I have a black bar at the top and the **<ion-fab>** which is positioned absolute is displayed at the top, so it's relative container is kinda shrinked over the pane? (Screenshot attached)

- iOS: The Pane does not resize at all, i think because it is `fixed`.

**Expected behavior**

On both Platforms the Pane should be adjusted to be displayed over the keyboard (like android) but without being buggy.

**Screenshots**

Android:
<img src="https://user-images.githubusercontent.com/20899975/97556326-9ac2fe00-19d9-11eb-8c65-ba541768e431.jpg" width="400">

**Smartphone (please complete the following information):**
 - Device: S8 / iPhone 11 Pro
 - OS: Android 9 / iOS 14.1

**Comment by EinfachHans** [comment]
Any Updates on this? Wuite important for us

**Comment by roman-rr** [comment]
@EinfachHans I have plan to handle this issue within one week. 
Until that, you can handle it manually with `moveToHeight()` method on focus/blur input.

**Comment by EinfachHans** [comment]
If i should test anything here, feel free to provide a dev build to me 😊

**Comment by roman-rr** [comment]
@EinfachHans Let's confirm scenario's. 

### Chrome/Safari/WkWebView/WebView
We don't have keyboard callbacks such as close/open. 
User's must use input focus/blur callback's to handle keyboard. 
On focus -> `moveToBreak('top')` or on focus -> `moveToHeight(current + keyboardHeight)`

### Cordova apps
By default no callbacks, we using method above

### Cordova/Capacitor apps with keyboard plugin
Here we have listeners 
```
document.addEventListener('keyboardWillHide', onKeyboardHide, false);
document.addEventListener('keyboardWillShow', onKeyboardShow, false);
```
And we can push keyboard from our side to keyboard height. Also, create new option `pushOnKeyboard: true` by default. 

Something more ?

**Comment by EinfachHans** [comment]
Yeah, would be great, i'm using Cordova + [this Plugin](https://github.com/ionic-team/cordova-plugin-ionic-keyboard#events).

Also i would prefer to move via `moveToHeight(current + keyboardHeight)` as it should also work if i have only one break, that is placed very low 🤔

**Comment by blahblehblah** [comment]
Ah, as much as i was happy finding this plugin, but this is kind of a stopper, once the keyboard opens, it should push  the input above or something, i must drag the modal for it to show

**Comment by EinfachHans** [comment]
@blahblehblah we are discussing how to solve this in the project, BUT everything we are discussing right now is possible to handle app side too. Listen for Keyboard events and move the pane to whatever height yoh want.

**Comment by blahblehblah** [comment]
> @blahblehblah we are discussing how to solve this in the project, BUT everything we are discussing right now is possible to handle app side too. Listen for Keyboard events and move the pane to whatever height yoh want.

I actually did, still focusing on inputs especially the ones on the very bottom are somewhat not cool, however i managed to do a little hack by adding an extra margin bottom to the last element on keyboard showing, thought there would be better idea's

**Comment by blahblehblah** [comment]
Issue with input focusing; it doesn't scroll into its view, tried applying ionFocus and scrolling into it manually; weird behavior happens with the scroll of the list

**Comment by roman-rr** [comment]
@blahblehblah please provide video or code samples

**Comment by roman-rr** [comment]
Implemented simple handling for `cordova/capacitor/phonegap/ionic` apps in `1.1.94`
https://github.com/roman-rr/cupertino-pane#keyboard-issues
If you found a bags, feel free to create new issues.

**Comment by EinfachHans** [comment]
@roman-rr as i said the possibility to define what happens on keyboard push would be better, as now the pane gets pushed so high that is higher than the screen 🤔

**Comment by roman-rr** [comment]
> @roman-rr as i said the possibility to define what happens on keyboard push would be better, as now the pane gets pushed so high that is higher than the screen 🤔

@EinfachHans 
Please check version from master branch. There maximum pushed position is top breakpoint. Is that better ?

**Comment by EinfachHans** [comment]
@roman-rr nope doesn't work for me

**Comment by roman-rr** [comment]
@EinfachHans 
> @roman-rr nope doesn't work for me

Ok please make new issue with some video
