### ISSUE TITLE
Toggle pane in Angular 10

### ISSUE THREAD

**Issue by ejirocodes** [roman-rr/cupertino-pane#81]
Unable to toggle pane in angular project

**Comment by roman-rr** [comment]
@ejirocodes Maybe this example make sense for you https://github.com/roman-rr/cupertino-pane/issues/8

**Comment by ejirocodes** [comment]
@roman-rr I've done all of that and it's working fine. What I want to achieve is to hide the panel on click of a button inside of the panel itself and show another panel. The .hide and destroy methods are not working. I have attached the methods below

![code1](https://user-images.githubusercontent.com/45228014/98255146-63c28e80-1f7d-11eb-8fd1-143e4e91ee82.png)
![code](https://user-images.githubusercontent.com/45228014/98255151-64f3bb80-1f7d-11eb-9a6a-b6f213b4c497.png)

**Comment by roman-rr** [comment]
@ejirocodes it's a bit missunderstanding of scope variables in angular, typescript and ecma. 

This is proper way: 
```javascript
private myPane: CupertinoPane;
constructor() {
...
}

ngOnInit() {
  this.myPane = this.handleRateSheet();
  this.myPane.present({animate: true});
}

submitReview() {
  this.myPane.destroy({animate: true});
}

handleRateSheet() {
  let settings: CupertinoSettings = { ... };
  let myPane = new CupertinoPane('.rider-rate-sheet', settings) ;
  return myPane;
}
```

**Comment by ejirocodes** [comment]
Thanks, man. It worked like magic
