### ISSUE TITLE
[FEAT] - Prevent from closing

### ISSUE THREAD

**Issue by Pacn91** [roman-rr/cupertino-pane#82]
Hi, 
Maybe there is an option to my request but I really couldn't find one.

It occurred to me, more than once, I wanted to disable the option to close the drawer until the user do 'some action'.
Would be nice if there was an option to prevent the drawer to close.

Maybe on 'onWillDismiss' we could call something to stop the closing action, for example.

Thanks in advance.

Best regards

**Comment by roman-rr** [comment]
Hello @Pacn91 thank you for issue. I don't clear understand your request, please describe scenarios more detailed. 
What is this situation where user already call `.destroy()` method, but not want to destroy pane ?

**Comment by Pacn91** [comment]
Hi @roman-rr,
Thanks for the fast response.

What I was trying to say (sorry about my English xD) is for example: I want the user to open a drawer and select something. If he doesn't do that then he cannot close the drawer (by drag down or tapping the backdrop) until he selects something.

Imagine this:
**The user have to select a connection. If he doesn't do that, then he can not close the drawer.**
![drawer](https://user-images.githubusercontent.com/17788348/98276638-2c101280-1f8e-11eb-9f45-cf0b5ae86d9a.png)

Thanks again :)

**Comment by EinfachHans** [comment]
Guess something like https://github.com/ionic-team/ionic-framework/issues/22297

**Comment by roman-rr** [comment]
@EinfachHans Thank you, good example. This issue also i plan to handle within next week. And sure, we need similar feature.

**Comment by roman-rr** [comment]
Implemented in `v.1.1.94`. 
Check readme for `preventDismiss()` method. 
[Live example here](https://output.jsbin.com/keravam)

**Comment by EinfachHans** [comment]
@roman-rr i would like this more if the drag gesture is not possible to drag to bottom completly if a handler is set - check my ionic pr 🤔

**Comment by roman-rr** [comment]
@EinfachHans Seems that all what you need just set `onDrag` callback and show alert in some exact transformY position.

**Comment by Pacn91** [comment]
Thank you very much @roman-rr :)

**Comment by EinfachHans** [comment]
@roman-rr i think it should cause some changed gesture then, not just start onDrag. See the Video of how it is in a native modal in the mentioned ionic issue

**Comment by EinfachHans** [comment]
@roman-rr i think the answer in the ionic issue was supposed to be here 😃 i will open a new FR
