### ISSUE TITLE
Set a fixed height for pane?

### ISSUE THREAD

**Issue by ejirocodes** [roman-rr/cupertino-pane#83]
How do I make a pane have a fixed height say 300px

**Comment by EinfachHans** [comment]
If you read the *readme*:
https://github.com/roman-rr/cupertino-pane#breakpoints

You can for example disable the `bottom` and the `top` breakpoint and give the `middle` one the height you need

**Comment by roman-rr** [comment]
Thank you @EinfachHans, all right! Can also make free mode or disable `lowerThanBottom` to better effect of fixed position.

@ejirocodes  And if you want to set height for presented pane you can try `.moveToHeight()` method.

**Comment by ejirocodes** [comment]
> If you read the *readme*:
> https://github.com/roman-rr/cupertino-pane#breakpoints
> 
> You can for example disable the `bottom` and the `top` breakpoint and give the `middle` one the height you need

Got it. Thanks man
