### ISSUE TITLE
Drag pane to bottom to close 

### ISSUE THREAD

**Issue by ejirocodes** [roman-rr/cupertino-pane#84]
How do allow users to close pane by dragging to button?

**Comment by roman-rr** [comment]
> How do allow users to close pane by dragging to button? 

Try to set `bottomClose: true` option, and define and bottom breakpoint.

**Comment by ejirocodes** [comment]
Let me try it out.
Thanks

**Comment by rgoldiez** [comment]
@roman-rr when `bottomClose: true` ... should the background fade away and be hidden as well?

**Comment by roman-rr** [comment]
@rgoldiez `bottomClose: true` should destroy pane, wrapper and backdrop (if exist) when you reach bottom breakpoint.

**Comment by rgoldiez** [comment]
@roman-rr Thanks for the fast reply!  I'm not seeing that behavior but let me see if it's something wrong on my end.

**Comment by rgoldiez** [comment]
@roman-rr - If I want `onBackdropTap` to animate the panel to the bottom and then fire `onDidDismiss` ... how would you set that up?  It seems that `moveToBreak()` does not return a promise.  

Let me know if you'd like me to open up a new issue for this.

**Comment by roman-rr** [comment]
@rgoldiez Maybe just a this `onBackdropTap: () => pane.destroy({animate: true})` ? I will be dismissed and animated with bottom transition. I can transform moveToBreak to promise like async function also. 

If this tip doesn't work, please create new issue.

**Comment by rgoldiez** [comment]
@roman-rr - this is great.  Thank you.

**Comment by brunoborta** [comment]
I have `bottomClose: true` and I can already close swiping down. Although, I want to add a callback just for the swipe action. Is it possible?

**Comment by roman-rr** [comment]
Hi @brunoborta 
Probably you need `bottomClose: true` and `fastSwipeClose: true`

**Comment by brunoborta** [comment]
Hey @roman-rr, thanks for the quick reply. Maybe I'm missing something, but I still can't see a callback to the swiping motion. Could you please be more specific? Thank you for your time!

**Comment by roman-rr** [comment]
@brunoborta This callback currently exist https://github.com/roman-rr/cupertino-pane#callbacks
Aren't any of them satisfied your needs ?

**Comment by brunoborta** [comment]
I was just asking if there was a swipe close callback, that's all. If there's a way to take it without calculating the height of `onDragEnd` is below the bottom breakpoint.

**Comment by roman-rr** [comment]
@brunoborta have you try `onWillDismiss` ?

**Comment by brunoborta** [comment]
`onWillDismiss` triggers for every single way I closed the pane. So if I close the pane through a button, it will trigger `onWillDismiss` and `onDidDismiss`, so I can't differentiate the swipe one from the close button one.

**Comment by roman-rr** [comment]
@brunoborta Then you must try `onDidDismiss` callback. If you close within close button, callback will return event 
```
destroyButton: true
``` 
If still doesn't satisfied your needs, please create a issue as feature request.
