### ISSUE TITLE
[BUG] Keyboard with overflow list inputs

### ISSUE THREAD

**Issue by blahblehblah** [roman-rr/cupertino-pane#85]
Testing on android for now;

Kindly check the video; input hides behind keyboard, can't see it

Video > https://streamable.com/yx5jgx

**Comment by roman-rr** [comment]
@blahblehblah Thank you, i got it. This is browser or cordova webview ?

**Comment by blahblehblah** [comment]
Tested it on device and simulator, cordova.

**Comment by roman-rr** [comment]
@blahblehblah please check latest push from master branch and give me your feedback 
```json
"cupertino-pane": "git+https://github.com/roman-rr/cupertino-pane.git"
```

**Comment by blahblehblah** [comment]
Awesome work, does the job, thank you
