### ISSUE TITLE
[BUG] Keyboard resize-behavior

### ISSUE THREAD

**Issue by EinfachHans** [roman-rr/cupertino-pane#86]
**Describe the bug**
See #80 

**Expected behavior**
Move the Pane to top Breakpoint

**Screenshots**

Video: https://gofile.io/d/G9kaV0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Version: master

**Comment by roman-rr** [comment]
@EinfachHans Only android relative ?

**Comment by EinfachHans** [comment]
good question - let me check 😃

**Comment by EinfachHans** [comment]
Yes iOS works fine. It may be related to the different ways of how the screen gets resized 🤔

**Comment by EinfachHans** [comment]
On Android it some kind of worked before, but the problem there was the black bar and the moving of the fab button somehow? See #80 - maybe it is better to try to fix this

**Comment by EinfachHans** [comment]
@roman-rr anything i can do here to help you? Is quite important for me as i currently have a strict timeline of the app

**Comment by roman-rr** [comment]
@EinfachHans I will switch to keyboard issues, but you please help [here](https://github.com/roman-rr/cupertino-pane/issues/90)

**Comment by roman-rr** [comment]
Hey @EinfachHans 
Please check master branch version on your app.

**Comment by EinfachHans** [comment]
@roman-rr just checked. The Pane gets pushed to high and is over the top screen 🤔

**Comment by roman-rr** [comment]
@EinfachHans try to clean platforms, node_modules, and re-build app. Try with android emulator and device both. 
If still not works, please create a repo where i can try.

**Comment by EinfachHans** [comment]
I did this of course, here is a Repo which cause this for me also: https://github.com/EinfachHans/cupertino-resize

**Comment by EinfachHans** [comment]
btw i get the error: `undefined is not an object (evaluating 'this.settings.simulateTouch')` now when i install from master when i try to call the constructor - i removed the check from `.js` file in repo to make it work

**Comment by roman-rr** [comment]
@EinfachHans Let's confirm, that bug is "view resizing" after keyboard shown ? 
[Android_Pixel_API_30.mov.zip](https://github.com/roman-rr/cupertino-pane/files/5583686/API_30.mov.zip)

**Comment by EinfachHans** [comment]
Can you test on a real Device? I test in Samsung S8 - doesn't work there

**Comment by roman-rr** [comment]
@EinfachHans i don't have any real device with android. Unfortunately, i will need to get one. if nobody will help's us here.

**Comment by EinfachHans** [comment]
How can i help to give you more information with my device?

**Comment by roman-rr** [comment]
@EinfachHans The only ways for you: 
1. Make fork and explore `events.ts`, where keyboard show/hide events appears. Play with timeouts and this code snippet: 
```javascript
if (this.device.android) {
      this.fixAndroidResize();
}    
```

2. Await ~ one week while i'm get Android to debug.

**Comment by EinfachHans** [comment]
@roman-rr i will try to look into this, but i dont know if playing around with timeouts is a great solution to detect the error - may result in waiting for your android device 😕 what about the "simulateTouch" Problem? 🤔

**Comment by roman-rr** [comment]
@EinfachHans `simulateTouch` should be solved i pushed commit few hours ago.

**Comment by EinfachHans** [comment]
btw: Just noticed, that for iOS it is going over the top Breakpoint

**Comment by omar2205** [comment]
https://i.imgur.com/hiqLSm5.mp4

**Comment by roman-rr** [comment]
@omar2205 Thank you. Wait for awhile i will get Android to debug.

**Comment by EinfachHans** [comment]
@roman-rr how is it going? Do you have your android device? Our app needs to go live this year (for some reasons) and this is currently some kind of a showstopper 😕

**Comment by roman-rr** [comment]
Hey @EinfachHans I still doesn't get any real device with Android, but still plan to do it in near time.

**Comment by roman-rr** [comment]
Has gained Android device.

**Comment by roman-rr** [comment]
@EinfachHans Please try latest commit

**Comment by roman-rr** [comment]
Also, found that it is ionic issue in common, and i created [issue in ionic repository](https://github.com/ionic-team/ionic-framework/issues/22664), because of current patch is type of hack. And good if ionic developers can provide solution.

**Comment by roman-rr** [comment]
@EinfachHans Alternatively, you can try now how `handleKeyboard` option works with both `false/true` for Android in your app and decide what works better in your case.

**Comment by omar2205** [comment]
@roman-rr The latest version fixed this issue (https://i.imgur.com/hiqLSm5.mp4)
Thanks

**Comment by omar2205** [comment]
Still same error
https://i.imgur.com/wdegmEn.mp4

**Comment by roman-rr** [comment]
@omar2205 Create new issue, provide some sources. Seems that one pane properly resized, buy for few panes keyboard close not triggered.
