### ISSUE TITLE
[FEAT] prevent dismiss changes

### ISSUE THREAD

**Issue by EinfachHans** [roman-rr/cupertino-pane#87]
**What are you trying to add to Cupertino-Pane?**

*Describe your feature request **detailed***

I would like to have some changes in the newly created logic from #82 
- I think it is better to handle this like i did in my PR to this [Ionic Issue](https://github.com/ionic-team/ionic-framework/issues/22297): [My PR](https://github.com/ionic-team/ionic-framework/pull/22308) by adding a Methode to the Drawer Options that has type of () => `boolean | Promise<boolean>`
- Gesture: The Gesture should change if this methode is set, to match the native modal style (see video in ionic issue) - slower drag
- If the drag is executed enough or released above some fixed value, the method should be executed and the pane only dismisses if the value is **true** or the promise resolves **true**

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[X] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X] No

**Comment by roman-rr** [comment]
https://github.com/roman-rr/cupertino-pane#preventdismissboolean--false
