### ISSUE TITLE
[FEAT] Multiple panes in same screen 

### ISSUE THREAD

**Issue by akharag** [roman-rr/cupertino-pane#90]
**What are you trying to add to Cupertino-Pane?**
Having multiple panes that can stack on top of each other or that can be nested in each other.

*Describe your feature request **detailed***
Currently, there can only be one cupertino-pane on the page at once. However, there are several use-cases that having multiple cupertino-panes on one screen can make for interesting layouts. I added an image to see how it would look like. (Sorry it is crudely made).

![New Project](https://user-images.githubusercontent.com/22301549/99445737-a6457d00-2926-11eb-8d23-d153ad91fb12.jpg)

**Is there an alternative at the latest version?**

[ ] Yes (describe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
@akharag Have you already try to initiate 2 inversed panes  ?

**Comment by akharag** [comment]
Yes. 


page.typescript
```javascript
this.mainPane = new CupertinoPane(
      ".cupertino-pane-main", // Pane container selector
      {
        initialBreak: "top",
        breaks: {
          top: { enabled: true, height: screen.height * 0.65 },
          middle: { enabled: false },
          bottom: { enabled: true, height: screen.height * 0.1 },
        },
        buttonClose: false,
        inverse: true,
        // darkMode: false,
        // onDrag: () => console.log("Drag event"),
      }
    );

    this.childPane = new CupertinoPane(
      ".cupertino-pane-child",
      {
        initialBreak: "bottom",
        breaks: {
          top: { enabled: true, height: screen.height * 0.1 },
          middle: { enabled: false },
          bottom: { enabled: true }
        },
        buttonClose: false,
        inverse: true
      }
    )

    this.mainPane.present({ animate: true });
    this.childPane.present({animate: false});
```

page.html
```html

<div class="cupertino-pane-main">
    <div class="cupertino-pane-child">

    </div>
</div>
```

I get the error `cupertino-pane.esm.bundle.js:443 Cupertino Pane: specified selector or DOM element already in use`.

I just tried making the panes unnested and they both render to the screen.

**Comment by roman-rr** [comment]
> @akharag Have you already try to initiate 2 inversed panes  ? 

You must provide another element for new Pane instance. You can't create 2 panes from one DOM element. 

Create one more DOM element for second Pane or clone existing element.

**Comment by roman-rr** [comment]
@akharag Issue solved, or you still need to created 2 panes from nested elements for some reasons ?

**Comment by akharag** [comment]
The reason I wish to have them nested is because I want the content inside of the main element to automatically adjust when the child pane is moved.

**Comment by EinfachHans** [comment]
@akharag please describe a bit more detailed what you are trying to archieve

**Comment by akharag** [comment]
My idea is that when I would open the child pane, any content that was below it would be moved down. This is different from the normal behavior where the pane that is declared first just covers the one after it.

**Comment by roman-rr** [comment]
@akharag You must create two panes from different elements. Creating pane from other pane isn't supported.
