### ISSUE TITLE
[FEAT] Change color of bottom grey bar/draggable

### ISSUE THREAD

**Issue by akharag** [roman-rr/cupertino-pane#91]
**What are you trying to add to Cupertino-Pane?**
A way to change the bottom bar.

*Describe your feature request **detailed***
Is there a method, CSS property, or setting that can change things (specifically colors) inside of the draggable/div.move? I can see it in the console and can edit it there (it is the background property), but it seems I have to do a query and edit in JS at this point. Maybe I am missing something obvious though. 

Also, by default, should the draggable match the background of the pane? Changing the background property will only change the pane, leaving a colorful pane, but a white draggable. Image and code below: 

`.cupertino-pane-main {
  background: red;
  .draggable {
    background: coral;
  }
}`

![image](https://user-images.githubusercontent.com/22301549/99450794-ece8a680-2929-11eb-8bcc-0a23e6989a94.png)

**Is there an alternative at the latest version?**

[ ] Yes (describe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
@akharag 
Try this
```css
.cupertino-pane-wrapper .pane {
  background: red;
}
```

**Comment by DwieDima** [comment]
@roman-rr maybe its worth a feature request by providing `cssClass` property to `CupertinoSettings`.
By overriding `cupertino-pane-wrapper` and `pane` class this will be applied to all panes.
Is there a way to apply these styles to one pane only??

**Comment by roman-rr** [comment]
@DwieDima If your component will have a class 
```html
<div class="my-pane-1">
...
</div>
```

Class will be passed to whole parent wrapper 
```
.cupertino-pane-wrapper .my-pane-1 {

}
```

**Comment by DwieDima** [comment]
@roman-rr i'm using custom components. 
There is no effect when i apply a class

.html
```
  <cdfy-initial-device-card
    class="initial-pane"
  ></cdfy-initial-device-card>
```

.scss
```
.cupertino-pane-wrapper .initial-pane {
  background: transparent !important;
  box-shadow: none !important;
}

```
.ts
```
    const settings: CupertinoSettings = {
      buttonClose: false,
      showDraggable: false,
      bottomClose: true,
      parentElement: 'cdfy-device-map',
      preventClicks: true,
      initialBreak: 'bottom',
      breaks: {
        bottom: { enabled: true, bounce: true, height: 225 },
        middle: { enabled: true, bounce: true, height: 560 },
        top: { enabled: false },
      },
    };
    this.initialPane = new CupertinoPane('cdfy-initial-device-card', settings);
```

I'm using Ionic Angular.
CSS is applied to the page scss file, not global.scss

**Comment by roman-rr** [comment]
@DwieDima 
try it 
```scss
::ng-deep .cupertino-pane-wrapper.initial-pane .pane {
  background: transparent !important;
  box-shadow: none !important;
}
```

**Comment by DwieDima** [comment]
@roman-rr this seems to work, but also overwrite my other panes, too :(

**Comment by roman-rr** [comment]
@DwieDima could you please try to set other classes to other panes ? 
e.g. 
```html
<div class="initial-pane-1"></div>
<div class="initial-pane-2"></div>
<div class="initial-pane-3"></div>
```

```css
::ng-deep .cupertino-pane-wrapper.initial-pane-1 .pane {
  ...
}
::ng-deep .cupertino-pane-wrapper.initial-pane-2 .pane {
  ...
}
```
::ng-deep .cupertino-pane-wrapper.initial-pane-3 .pane {
  ...
}
