### ISSUE TITLE
[BUG] Pane gets placed offscreen after putting cordova app in the background

### ISSUE THREAD

**Issue by CodeWithOz** [roman-rr/cupertino-pane#97]
**Describe the bug**
The `translateY` of the `.pane` node changes after putting my app cordova app in the background (with the sheet at the mid breakpoint) and resuming the app. This first screenshot shows before putting the app in the background
![before-bug](https://user-images.githubusercontent.com/28525986/100027583-5f0b3080-2ded-11eb-9ec4-7e747abae445.png)

This second screenshot shows after putting the app in the background
![after-bug](https://user-images.githubusercontent.com/28525986/100027605-68949880-2ded-11eb-989d-6fd0c4d78bb6.png)

You can see the `translateY` of the `transform` changes significantly, so this causes the sheet to not be shown because it's positioned below the bottom edge of the screen. This **_doesn't_** happen when the sheet is at the `top` breakpoint, only `middle` (no need to check `bottom` because I set `bottomClose` to `true`). Is there a resize handler or something that fires and causes this problem?

**To Reproduce**
Sadly I haven't been able to reproduce this in a sample app, the bug doesn't happen.

**Expected behavior**
Putting the cordova app in the background and resuming shouldn't trigger the change in `translateY`.

**Screenshots**
See above.

**Smartphone (please complete the following information):**
 - Device: Tecno POP 2 Plus
 - OS: Android 8
 - Browser Chrome Webview
 - Version 85

**Comment by roman-rr** [comment]
@CodeWithOz Are you find a way to reproduce ?

**Comment by roman-rr** [comment]
@CodeWithOz I checked different actions with background application and don't find similar issues. Pane by default doesn't have resize handlers of background listeners. I will re-open if more cases appears or will have steps to reproduce. Thanks you anyway!
