### ISSUE TITLE
[BUG] In Ionic 5, spinners and alerts are displayed behind the pane

### ISSUE THREAD

**Issue by derek90** [roman-rr/cupertino-pane#99]
**Describe the bug**
Ionic spinners and alerts are shown behind the pane

**To Reproduce**
Fire any ionic spinner or alert while having a pane open

**Expected behavior**
When an ionic alert or spinner is shown, it should be over the pane

**Screenshots**
<img width="185" alt="Captura" src="https://user-images.githubusercontent.com/7257414/100244208-704f5c80-2f15-11eb-83b6-c985178ee882.PNG">
<img width="184" alt="Captura2" src="https://user-images.githubusercontent.com/7257414/100244212-70e7f300-2f15-11eb-9916-260d9bdbbb06.PNG">

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 87.0.4280.66

**Smartphone (please complete the following information):**
 - Device: Google Pixel XL
 - OS: Android 10
 - Browser: n/a
 - Version: n/a

**Additional context**
Inside the pane, I'm using a component tag, like this:
```
<div class="cupertino-pane">
  <app-forgot-password-modal></app-forgot-password-modal>  
</div>
```
The code that shows the spinner runs inside that app-forgot-password-modal component, but the alert is running in an interceptor that catches all the http errors, so I think that this behaviour will happend if its fire in a parent component too, it doesn't seem to have something to do with using a child component inside the pane.
My Cupertino settings are:
```
{ 
      parentElement: 'body', // Parent container
      buttonClose: false,
      darkMode: this.darkModeService.isDark,
      backdrop: true,
      bottomClose: true,
      breaks: {
        top: { enabled: false },
        middle: { enabled: true, height: window.screen.height / 2 }
      },
      onBackdropTap: () => {
        this.forgotPasswordModal.hide();
      }
}
```

**Comment by derek90** [comment]
Nevermind, I just needed to change the parentElement setting from 'body' to 'ion-app'

**Comment by roman-rr** [comment]
@derek90 All right. But in cases where you must use body as parent, you can specify z-index wrapper property with css.
